### PR TITLE
add JLRoutes to Networking section (references to #232)

### PR DESCRIPTION
**Pull request by miguelarauj1o**

### CODE REVIEW

**Comment by dkhamsing** [comment]
Hi sorry, JLRoutes should no go to Networking

**Comment by miguelarauj1o** [comment]
@dkhamsing, really? I followed the suggestion given by @lfarah

**Comment by dkhamsing** [comment]
@lfarah did say that but it looks like it should go somewhere else.. hold on until we figure it out

**Comment by miguelarauj1o** [comment]
@dkhamsing ok :)

**Comment by lfarah** [comment]
Sorry guys...

**Comment by dkhamsing** [comment]
No worries

**Comment by dkhamsing** [comment]
@miguelarauj1o pls add JLRoutes to a new section called `URL Scheme`

**Comment by miguelarauj1o** [comment]
@dkhamsing, done!

**Pull request merged**
