### PR TITLE
Added VIPER Module Template to Architecture Patterns

### PR DESCRIPTION
**Pull request by EvsenevDev**
## Project URL

https://github.com/EvsenevDev/VIPERModuleTemplate

## Category

Architecture Patterns

## Description

Added url to Architecture template.
Xcode Template of VIPER Module which generates all layers of VIPER.

## Why it should be included to `awesome-ios` (mandatory)
It's very useful template for me. I hope it can be useful for other iOS developers

## Checklist

- [x] Only one project/change is in this pull request
- [ ] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please update the Pull Request title to contain the library name</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
206 | [403](https://httpstatuses.com/403) | https://www.udemy.com/arkit-beginner-to-professional/?couponCode=CREATORS 
1498 | [301](https://httpstatuses.com/301) | https://github.com/mobilefirstinc/MFCard redirects to<br>https://github.com/RC7770/MFCard


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by EvsenevDev** [comment]
@lfarah could you check warnings?

**Comment by vsouza** [comment]
@EvsenevDev This project is a Xcode template, we can't accept this in `Architecture` category. We have to figure out which category this project suits better.

**Comment by EvsenevDev** [comment]
@vsouza what about this? 
https://github.com/vsouza/awesome-ios#other-xcode

**Comment by vsouza** [comment]
@EvsenevDev can you solve the conflicts?

**Comment by EvsenevDev** [comment]
@vsouza done 👍

**Comment by vsouza** [comment]
@EvsenevDev Thanks for contributing.

**Pull request merged**
