### PR TITLE
Add SwiftLinkPreview

### PR DESCRIPTION
**Pull request by LeonardoCardoso**
## Project URL
https://github.com/LeonardoCardoso/Swift-Link-Preview

## Description
It makes a preview from an url, grabbing all the information such as title, relevant texts and images.

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by victorgama** [comment]
Thanks!

**Comment by LeonardoCardoso** [comment]
Thank you too!

**Comment by lfarah** [comment]
Guys, we have a problem:
**SwiftLinkPreview** is under ```/Tools```, but [URLPreview](https://github.com/itsmeichigo/URLPreview), which has been added about 2 weeks ago in Awesome, is under ```XML/HTML/CSV``` since it is parsing the HTML.

What do we do?

**Comment by LeonardoCardoso** [comment]
@lfarah I will change the category and amend my commit tomorrow.

**Comment by LeonardoCardoso** [comment]
@lfarah If you guys think it's miscategorised, I could change the category and create a new PR.

**Comment by lfarah** [comment]
@victorgama what category do you think it's the best?

**Pull request merged**
