### PR TITLE
Add IBLinter.

### PR DESCRIPTION
**Pull request by arasu01**
IBLinter

## Project URL
https://github.com/kateinoigakukun/IBLinter

## Category
[Linter](https://github.com/vsouza/awesome-ios#linter)

## Description
A linter tool for Interface Builder
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 / tvOS 10 or later
- [ ] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 3 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
5 | Dupe | https://gitter.im/vsouza/awesome-ios 
6 | [500](https://httpstatuses.com/500) | https://api.travis-ci.org/vsouza/awesome-ios.svg?branch=master 
2699 | [503](https://httpstatuses.com/503) | https://boombox.io/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@arasu01 we should move this project to the `Linter` category.

https://github.com/vsouza/awesome-ios#linter

Thank you.

**Comment by arasu01** [comment]
@vsouza : Done.

**Comment by lfarah** [comment]
Thanks guys!

**Pull request merged**
