### PR TITLE
Add ARPieChart to Charts section

### PR DESCRIPTION
**Pull request by miguelarauj1o**
## Project URL
https://github.com/nero-tang/ARPieChart

## Description
Add ARPieChart to Charts section

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
hey @miguelarauj1o, thanks for contributing again!
We can't accept this lib because it won't compile in the latest Swift, so we gotta wait for @nero-tang to fix [issue 1](https://github.com/nero-tang/ARPieChart/issues/1)

**Comment by miguelarauj1o** [comment]
hey, @lfarah, thanks for checking this condition. I forgot totally!

**Comment by vsouza** [comment]
@miguelarauj1o and @lfarah  it's ok now?

**Comment by lfarah** [comment]
@vsouza we gotta wait for them to update the lib

**Comment by dkhamsing** [comment]
Let's close this
Feel free to reopen when ready

**Comment by miguelarauj1o** [comment]
I agree. No problem.

**Pull request closed without merging**
