### PR TITLE
Added SwiftyTask to GDC section

### PR DESCRIPTION
**Pull request by Albin-CR**
Added SwiftyTask to GDC section

An extreme queuing system with high performance for managing all task in app with closure

## Project URL
https://github.com/CR-Creations/SwiftyTask

## Description
Made changes in GCD section added SwiftyTask bellow
 
## Why it should be included to `awesome-ios` (optional)
An extreme queuing system with high performance for managing all task in app with closure
This can make the queueing process very easy 

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1038 | [301](https://httpstatuses.com/301) | https://tapglue.github.io/ redirects to<br>http://www.tapglue.com/
2207 | [301](https://httpstatuses.com/301) | https://github.com/s4cha/AssetChecker redirects to<br>https://github.com/freshOS/AssetChecker


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Albin-CR** [comment]
Can anyone tell me how I can solve this issue?

**Comment by lfarah** [comment]
Hey @Albin-CR, don't worry about it

**Comment by lfarah** [comment]
Hey @Albin-CR, nice lib!
Before I can approve, please fix the issue above

**Comment by Albin-CR** [comment]
@lfarah Created new pull request [Link ](https://github.com/vsouza/awesome-ios/pull/1462)

**Pull request closed without merging**
