### PR TITLE
Add Swrve to push providers

### PR DESCRIPTION
**Pull request by oisin**
## Description

 
Adding Swrve to push providers

## Why it should be included to `awesome-ios` (optional)

Swrve provides push and other good stuff! Checklist below only partially applies as it's not a project in its own right.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 4 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1354 | [301](https://httpstatuses.com/301) | https://github.com/SwiftOnEdge/Edge redirects to<br>https://github.com/skylab-inc/Edge
2197 | [404](https://httpstatuses.com/404) | https://github.com/rob-nash/CollapsableTable 
2217 | [404](https://httpstatuses.com/404) | https://github.com/rob-nash/PageFeedControl 
2256 | [404](https://httpstatuses.com/404) | https://github.com/rob-nash/CollapsibleTable 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by aaronjsutton** [comment]
@lukecrum I disagree since this is a service being added to a list of push providers, not a framework. Be sure to check out the project before proposing changes.

**Comment by lukecrum** [comment]
whoops. my bad 😦

**Comment by arasu01** [comment]
Nice one. What do you guys think?

**Comment by lfarah** [comment]
Thanks y'all for contributing 👍

**Comment by oisin** [comment]
👍

**Pull request merged**
