### PR TITLE
Add Bohr by @nschucky to Table View / Collection View section

### PR DESCRIPTION
**Pull request by nschucky**
## Project URL

https://github.com/DavdRoman/Bohr

## Description

Add Bohr by @nschucky to Table View / Collection View section

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by dkhamsing** [comment]
@nschucky hey you misunderstood me, the by is by the project owner
here should be `by @DavdRoman`

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2005 | [504](https://httpstatuses.com/504) | https://littlebitesofcocoa.com/ 
2048 | [301](https://httpstatuses.com/301) | https://appicontemplate.com/ios8/ redirects to<br>https://appicontemplate.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by nschucky** [comment]
@dkhamsing  my bad dude, sorry for that.

**Comment by dkhamsing** [comment]
@lfarah should "settings" projects be moved to Form ?

**Comment by nschucky** [comment]
@dkhamsing i had this doubt, but there is another project of settings in the table view section.

**Comment by dkhamsing** [comment]
@nschucky yeah might have to move that one too

I am merging this 
Thx!

**Comment by lfarah** [comment]
Thanks @nschucky again. You've been an **awesome** help!

**Pull request merged**
