### PR TITLE
Add Bond

### PR DESCRIPTION
**Pull request by Isaac12x**
Added Swift Bond

### CODE REVIEW

**Comment by victorgama** [comment]
As it is a Swift item, please add the orange diamond to its entry. (:large_orange_diamond:)

**Comment by lfarah** [comment]
Please take the space. Instead of Swift Bond, put SwiftBond

**Comment by Isaac12x** [comment]
Updated, sorry for the delay :)

**Comment by lfarah** [comment]
Still have conflicts. @Isaac12x

**Pull request closed without merging**
