### PR TITLE
Add awesome-interview-questions to Other Awesome Lists

### PR DESCRIPTION
**Pull request by yoha**
Same as title above

## Project URL

https://github.com/MaximAbramchuck/awesome-interview-questions

## Description

Same as title above
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [] Supports iOS 9 or later
- [] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @yoha, can you [put this url](https://github.com/MaximAbramchuck/awesome-interview-questions#ios) instead?

Thanks for contributing again! 🎉

**Comment by yoha** [comment]
@lfarah url and description have been updated accordingly.

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2252 | [301](https://httpstatuses.com/301) | http://www.ioscreator.com/ redirects to<br>https://www.ioscreator.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dkhamsing** [comment]
Thank you for contributing to `awesome-ios` 😄

**Pull request merged**
