### PR TITLE
Add HTPullToRefresh

### PR DESCRIPTION
**Pull request by hoang-tran**
Add pod HTPullToRefresh.

## Project URL
https://github.com/hoang-tran/HTPullToRefresh

## Description
There is no pod that supports horizontal pull to refresh capability so I made one. It also supports adding multiple pull to refresh views into one single UIScrollView.

## Checklist
- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found links issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
157 | [503](https://httpstatuses.com/503) | https://www.raywenderlich.com/38557/learn-to-code-ios-apps-1-welcome-to-programming 
1926 | [500](https://httpstatuses.com/500) | https://code.facebook.com/ios/ 
1946 | [503](https://httpstatuses.com/503) | https://www.raywenderlich.com/tutorials 
1981 | [503](https://httpstatuses.com/503) | https://www.raywenderlich.com/newsletter 
2009 | [503](https://httpstatuses.com/503) | https://www.raywenderlich.com/rwpodcast 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Nothing related to the lib

**Comment by lfarah** [comment]
Cool lib, @hoang-tran. Thanks for contributing! 😄

**Comment by hoang-tran** [comment]
wow, that was quick. Thanks @lfarah  😉

**Comment by lfarah** [comment]
You're welcome! 🚀🚀🚀

**Pull request merged**
