### PR TITLE
[template] add reason for inclusion

### PR DESCRIPTION
**Pull request by dkhamsing**
@lfarah @vsouza 

tweaking the template, your input would be great

### CODE REVIEW

**Comment by lfarah** [comment]
Hmmm I don't think it is a good idea because we're making the lib creators have to think of arguments.
By having the description I am able to know what the lib is about and then open the link to see if the lib is good for awesome

**Comment by dkhamsing** [comment]
@lfarah why is it bad that they have to have an argument to be on the list? if even they can't.. that would be bad

**Comment by lfarah** [comment]
I feel like this question is kinda intimidating and it looks like "We're AwesomeiOS. Is your lib good enough to be here?"

**Comment by dkhamsing** [comment]
I feel that's ok

What do @vsouza @victorgama think

**Comment by vsouza** [comment]
I agree with @lfarah Would be nice have a clear reason to include lib on list.

**Comment by dkhamsing** [comment]
Hey @vsouza you are confusing me 

Do you approve this change or not

Pls merge if you approve or close it you don't


Thx!

**Comment by lfarah** [comment]
Hahahahhahaha I was thinking the same thing....

**Comment by vsouza** [comment]
Sorry, various days without sleep well.

I think it will be nice have some reason to include some library in awesome-ios, but I agree with @lfarah it could be kinda intimidating. So, we can add this new template, but it's not mandatory have a clear reason to approve inclusion on the list.

So, when we have some doubt about new projects to be included on list, we can request PR author to insert reason.

What do you guys think?

@dkhamsing @victorgama

**Comment by dkhamsing** [comment]
Sounds good to me

**Comment by lfarah** [comment]
So should we do this?

## [optional] Why it should be included to `awesome-ios`

**Comment by dkhamsing** [comment]
@lfarah updated

**Comment by vsouza** [comment]
Good job guys ❤️

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 1 link issue</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1959 | [301](https://httpstatuses.com/301) | https://github.com/metasmile/ai2app redirects to<br>https://github.com/metasmile/ai2appiconset


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Pull request merged**
