### PR TITLE
Added SwiftyVIPER project

### PR DESCRIPTION
**Pull request by codytwinton**
## Project URL
https://github.com/codytwinton/SwiftyVIPER

## Description
This project enables easy use of VIPER architecture in your project.
 
## Why it should be included to `awesome-ios`
VIPER is one of many great programming architectures. I wanted using it to be super simple and easy. That's why I created this project.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
18 | [503](https://httpstatuses.com/503) | https://twitter.com/awesome_ios 
1013 | Error | https://boxcar.io <br> Net::ReadTimeout


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by codytwinton** [comment]
@lfarah Is this something I need to resolve manually?

**Comment by dkhamsing** [comment]
No thx

**Comment by lfarah** [comment]
Hey @codytwinton, thanks for contributing! 👍

VIPER is really interesting and your library makes it really simple to use.

I just need you to [fix this issue](https://github.com/codytwinton/SwiftyVIPER/issues/1) before I approve your PR.

**Comment by codytwinton** [comment]
@lfarah - I've updated the `README.md` file.

**Pull request merged**
