### PR TITLE
Added AlexaSkillsKit to new category called 'Personal Assistant'.

### PR DESCRIPTION
**Pull request by yoha**
Same as the title.

## Project URL

https://github.com/choefele/AlexaSkillsKit

## Description

I originally thought this library can be placed under machine learning but I think it fits better under Personal Assistant category and more libraries can be added there from here on since Siri has been opened now for future third party libraries supporting it. 
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
419 | [404](https://httpstatuses.com/404) | https://github.com/faunadb/faunadb-swift 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
@vsouza?

**Comment by vsouza** [comment]
We can create a new category only if we have more projects to join on new category. I agree with new category name, but we need more projects for now.

Or we can create a subcategory in Machine Learning...

**Comment by yoha** [comment]
@vsouza That makes sense. How about the following categorization?

# Machine Learning
## Artificial Intelligence
- Swift-AI
- Swift-Brain
- AIToolbox

## Personal Assistant
- AlexaSkillsKit

## Miscellaneous
- Tensorflow-iOS

**Comment by yoha** [comment]
I screwed up my fork. Will create a new pr.

**Pull request closed without merging**
