### PR TITLE
Add Walker and Morgan

### PR DESCRIPTION
**Pull request by RamonGilabert**
https://github.com/RamonGilabert/Walker
https://github.com/RamonGilabert/Morgan

Hope you like it! :)

### CODE REVIEW

**Comment by RamonGilabert** [comment]
Other stuff got edited too for some reason. :heart:

**Comment by lfarah** [comment]
Hey @RamonGilabert, what's the difference between the two libraries? The READMEs are really good, but it didn't explain much

**Comment by RamonGilabert** [comment]
Hey @lfarah! :) While the first library, Walker, is an animation engine that provides you with a sugared way to do animations, the second library, Morgan, is a work in progress with a set of different animations.

We could say that Walker is the engine where Morgan is just a set of predefined animations.

**Comment by lfarah** [comment]
@RamonGilabert awesome! Really well done. Congrats. :smile:

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:33039 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMT-001xT3-QP
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:38:01 -0400
Date: Mon, 14 Mar 2016 13:29:23 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457987363;
	bh=lVP4+HmeW/Krot6+ATPd2y229fAX41qlDpQBIgyT4l0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=NaRDsVMvnBfwcfrE7+jF8isfT5eOonFt3vRFcwrTAhuv+YokqJJ5feop3kKY3bhq4
	 pxfm9Tp0WB7h8NHweBfxZxRUnYGmFwJ87NdRTLKW7qnGYb+RToTB0E9UifFyqHkeAI
	 Z8amDe0kyktmkFd74MYN2cpu7MSJwgrg3PjjAncI=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:34205 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMd-001xYL-Tg
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:38:11 -0400
Date: Mon, 14 Mar 2016 13:29:27 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457987367;
	bh=OWqHcba3T7+D+ODQH2LIHBmYLVfAouWg+jWeMq76YIE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=oDKaj3H39AOonsk9XVvWz2CCJDpRDY74Q0OOxsHGbK3BiQixOBk5QxmHqbUPH1Vep
	 CtViaL0S+eub8lS4flLIoXLFMDQB714H+zC0mHwGbR1KV8OtbTLV9Sv04RhGNwTezT
	 0GBR4021R9NC98z2HRd3RUKW3Af3IvHl69HEPJHc=

**Pull request merged**
