### PR TITLE
Added SHPopup

### PR DESCRIPTION
**Pull request by iamshezad**
## Project URL
https://github.com/iamshezad/SHPopup

## Category
popup

## Description
SHPopup is a simple lightweight library for popup view.
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2542 | Error | http://alcatraz.io/ <br> getaddrinfo: Name or service not known


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by iamshezad** [comment]
@arasu01 created a new pull request. 
can you please solve the above issue.

**Comment by arasu01** [comment]
Thanks.

**Comment by iamshezad** [comment]
@arasu01 Thank you for considering.

**Pull request merged**
