### PR TITLE
Add AwesomeSpotlightView to Walkthrough / Intro / Tutorial

### PR DESCRIPTION
**Pull request by aleksandrshoshiashvili**
## Project URL

https://github.com/aleksandrshoshiashvili/AwesomeSpotlightView

## Description

AwesomeSpotlightView is a nice and simple libriary for iOS written on Swift 3. It's highly customizable and easy-to-use tool. Works perfectly for tutorial or coach in your app. 

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2448 | [503](https://httpstatuses.com/503) | http://www.teehanlax.com/tools/iphone/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by naeemshaikh90** [comment]
Hey @aleksandrshoshiashvili nice lib, we would like you to fix [this issue](https://github.com/aleksandrshoshiashvili/AwesomeSpotlightView/issues/1) before we can merge your PR.

**Comment by aleksandrshoshiashvili** [comment]
@naeemshaikh90 Done

**Comment by naeemshaikh90** [comment]
Thanks for contributing to `awesome-ios` 🎉

**Pull request merged**
