### PR TITLE
Newsletter announcement spacing

### PR DESCRIPTION
**Pull request by lfarah**
@hevertonrodrigues told me the spacing was a little bit off, so I'm trying to follow his ideas

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
178 | [301](https://httpstatuses.com/301) | http://www.codeproject.com/Articles/88929/Getting-Started-with-iPhone-and-iOS-Development redirects to<br>https://www.codeproject.com/articles/88929/getting-started-with-iphone-and-ios-development
995 | [301](https://httpstatuses.com/301) | https://github.com/alvinvarghese/EasyIAPs redirects to<br>https://github.com/aaalveee/EasyIAPs


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dkhamsing** [comment]
Uh this is a temporary change?

**Comment by lfarah** [comment]
@dkhamsing it would be a temporary thing since we're working on the website, which will have an AwesomeiOS.Weekly page.
I understand that you didn't like the changes... Do you have any ideas on how to make it better?

**Comment by dkhamsing** [comment]
I think it is fine if it is temporary :)

**Pull request merged**
