### PR TITLE
Adding PrivacyFlash Pro

### PR DESCRIPTION
**Pull request by SebastianZimmeck**
With PrivacyFlash Pro developers can generate a privacy policy for their iOS app from its code. PrivacyFlash Pro is based on an academic research project at Wesleyan University.

## Project URL

https://github.com/privacy-tech-lab/privacyflash-pro

## Category

Consent

## Description

Add PrivacyFlash Pro to the readme

## Why it should be included to `awesome-ios` (mandatory)
PrivacyFlash Pro is a privacy policy generator for iOS apps written in Swift. It helps developers to create meaningful privacy policies by automatically analyzing app code. It also guides developers through a wizard questionnaire covering policy provisions that cannot be detected from the app code (e.g., how long data is retained). PrivacyFlash Pro is intended to increase privacy transparency in the iOS app ecosystem.

## Checklist

- [x] Has 50 GitHub stargazers or more
- [x] Only one project/change is in this pull request
- [x] Isn't an archived project
- [x] Has more than one contributor
- [ ] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @SebastianZimmeck, thanks for contributing. 
PrivacyFlash Pro looks really interesting, but unfortunately we cannot merge this PR until you add some unit tests.
Let me know if you need any help 👍

**Comment by SebastianZimmeck** [comment]
Thanks for your explanation, @lfarah. We should be able to provide some unit tests. Could you say a bit more on what you would expect? For example, do you require a particular testing framework, a minimum number of tests, continuous integration, ...?

**Comment by lfarah** [comment]
Hey @SebastianZimmeck, no need to be fancy at all! I would be happy with some XCTests.

**Comment by SebastianZimmeck** [comment]
Great! Thanks, @lfarah. We will be working on that and report back ...

**Comment by vsouza** [comment]
@SebastianZimmeck I'll close this PR and feel free to reopen once it is ready.

Thanks.

**Comment by SebastianZimmeck** [comment]
@vsouza, we added [unit tests](https://github.com/privacy-tech-lab/privacyflash-pro/tree/master/tests) now. Should I open a new PR?

**Pull request closed without merging**
