### PR TITLE
Add GlitchLabel

### PR DESCRIPTION
**Pull request by kciter**
Glitching UILabel for iOS

## Project URL
https://github.com/kciter/GlitchLabel

## Description
Glitching UILabel like [this](http://codepen.io/paultreny/pen/nJyvG).

## Checklist

- [x] Only one project is in the request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 and later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by dkhamsing** [comment]
Travis CI is unrelated and can be fixed separately

**Comment by kciter** [comment]
I fixed it!
https://github.com/kciter/GlitchLabel/blob/master/README.md

**Comment by kciter** [comment]
I really fixed it. :-)

**Comment by dkhamsing** [comment]
@kciter thanks! can you rebase to only have one update in this pull (glitch label)

**Comment by kciter** [comment]
@dkhamsing I did it! :)

**Comment by lfarah** [comment]
When I read the title of the lib I was like
> Wait, what?

But then I read the ```README.md``` and the effect is really cool.
Congrats 😄

**Comment by dkhamsing** [comment]
@lfarah @kciter yea looks very cool

**Comment by kciter** [comment]
@lfarah @dkhamsing Thanks! 😄

**Pull request merged**
