### PR TITLE
Added NotificationBanner

### PR DESCRIPTION
**Pull request by Daltron**
## Project URL
https://github.com/Daltron/NotificationBanner

## Description
Added NotificationBanner to the `UI/Alerts` Category. 
 
## Why it should be included to `awesome-ios`

NotificationBanner is an extremely customizable and lightweight library that makes the task of displaying in app notification banners and drop down alerts an absolute breeze in iOS.

It also has a built in banner queue system which makes displaying multiple banners that happen within the same timeframe easier than ever.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by Daltron** [comment]
@naeemshaikh90 Even though merged, NotificationBanner isn't appearing on the README. Any idea on why that may be the case?

**Comment by nschucky** [comment]
weird, looks like the only one merged was the commit 0e71a1c, any idea @naeemshaikh90?

**Comment by naeemshaikh90** [comment]
@Daltron , @nschucky Sorry for late reply. It looks strange, let me check this out.

**Comment by naeemshaikh90** [comment]
@Daltron I am not able to find why this happened, you can submit another PR for `NotificationBanner`.

**Comment by naeemshaikh90** [comment]
#1607

**Pull request merged**
