### PR TITLE
added GoogleMaterialDesignIcons

### PR DESCRIPTION
**Pull request by nschucky**
## Project URL
https://github.com/dekatotoro/GoogleMaterialDesignIcons

## Description
Added GoogleMaterialDesignIcons

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 6 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
529 | [301](https://httpstatuses.com/301) | https://github.com/szk-atmosphere/MisterFusion redirects to<br>https://github.com/marty-suzuki/MisterFusion
659 | [301](https://httpstatuses.com/301) | https://github.com/szk-atmosphere/SABlurImageView redirects to<br>https://github.com/marty-suzuki/SABlurImageView
824 | [302](https://httpstatuses.com/302) | https://www.onesignal.com redirects to<br>https://onesignal.com/
1065 | [301](https://httpstatuses.com/301) | https://github.com/szk-atmosphere/SAHistoryNavigationViewController redirects to<br>https://github.com/marty-suzuki/SAHistoryNavigationViewController
1066 | [301](https://httpstatuses.com/301) | https://github.com/szk-atmosphere/SAInboxViewController redirects to<br>https://github.com/marty-suzuki/SAInboxViewController
1139 | [301](https://httpstatuses.com/301) | https://github.com/szk-atmosphere/URLEmbeddedView redirects to<br>https://github.com/marty-suzuki/URLEmbeddedView


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Should be under /Font

**Comment by dkhamsing** [comment]
not sure why you have so many commits here
please open a new pull request with https://github.com/vsouza/awesome-ios as your starting point

**Comment by nschucky** [comment]
my bad, really bad, some git mistakes sorry.

**Pull request closed without merging**
