### PR TITLE
Added AZDialogViewController

### PR DESCRIPTION
**Pull request by Minitour**
I added one of my frameworks in the Pop Up section.

## Project URL
https://github.com/Minitour/AZDialogViewController

## Description
A highly customizable alert dialog controller that mimics Snapchat's alert dialog.

## Checklist

- [X] Only one project/change is in this pull request
- [X] Addition in chronological order (bottom of category)
- [X] Supports iOS 9 / tvOS 10 or later
- [X] Supports Swift 3
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

### CODE REVIEW

**Comment by victorgama** [comment]
@Minitour Hi Antonio! Thank you for contributing. 
Would you mind adding an installation section to your Readme?

Thanks! ✨

**Comment by Minitour** [comment]
@victorgama No problem, I'm on it.

**Comment by Minitour** [comment]
@victorgama done.

**Comment by vsouza** [comment]
thanks for contributing @Minitour

**Pull request merged**
