### PR TITLE
Add Flawless App to the UI Testing

### PR DESCRIPTION
**Pull request by LisaDziuba**
## Project URL
https://flawlessapp.io/
## Description
Tool for visual quality check of mobile app right inside iOS simulator.
## Why it should be included to `awesome-ios` (optional)
It’s useful tool for iOS and macOS developers, who wish to deliver applications with high visual quality. 
## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by LisaDziuba** [comment]
Flawless is easy-to-use diff tool, which compares initial design and implementation right inside iOS simulator. The tool helps spot any visual difference between expected result and initial design. That saves time and money! It’s mine and Ahmed Sulaiman startup :)

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks: )</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2425 | Error | https://iconresizer.com/ <br> Connection refused - connect(2) for "iconresizer.com" port 443


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @LisaDziuba, thanks for contributing and good job on Flawless. I showed it to my coworkers and they loved it!

**Comment by onmyway133** [comment]
🚀

**Comment by LisaDziuba** [comment]
@onmyway133 and @lfarah, 
thank you for your support 😊

**Pull request merged**
