### PR TITLE
A replacement of default action sheet, but has very simple usage.

### PR DESCRIPTION
**Pull request by khuong291**
## Project URL
https://github.com/khuong291/kpactionsheet

## Description
A replacement of default action sheet, but has very simple usage.
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by khuong291** [comment]
@naeemshaikh90 , still has conflicts :|

**Comment by naeemshaikh90** [comment]
@khuong291 try to add in from [awesome-ios](https://github.com/vsouza/awesome-ios)'s [README.md](https://github.com/vsouza/awesome-ios/blob/master/README.md)

**Comment by khuong291** [comment]
I edit from your README.md, see the files changed, I just change 1 line.

**Comment by naeemshaikh90** [comment]
screen shot 2017-03-01 at 10 23 06 am

Hey @khuong291 try to remove all branches and than start over again. If still conflicts occurs than try to remove your forked repo completety than start over again by forking latest `awesome-ios` repo. 🙂

**Pull request closed without merging**
