### PR TITLE
Add AIToolbox to Machine Learning section

### PR DESCRIPTION
**Pull request by KevinCoble**
## Project URL
https://github.com/KevinCoble/AIToolbox.git

## Description
Added AIToolbox to the machine learning section.  While the README.md file is not alphabetized, whatever is ordering the sections needs to be looked at, as Maps is coming before Machine Learning

## Checklist

- [x] Only one project is in the request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 and later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by dkhamsing** [comment]
Kevin, can you add https://github.com/KevinCoble/AIToolbox instead of https://github.com/KevinCoble/AIToolbox.git

**Comment by KevinCoble** [comment]
Fixed the link (Forgot to remove the .git when using the GitHub 'push' link button to copy the link)

If necessary, I will look into the Travis CI build when I can (but it will probably be Thursday before I can)

Thanks for considering my framework.

**Comment by lfarah** [comment]
@KevinCoble good job on the awesome framework! 😃

**Comment by dkhamsing** [comment]
Kevin 
Looks good, should be ok to merge

**Pull request merged**
