### PR TITLE
Move Synx

### PR DESCRIPTION
**Pull request by dkhamsing**
Synx is not a plugin so I moved it..

### CODE REVIEW

**Comment by lfarah** [comment]
You did the right thing, but it still can't be outside a category, so we need to find a better place for it

**Comment by dkhamsing** [comment]
How about a sub section called `Misc`

**Comment by dkhamsing** [comment]
@lfarah do you want me to create a sub section called `Misc` under Xcode?

**Comment by lfarah** [comment]
Ok... Let's do it!

**Pull request closed without merging**
