### PR TITLE
Update Carnival's URL

### PR DESCRIPTION
**Pull request by samjarman**

### CODE REVIEW

**Comment by victorgama** [comment]
Hi Sam! I noticed Carnival appears in two distinct categories. Would you mind to remove it from one of them? Thanks.

**Comment by samjarman** [comment]
Which do you think is more appropriate?

**Comment by victorgama** [comment]
I see you are one of Carnival developers. Feel free to pick one. :smiley:

**Comment by samjarman** [comment]
done

**Comment by dkhamsing** [comment]
Thanks

**Pull request merged**
