### PR TITLE
add a iOS network debug library "NetworkEye"

### PR DESCRIPTION
**Pull request by coderyi**

### CODE REVIEW

**Comment by victorgama** [comment]
Hmm. I think this should go to `Code Quality` rather than `Networking`. @dkhamsing?

**Comment by dkhamsing** [comment]
Networking is fine

**Comment by dkhamsing** [comment]
@victorgama let me know if you want to make a change

**Comment by victorgama** [comment]
@dkhamsing Ah, no problem. I just thought that since it is probably more useful during development than production, `Code Quality` seemed best; but networking is fine as well. :shipit:

**Comment by dkhamsing** [comment]
Cool thanks

**Pull request merged**
