### PR TITLE
Add Mockit description in README.md

### PR DESCRIPTION
**Pull request by sabirvirtuoso**
## Project URL
https://github.com/sabirvirtuoso/Mockit

## Description
A simple mocking framework for Swift, inspired by the famous Mockito for Java. It provides clean syntax and facilitates writing readable unit tests in Swift.

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by victorgama** [comment]
@sabirvirtuoso Thank you for the contribution! Would you mind to move Mockit to the `Other Testing` category?

**Comment by sabirvirtuoso** [comment]
@victorgama Done.

**Comment by lfarah** [comment]
@sabirvirtuoso good job on the lib! I was talking about Mocking in a code interview yesterday and the concept is really amazing.

**Comment by sabirvirtuoso** [comment]
Thanks for the feedback.

On Wed, Jun 1, 2016 at 10:27 AM, Lucas Farah <notifications@github.com>
wrote:

> @sabirvirtuoso <https://github.com/sabirvirtuoso> good job on the lib! I
> was talking about Mocking in a code interview yesterday and the concept is
> really amazing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/vsouza/awesome-ios/pull/855#issuecomment-222889453>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKNcGIGXjsOCZgv1Vku37zoVPNDMpVaQks5qHQo-gaJpZM4IquuR>
> .
>



-- 
Regards,

Syed Sabir Salman-Al-Musawi
Software Engineer
Therap Services LLC, http://www.therapservices.net/

Phone: +8801680464463
Github: *https://github.com/sabirvirtuoso
<https://github.com/sabirvirtuoso>*

**Pull request merged**
