### PR TITLE
Add Presenter

### PR DESCRIPTION
**Pull request by muukii**
Add Presenter

## Project URL
https://github.com/muukii/Presenter

## Description
Screen transition with safe and clean code. 

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by dkhamsing** [comment]
@lfarah should this be moved to Modal Transition

**Comment by muukii** [comment]
@dkhamsing 
@lfarah 
I've fixed.
Could you check it?

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dkhamsing** [comment]
thx

**Comment by muukii** [comment]
thank you!

**Pull request merged**
