### PR TITLE
added Typist-keybaord manager

### PR DESCRIPTION
**Pull request by totocaster**
Added UI Keyboard manager written in Swift 3.

## Project URL
https://github.com/totocaster/Typist

## Description
Typist is small, drop-in Swift UIKit keyboard manager for iOS apps. It helps you manage keyboard's screen presence and behavior without notification center and Objective-C.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 3 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1262 | [301](https://httpstatuses.com/301) | https://github.com/mrugrajsinh/MVMaterialView redirects to<br>https://github.com/TheMrugraj/MVMaterialView
1779 | [301](https://httpstatuses.com/301) | https://github.com/mrugrajsinh/MVAutocompletePlaceSearchTextField redirects to<br>https://github.com/TheMrugraj/MVAutocompletePlaceSearchTextField
1973 | [301](https://httpstatuses.com/301) | https://github.com/neonichu/fastlane-plugin-appicon redirects to<br>https://github.com/KrauseFx/fastlane-plugin-appicon


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Hey @totocaster, nice library! 😉 

I need you [to fix this](https://github.com/totocaster/Typist/issues/1) before I can merge your pull request.

Thanks for contributing! 🎉

**Comment by totocaster** [comment]
Hi @lfarah, all fixed. Please review and merge if possible. Thanks for all your comments!

**Comment by lfarah** [comment]
Perfect!
Thanks again for contributing 😄

**Pull request merged**
