### PR TITLE
CRPageViewController & CRRulerControl

### PR DESCRIPTION
**Pull request by vladdmitriev**
## Project URL
https://github.com/Cleveroad/CRPageViewController
https://github.com/Cleveroad/CRRulerControl

## Description
While a standard page view allows you to navigate between pages by using simple gestures, our component goes further
 
## Why it should be included to `awesome-ios` (optional)
I think this useful component should be included to awesome-ios, because it allows defining a page size by setting width and heights manually. Thus, users will be able to control the placement of pages on the screens in the way which is more suitable for them.

### CODE REVIEW

**Comment by vladdmitriev** [comment]
@dkhamsing Hello! I'm sorry but I have tried to add only one library CRPageViewController.

The second had been added before. It's my fault.

**Comment by vladdmitriev** [comment]
@dkhamsing How can I fix it?

**Comment by dkhamsing** [comment]
Hm this is not ideal
Let's close this and can you start over, always from https://github.com/vsouza/awesome-ios

Can you do one pull request per project

Thx

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Pull request closed without merging**
