### PR TITLE
Added Benchmark

### PR DESCRIPTION
**Pull request by WorldDownTown**
## Project URL
https://github.com/WorldDownTown/Benchmark

## Description
The Benchmark⏲ module provides methods to measure and report the time used to execute Swift code.

## Checklist
- [x] Only one project is in the request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
I think it would be better under ```Tools```. @dkhamsing what do you think?

**Comment by dkhamsing** [comment]
Sounds good

@WorldDownTown also please readd the tutorial link you deleted

**Comment by dkhamsing** [comment]
In general, you pull request should only be about what you are adding/updating
Thx

**Comment by WorldDownTown** [comment]
@dkhamsing I removed unecessary commit.

**Comment by dkhamsing** [comment]
Can you move it to Tools? Thx

**Comment by WorldDownTown** [comment]
@dkhamsing OK. I moved the line. Please check it.

**Comment by dkhamsing** [comment]
Thx

**Pull request merged**
