### PR TITLE
FTFoldingPaper - Emulates paper folding effect.

### PR DESCRIPTION
**Pull request by monofire**
## Project URL
[FTFoldingPaper](https://github.com/monofire/FTFoldingPaper)

## Description
FTFoldingPaper is a UI framework built on top of the Core Animation. It is designed to emulate paper folding effects and can be integrated with UITableView, used independently or paired with other UI components.

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
685 | [404](https://httpstatuses.com/404) | https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ios_examples/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by monofire** [comment]
Obsolete link is not mine... 
And it seems it is not supported by Tensor Flow anymore
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ios_examples/

**Comment by lfarah** [comment]
Hey @monofire, please rebase your PR

**Comment by monofire** [comment]
rebased

**Comment by lfarah** [comment]
@monofire thanks for contributing. You're awesome! 🎉

**Pull request merged**
