### PR TITLE
Use Danger

### LINKED ISSUE #972: Implement Danger
Dear @dkhamsing, our CI God,
Do you think it would be cool to add [Danger](http://danger.systems/reference.html) to AwesomeiOS?
If so, can you do it? I don't wanna mess up with the bots you're already running

### PR DESCRIPTION
**Pull request by dkhamsing**
Close #972

### CODE REVIEW

**Comment by dkhamsing** [comment]
wip dont merge yet
thx

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Please provide a summary in the Pull Request description</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Please only add one library per Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dkhamsing** [comment]
@lfarah looks ok for integration, Dangerfile probably could use some tune up

**Comment by lfarah** [comment]
Thanks, @dkhamsing. You're the best!

**Pull request merged**
