### PR TITLE
Add MRArticleViewController by @mrigdon to UI section

### PR DESCRIPTION
**Pull request by mrigdon**
## Project URL
https://github.com/mrigdon/MRArticleViewController

## Description
Add MRArticleViewController by @mrigdon to UI section

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1765 | [301](https://httpstatuses.com/301) | https://github.com/wtmoose/TLLayoutTransitioning redirects to<br>https://github.com/SwiftKickMobile/TLLayoutTransitioning
1768 | [301](https://httpstatuses.com/301) | https://github.com/wtmoose/TLIndexPathTools redirects to<br>https://github.com/SwiftKickMobile/TLIndexPathTools


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mrigdon** [comment]
Is this danger a me problem?

**Comment by lfarah** [comment]
Don't worry about that

**Comment by lfarah** [comment]
Thanks for contributing! 🎉

**Pull request merged**
