### PR TITLE
EasyNotificationBadge - UIView extension that adds a notification badge.

### PR DESCRIPTION
**Pull request by Minitour**
## Project URL

https://github.com/Minitour/EasyNotificationBadge
## Description

UIView extension that adds a notification badge.

## Checklist

- [x] Only one project/change is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @Minitour, thanks for contributing! 😄

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
904 | Dupe | https://github.com/paypal/PayPal-iOS-SDK 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
@Minitour please add it to the bottom of the category.

**Comment by Minitour** [comment]
@lfarah done.

**Comment by lfarah** [comment]
Thanks! 😄

**Pull request merged**
