### PR TITLE
Added CFSA to readme

### PR DESCRIPTION
**Pull request by nadav96**
## Project URL

[compiler-friendly-storyboard-access](https://github.com/nadav96/compiler-friendly-storyboard-access/blob/master/README.md)

## Why it should be included to `awesome-ios` (optional)
I'm amazed Xcode still forces us to access Storyboards and controllers using raw strings (which could easily result with unexpected runtime exceptions, with a typo for example), this build time python script will scan the project for all storyboard files, and list all the available controllers group by storyboards using enums and structs, no more runtime exceptions in this regard!!

## Checklist

- [X] Only one project/change is in this pull request
- [X] Addition in chronological order (bottom of category)
- [X] Supports iOS 9 / tvOS 10 or later
- [X] Has a **clear** README in English
- [X] Supports Swift 3
- [X] Has a commit from less than 2 years ago

### CODE REVIEW

**Comment by nschucky** [comment]
@lfarah, @dkhamsing, @naeemshaikh90 what you guys think? is it under /Data Structures Algorithms the best place for this lib?

**Comment by naeemshaikh90** [comment]
I think it should be in [utility](https://github.com/vsouza/awesome-ios#utility) or [tools](https://github.com/vsouza/awesome-ios#tools) 🤔

**Comment by dkhamsing** [comment]
Should be Tools

**Comment by vsouza** [comment]
@nadav96 could you move project to `Tools` section, please?

**Comment by dkhamsing** [comment]
Closing for lack of activity

**Pull request closed without merging**
