### PR TITLE
Add SwiftFlyer

### PR DESCRIPTION
**Pull request by rinov**
An API wrapper for bitFlyer that supports all providing API.
## Project URL

https://github.com/rinov/SwiftFlyer
## Category

SDK/Unofficial
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 3 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
5 | Dupe | https://gitter.im/vsouza/awesome-ios 
796 | [502](https://httpstatuses.com/502) | https://github.com/swisspol/XLFacility 
2704 | [503](https://httpstatuses.com/503) | https://boombox.io/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
Hi @rinov. Thanks for contributing.

Maybe is not be crucial for us creating a new category called `Bitcoin` for now. We can try to move this project to another category, do you have any suggestions?

**Comment by lfarah** [comment]
What about ```SDK```?

**Comment by rinov** [comment]
@vsouza Thank you for your reply. Okay, I'd like to change this library's category to `SDK` 🙆

**Pull request merged**
