### PR TITLE
Contacts Wrapper with Objective-C

### PR DESCRIPTION
**Pull request by abdullahselek**
## Project URL
https://github.com/abdullahselek/ContactsWrapper

## Description
An easy to use wrapper for both contacts and contacts group available for iOS 9 and upper.
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
30 | [503](https://httpstatuses.com/503) | https://twitter.com/awesome_ios 
2259 | [301](https://httpstatuses.com/301) | http://www.ioscreator.com/ redirects to<br>https://www.ioscreator.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by abdullahselek** [comment]
Hi,

There are 2 failures on Travis, one of them is related two an old url added without https and the other one is service unavailability on Twitter.

How do we continue?

**Comment by dkhamsing** [comment]
hi, don't worry about the travis issues
thx

**Comment by abdullahselek** [comment]
ok thanks

**Comment by lfarah** [comment]
Hey @abdullahselek, thanks for contributing to AwesomeiOS. I loved your library because we had an issue related to it before.
Does your lib solve #1315?

Also, I'm a little against adding it inside ```/Utility```.
@dkhamsing what do you think?

**Comment by abdullahselek** [comment]
yes, I think it solves #1315

**Comment by dkhamsing** [comment]
@lfarah yeah that is not a great category but it should do for now..

**Comment by dkhamsing** [comment]
@abdullahselek thx

**Comment by abdullahselek** [comment]
Cool thanks @dkhamsing

**Pull request merged**
