### PR TITLE
Fix link issues

### PR DESCRIPTION
**Pull request by serhii-londar**
Line	Status	Link
206	[403](https://httpstatuses.com/403)	https://www.udemy.com/arkit-beginner-to-professional/?couponCode=CREATORS
228	[301](https://httpstatuses.com/301)	https://answers.io/ redirects to
https://get.fabric.io
460	[301](https://httpstatuses.com/301)	https://github.com/hyperoslo/Hue redirects to
https://github.com/zenangst/Hue
613	[404](https://httpstatuses.com/404)	https://github.com/mentalfaculty/impeller
939	[301](https://httpstatuses.com/301)	https://github.com/schibsted/layout redirects to
https://github.com/nicklockwood/layout
1134	[301](https://httpstatuses.com/301)	https://github.com/luiyezheng/JLStickerTextView redirects to
https://github.com/Textcat/JLStickerTextView
1340	[404](https://httpstatuses.com/404)	https://github.com/SvenTiigi/PerfectAPIClient
1516	[301](https://httpstatuses.com/301)	https://github.com/RC7770/MFCard redirects to
https://github.com/MobileFirstInc/MFCard
1630	Error	https://www.packetzoom.com/ 
Connection refused - connect(2) for "www.packetzoom.com" port 443
1661	[301](https://httpstatuses.com/301)	https://github.com/SlackKit/SlackKit redirects to
https://github.com/pvzig/SlackKit
1673	[404](https://httpstatuses.com/404)	https://github.com/SvenTiigi/PerfectSlackAPIClient
1899	[301](https://httpstatuses.com/301)	https://github.com/KrauseFx/trainer redirects to
https://github.com/xcpretty/trainer
2694	[301](https://httpstatuses.com/301)	https://github.com/DenHeadless/DTTableViewManager redirects to
https://github.com/DenTelezhkin/DTTableViewManager
3216	[301](https://httpstatuses.com/301)	https://www.shinobicontrols.com/blog/ios-10-day-by-day-index redirects to
https://www.shinobicontrols.com/blog/ios-10-day-by-day-index/
3259	[301](https://httpstatuses.com/301)	http://principleformac.com redirects to
https://principleformac.com/

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
206 | [403](https://httpstatuses.com/403) | https://www.udemy.com/arkit-beginner-to-professional/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@serhii-londar Thanks ❤️

**Comment by serhii-londar** [comment]
@vsouza Maybe it will be better to add https://www.udemy.com/arkit-beginner-to-professional/ to white list?

**Comment by vsouza** [comment]
@serhii-londar Seems that Udemy check if you're logged. So they return a 403 status. So the best solution (for now) will add this link in our whitelist, as you said.

**Pull request merged**
