### PR TITLE
Added WhatsNewKit to Utility section

### PR DESCRIPTION
**Pull request by SvenTiigi**
## Project URL
https://github.com/SvenTiigi/WhatsNewKit

## Category
Utility

## Description
WhatsNewKit enables iOS developers to showcase their awesome new app features.
 
## Why it should be included to `awesome-ios` (optional)
WhatsNewKit is designed from the ground up to be fully customized to the developers needs.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2181 | [301](https://httpstatuses.com/301) | https://github.com/saeid/GDPersianCalendar redirects to<br>https://github.com/saeid/GDCalendar


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@SvenTiigi Maybe suits better put this project on [Walkthrough / Intro / Tutorial](https://github.com/vsouza/awesome-ios#walkthrough--intro--tutorial) category. What you think?

**Comment by SvenTiigi** [comment]
@vsouza you are totally right 👍 I've moved it to the [Walkthrough / Intro / Tutorial](https://github.com/vsouza/awesome-ios#walkthrough--intro--tutorial) 
 category (https://github.com/SvenTiigi/awesome-ios/commit/9617652fa57bef269a8700a0842841f16bc23855)

**Comment by vsouza** [comment]
@SvenTiigi Thank you.

**Pull request merged**
