### PR TITLE
Add ModelAssistant library to the DataBase Category

### PR DESCRIPTION
**Pull request by ssamadgh**
## Project URL

https://github.com/ssamadgh/ModelAssistant

## Category

DataBase

## Description

Added ModelAssistant library to the DataBase.

## Why it should be included to `awesome-ios` (mandatory)
ModelAssistant is a really useful library that there is no alternative for it. It makes working with tableView and CollectionView really easy and sweet. it's thread safe and has a lot of features.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [X] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1088 | [301](https://httpstatuses.com/301) | https://github.com/rs/SDWebImage redirects to<br>https://github.com/SDWebImage/SDWebImage
1404 | [301](https://httpstatuses.com/301) | https://github.com/Hearst-DD/ObjectMapper redirects to<br>https://github.com/tristanhimmelman/ObjectMapper


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ssamadgh** [comment]
@xwu @mcudich @mikelikespie What's meaning of this fail error?
Found 2 link issues, a project collaborator will take care of these, thanks :)
I do not duplicate any project and my project hasn't any relation to these two issued projects.

**Comment by ssamadgh** [comment]
Hi, What's wrong with this test?
Why does no one care about it?

**Comment by lfarah** [comment]
Hey @ssamadgh, thanks for contributing! Awesome documentation and really well-written tests 👍 

Don't worry about the failing test. These are links that are broken which are not related to the PR

**Comment by ssamadgh** [comment]
Thanks, for merging

**Pull request merged**
