### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by dkhamsing**

### CODE REVIEW

**Comment by victorgama** [comment]
:+1: (Nice project!)

**Comment by vsouza** [comment]
travis enabled.

what u think @lfarah ?

**Comment by dkhamsing** [comment]
@vsouza thx

**Comment by dkhamsing** [comment]
@vsouza gonna white list some items so it works

**Comment by dkhamsing** [comment]
@vsouza :white_check_mark:

**Comment by dkhamsing** [comment]
@vsouza note what is being white listed https://github.com/vsouza/awesome-ios/blob/master/.travis.yml

```
--white-list CONTRIBUTING.md,facebook.com/groups,growthpush.com,mocaplatform.com/features,XCDYouTubeKit
```

- Because the script checks for dupes, anything that is listed twice needs to be white listed, i.e. `XCDYouTubeKit` which is listed under video and apple tv (same with `mocaplatform` and `CONTRIBUTING`)
- The other items are for links that always redirect

**Comment by vsouza** [comment]
:clap:

**Comment by dkhamsing** [comment]
@vsouza hey we can alternatively do something else for allowing duplicates
- use the markdown link / footnote syntax https://daringfireball.net/projects/markdown/syntax#link
- this option adds some links at the bottom (seems ok) and we don't have to specify them in .travis.yml .. I will create another PR and see if that looks better

**Pull request merged**
