### PR TITLE
add asi-http-request to Networking section

### PR DESCRIPTION
**Pull request by miguelarauj1o**

### CODE REVIEW

**Comment by victorgama** [comment]
@miguelarauj1o Can you please rebase your changes? Thanks!

**Comment by miguelarauj1o** [comment]
@victorgama, yep!

**Comment by miguelarauj1o** [comment]
@victorgama, please make sure it is correct what I did.

**Comment by dkhamsing** [comment]
can you rebase again

**Comment by miguelarauj1o** [comment]
rebased

**Comment by miguelarauj1o** [comment]
@dkhamsing, I also deleted one line with trash from git.

**Comment by dkhamsing** [comment]
Thanks

**Pull request merged**
