### PR TITLE
Added PPAssetsActionController to Alerts section

### PR DESCRIPTION
**Pull request by pantuspavel**
Added PPAssetsActionController to Alerts section

## Project URL
[PPAssetsActionController](https://github.com/pantuspavel/PPAssetsActionController)

## Description
Added PPAssetsActionController to Alerts section

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1011 | [301](https://httpstatuses.com/301) | https://www.catapush.com redirects to<br>http://www.catapush.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Hey @pantuspavel, I think it is better under [/Image](https://github.com/vsouza/awesome-ios#image) since  [ImagePickerSheetController](https://github.com/lbrndnr/ImagePickerSheetController) is there already.

**Comment by pantuspavel** [comment]
Hey @lfarah sounds good, I'll update PR shortly. 👍

**Comment by lfarah** [comment]
Oh damn, that was a quick reply! 🚀🚀🚀🚀🚀🚀

**Comment by pantuspavel** [comment]
@lfarah ready for you. 👍

**Pull request merged**
