### PR TITLE
add OTAcceleratorCore to Streaming section

### PR DESCRIPTION
**Pull request by Lucashuang0802**
## Project URL
https://github.com/opentok/accelerator-core-ios

## Description
A painless way to integrate audio/video(screen sharing) to any iOS applications via Tokbox.
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1039 | [301](https://httpstatuses.com/301) | https://tapglue.github.io/ redirects to<br>http://www.tapglue.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @Lucashuang0802, I used OpenTok in the past and I loved it!
Please take a look at the issue above before we can approve your PR

**Comment by Lucashuang0802** [comment]
@lfarah Hey Lucas there(lol), I have updated the `dev` branch. How do you like the new installation guide and the sample codes? Please free feel to give us any comments! Thanks.

**Comment by lfarah** [comment]
Hey @Lucashuang0802, this is Lucas 😂
Everything looks good now. Will merge this PR when you merge ```dev``` into ```master```

**Comment by Lucashuang0802** [comment]
Hey, Lucas. Lucas just merged the code: https://github.com/opentok/accelerator-core-ios LOL

**Comment by lfarah** [comment]
Hey, Lucas. Lucas just merged your PR 
l1ghtsab3r-partyparrot

**Comment by vsouza** [comment]
dog

**Pull request merged**
