### PR TITLE
Add link iosdevnuggets

### PR DESCRIPTION
**Pull request by hboon**

### CODE REVIEW

**Comment by vsouza** [comment]
you forgot to put :large_orange_diamond: in links. :smile:

**Comment by hboon** [comment]
iOS dev nuggets is a mixed of ObjC and Swift though (and Little Bites of Cocoa is almost all Swift it seems). Do we mark with :large_orange_diamond: once it has Swift?

PS: sorry, the branch included both commits.

**Comment by vsouza** [comment]
the goal is to signal that contains Swift code, I think that applies.

**Comment by hboon** [comment]
Ok, done, thanks.

**Pull request merged**
