### PR TITLE
Add MPMoviePlayerController-Subtitles

### PR DESCRIPTION
**Pull request by mhergon**
## Project URL
https://github.com/mhergon/MPMoviePlayerController-Subtitles

## Description
MPMoviePlayerController-Subtitles is a library to display subtitles on iOS. It's built as a Swift extension and it's very easy to integrate.

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
@mhergon can you check why it's conflicting?

**Comment by dkhamsing** [comment]
You have to rebase
Do you need help with this

**Comment by mhergon** [comment]
Yes please, I need help... sorry!

**Comment by dkhamsing** [comment]
If you are doing this using the GitHub website, just close this and open a new pull request by editing the README in https://github.com/vsouza/awesome-ios

**Comment by mhergon** [comment]
Ok, thanks!

**Pull request closed without merging**
