### PR TITLE
Added About Swift

### PR DESCRIPTION
**Pull request by NicolaLancellotti**
## Project URL
https://github.com/NicolaLancellotti-About/About-Swift

## Description
A playground about Swift language.
 
## Why it should be included to `awesome-ios` (optional)
Because it can be useful for learn Swift or for reference.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 3 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
454 | [301](https://httpstatuses.com/301) | http://www.dollarswift.org redirects to<br>https://www.dollarswift.org/
1042 | [301](https://httpstatuses.com/301) | https://moltin.com/ios-ecommerce-sdk/ redirects to<br>https://www.moltin.com/ios-ecommerce-sdk/
2379 | [301](https://httpstatuses.com/301) | https://framerjs.com/ redirects to<br>https://framer.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
@dkhamsing what do you think?

**Comment by dkhamsing** [comment]
Not sure about this

**Comment by naeemshaikh90** [comment]
Should be added in https://github.com/uraimo/Awesome-Swift-Playgrounds

**Comment by dkhamsing** [comment]
@lfarah seems the readme could be improved? kinda vague at this point
i will let you decide

**Comment by NicolaLancellotti** [comment]
Hi everyone,
this is a playground that explains the Swift programming language and the standard library (the last is in development).
About the language there are other playgrounds but I think this is the more complete and I'm improving it.
I think that it can be useful for someone.
About the readme how do you think I can improve it?

**Comment by vsouza** [comment]
@NicolaLancellotti check this: https://github.com/awesome-labs/iOS-readme-template

**Comment by dkhamsing** [comment]
Closing for lack of activity

**Pull request closed without merging**
