### PR TITLE
Added SwiftSortedList

### PR DESCRIPTION
**Pull request by lifeisfoo**
## Project URL
https://github.com/bemindinteractive/SwiftSortedList

## Description
SwiftSortedList is a sorted list implementation in Swift. This is a generic list that is always sorted.
Every time that an element is added, the list is sorted automatically. This is the first public version with basic features. More features (e.g. lazy approach) will be added in the future. CI integration will be added soon.

## Checklist

- [x] Only one project is in the request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 and later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

SwiftSortedList is a sorted list implementation written in Swift. 
It uses the `Comparable` protocol to keep the implementation generic.

### CODE REVIEW

**Comment by lfarah** [comment]
I feel like there must be another category better than */Utilities*.
Some libraries on our Issues are some kind similar:
#739
#672

**Comment by lfarah** [comment]
@dkhamsing any thoughts?

**Comment by lifeisfoo** [comment]
Maybe a "Data structures/Algorithms" category?

**Comment by dkhamsing** [comment]
Yea something like a Data structure category. JSON and XML could go there too as sub section

**Comment by dkhamsing** [comment]
@lfarah is this ok to merge, we can move it later?

**Comment by lfarah** [comment]
@dkhamsing makes sense. Let's merge this and then discuss in #765

**Comment by dkhamsing** [comment]
@lfarah @lifeisfoo thx

**Pull request merged**
