### PR TITLE
Add ARKKit

### PR DESCRIPTION
**Pull request by sleepdefic1t**
#L1252

## Project URL
https://github.com/sleepdefic1t/ARKKit

## Description
iOS/macOS API Framework for interacting with the Ark Cryptocurrency Ecosystem, written purely in Swift 4.0
  
## Why it should be included to `awesome-ios` (optional)
I think it might be useful to others looking at Swift 4.0 or wondering about the world of cryptocurrencies. This Framework also has no external dependencies, so it's very easy to integrate.

## Checklist

- [X] Only one project/change is in this pull request
- [X] Addition in chronological order (bottom of category)
- [X] Supports iOS 9 / tvOS 10 or later
- [X] Supports Swift 3 or later
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 8 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
844 | [502](https://httpstatuses.com/502) | https://github.com/Minitour/AZImagePreview 
918 | [502](https://httpstatuses.com/502) | https://github.com/pokeb/asi-http-request 
1538 | [502](https://httpstatuses.com/502) | https://github.com/Lickability/PinpointKit 
1561 | [404](https://httpstatuses.com/404) | https://github.com/mancunianetz/iCheckbox 
1706 | [502](https://httpstatuses.com/502) | https://github.com/alsedi/RippleEffectView 
2069 | [502](https://httpstatuses.com/502) | https://github.com/yannickl/SnappingStepper 
2569 | [502](https://httpstatuses.com/502) | https://github.com/travisjeffery/ClangFormat-Xcode 
2649 | [301](https://httpstatuses.com/301) | http://www.tutorialspoint.com/ios/ redirects to<br>https://www.tutorialspoint.com/ios/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by sleepdefic1t** [comment]
Any thoughts?

**Comment by miguelarauj1o** [comment]
Hey @sleepdefic1t, don't worry. We'll fix these issues to merge your PR.

**Comment by sleepdefic1t** [comment]
No worries 😄 
Keep up the great work, @miguelarauj1o !

**Pull request merged**
