### PR TITLE
Added EEJSelectMenu to the UI-> Menu category

### PR DESCRIPTION
**Pull request by eejahromi**
## Project URL
https://github.com/eejahromi/EEJSelectMenu

## Description
Added EEJSelectMenu to the UI/Menu category (On the bottom)
(EEJSelectMenu is a Single selection menu with cool animations)

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @eejahromi, cool lib. I really liked the animations!

Thanks for contributing 😄

**Comment by eejahromi** [comment]
Thank you so much @lfarah ! 😀  👍

**Comment by onmyway133** [comment]
@eejahromi why not Swift 😉

**Comment by eejahromi** [comment]
The main code for this lib was actually written a while ago. Hopefully will do a swift rewrite soon. 🙂






On Tue, Jun 21, 2016 at 2:06 AM -0700, "Khoa Pham" <notifications@github.com> wrote:












@eejahromi why not Swift 😉

**Pull request merged**
