### PR TITLE
Add SFSafeSymbols

### PR DESCRIPTION
**Pull request by fredpi**
## Project URL
https://github.com/piknotech/SFSafeSymbols

## Category
Image

## Description
Added SFSafeSymbols to UI section.

## Why it should be included to `awesome-ios` (mandatory)
Makes using SF Symbols in iOS 13+ much easier.

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 5 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
500 | [301](https://httpstatuses.com/301) | https://github.com/arikis/Overdrive redirects to<br>https://github.com/saidsikira/Overdrive
611 | [301](https://httpstatuses.com/301) | https://github.com/alexdrone/Dispatch redirects to<br>https://github.com/alexdrone/DispatchStore
2060 | [301](https://httpstatuses.com/301) | https://github.com/alaphao/LLSpinner redirects to<br>https://github.com/alephao/LLSpinner
3019 | [301](https://httpstatuses.com/301) | https://github.com/tumblr/SwiftCompilationPerformanceReporter redirects to<br>https://github.com/TumblrArchive/SwiftCompilationPerformanceReporter
3266 | [302](https://httpstatuses.com/302) | https://ios-goodies.com redirects to<br>http://ios-goodies.com/#_=_


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@fredpi Maybe this projects suits better in [Image](https://github.com/vsouza/awesome-ios#image) category, what you think?

**Comment by fredpi** [comment]
@vsouza Yeah, that makes sense 👍 I relocated it as per your suggestion

**Comment by vsouza** [comment]
@fredpi Thanks!

**Pull request merged**
