### PR TITLE
Add iOS Cookies Newsletter

### PR DESCRIPTION
**Pull request by LisaDziuba**
## Project URL

[Newsletter](http://us11.campaign-archive1.com/home/?u=cd1f3ed33c6527331d82107ba&id=532dc7fb64)
[Project site](http://www.ioscookies.com/)
## Description

iOS Cookies Newsletter sends the collection of cool libraries, written in Swift.
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 / tvOS 10 or later
- [ ] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
765 | [301](https://httpstatuses.com/301) | https://github.com/zalando-incubator/MapleBacon redirects to<br>https://github.com/JanGorman/MapleBacon
991 | [301](https://httpstatuses.com/301) | http://www.netmera.com redirects to<br>https://www.netmera.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @LisaDziuba, we already had iOS Cookies on our websites, but it's definitely valid to also add their newsletter since I also follow it and the content is so good!

**Comment by lfarah** [comment]
Thanks for contributing 😉

**Comment by LisaDziuba** [comment]
Happy to help 💗

**Pull request merged**
