### PR TITLE
Added WVWalkthroughView

### PR DESCRIPTION
**Pull request by praagyajoshi**
## Project URL
https://github.com/praagyajoshi/WVWalkthroughView

## Description
Added WVWalkthroughView. It's a utility to create walkthrough views which can help with user onboarding by easily drawing their attention to a new feature or area of the app.
 
## Why it should be included to `awesome-ios` (optional)
I needed to point a new feature out in the app to the user and I couldn't find a utility which did exactly what I wanted. So I made this and hopefully, it can help other people out.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] ~~Supports Swift 3~~ n/a
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

---

*edited*

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by naeemshaikh90** [comment]
@dkhamsing @lfarah what you thing guys?

**Comment by victorgama** [comment]
@naeemshaikh90 I'll chime in, if you don't mind 🙌 

@praagyajoshi The repository lacks information on how to install and how to use the library. Would you mind adding these, so people can easily start using your project?

In case you need, [SwiftyOnboard](https://github.com/juanpablofernandez/SwiftyOnboard)'s README is pretty complete. ✨ 

Thank you for contributing! After sorting this out, we will gladly merge your pull request.

**Comment by praagyajoshi** [comment]
Hi guys, @victorgama, @naeemshaikh90, @dkhamsing,

Thanks for the feedback and pointing me towards SwiftyOnboard's README. I've just updated the README for WVWalkthoughView. Check it out and let me know what you think.

Apologies about the delay! 🙌

**Comment by dkhamsing** [comment]
thx

**Pull request merged**
