### PR TITLE
added TJProfileImage

### PR DESCRIPTION
**Pull request by tejas-ardeshna**
TJProfileImage

Project URL

https://github.com/tejas-ardeshna/TJProfileImage

Description

Live rendering of UIImageView properties in Interface Builder.

Why it should be included to awesome-ios (optional)

Checklist
 
- [x] Only one project/change is in this pull request
- [x]  Addition in chronological order (bottom of category)
- [x]  Supports iOS 9 / tvOS 10 or later
- [x]  Supports Swift 3 or later
- [x]  Has a commit from less than 2 years ago
- [x]  Has a clear README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
635 | [301](https://httpstatuses.com/301) | http://www.placekit.io/ redirects to<br>https://business.mapquest.com/products/points-of-interest-data/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @tejas-ardeshna, thanks for contributing!
Please fix the issue above before we can merge your pR

**Comment by tejas-ardeshna** [comment]
I have made changes accordingly.

**Comment by lfarah** [comment]
Hey @tejas-ardeshna, you're still missing an implementation section

**Comment by tejas-ardeshna** [comment]
I have added implementation now please approve PR.

**Comment by dkhamsing** [comment]
@lfarah pls take a look when you are free :)

**Comment by lfarah** [comment]
@tejas-ardeshna Sorry, but it still needs more details. Please provide a coding example, [like this](https://github.com/suzuki-0000/SKPhotoBrowser#usage)

**Comment by tejas-ardeshna** [comment]
@lfarah added please check.

**Comment by lfarah** [comment]
Thanks!

**Pull request merged**
