### PR TITLE
Added WYMaterialButton in Button section.

### PR DESCRIPTION
**Pull request by yuwang17**
Added WYMaterialButton in Button section.

## Project URL
https://github.com/yuwang17/WYMaterialButton

## Description
WYMaterialButton implemented Material Design on iOS and add more dynamic motions, allowing iOS buttons to be more responsive and interactive.

## Checklist

- [x] Only one project is in the request
- [x] `Travis CI` pass
- [x] Supports iOS 7 and later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by victorgama** [comment]
Could you please move the new item to the bottom of the category? Thanks!

**Comment by yuwang17** [comment]
No problem, just updated.

**Comment by victorgama** [comment]
Thank you!

**Comment by yuwang17** [comment]
My pleasure!

**Pull request merged**
