### PR TITLE
Added BiometricAuth Framework to Security

### PR DESCRIPTION
**Pull request by vasilenkoigor**
Added BiometricAuth Framework to Security

## Project URL
https://github.com/vasilenkoigor/BiometricAuth

## Description
Framework for biometric authentication (via TouchID) in your application

## Framework features: 
- [x] Force failure authentication if was added the new fingerprint to the device. 
This feature for security considerations.
- [x] Saving features list that needs authentication via TouchID
 
## Checklist
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please update the Pull Request title to contain the library name</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2257 | [301](https://httpstatuses.com/301) | http://www.ioscreator.com/ redirects to<br>https://www.ioscreator.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by vasilenkoigor** [comment]
Fixed CI issues

**Comment by vasilenkoigor** [comment]
@victorgama Fixed :)

**Comment by victorgama** [comment]
Thank you! 🙌

**Pull request merged**
