### PR TITLE
Added BackgroundVideoiOS.

### PR DESCRIPTION
**Pull request by arasu01**
BackgroundVideoiOS

## Project URL
https://github.com/Guzlan/BackgroundVideoiOS

## Description
A swift and objective-C object that lets you add a background video to iOS views

## Checklist

- [x] Only one project is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [ ] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
@arasu01, your commit has conflicts so you'll have to **rebase**.
Let me know if you have any questions

**Comment by arasu01** [comment]
I will resolve conflicts and update the pull request.

**Comment by lfarah** [comment]
@arasu01 Cool!
Thanks for contributing again and again and again. You're really **awesome** 😄

**Comment by arasu01** [comment]
@lfarah Done.

**Pull request merged**
