### PR TITLE
Add SwiftyZeroMQ

### PR DESCRIPTION
**Pull request by azawawi**
## Project URL
https://github.com/azawawi/SwiftyZeroMQ

## Description
ZeroMQ Swift Bindings for iOS. iOS 10+ at the moment but iOS 8+ support is planned within this weekend hopefully.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @azawawi, thanks for contributing! 😃

I was looking through your README and I'm thinking if it fits better under the [Reactive Programming section](https://github.com/vsouza/awesome-ios#reactive-programming), since we just added [Aftermath](https://github.com/hyperoslo/Aftermath) over there and your libraries seem similar.

What do you think? 🤔

**Comment by azawawi** [comment]
v1.0.12 now support iOS 8 and later :)

@lfarah Thanks for your feedback. My library is a high-level and low-level wrapper around ZeroMQ API so practically it is a messaging and/or networking library but I am not sure about it being under reactive programming category. Please take a look at https://en.wikipedia.org/wiki/ZeroMQ. What do you think? :+1:

**Comment by azawawi** [comment]
Any update on this one?

**Comment by victorgama** [comment]
@lfarah This lib implements a [ZeroMQ](http://zeromq.org/) abstraction and was correctly categorised by @azawawi. This PR LGTM.

@azawawi I'd recommend you adding at least one example in your README, since all of them live in a different repository. Thanks for contributing! 🦄

**Comment by azawawi** [comment]
@victorgama Thanks for the merge and your kind feedback. I am working on an an example iOS demo project that will be available with `pod try SwiftyZeroMQ`.

**Comment by victorgama** [comment]
@azawawi Nice! ZeroMQ is a really useful and powerful tool. I'm pretty sure your lib will be really helpful. :)

**Pull request merged**
