### PR TITLE
add SRGMediaPlayer-iOS

### PR DESCRIPTION
**Pull request by inix**
## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

SRGMediaPlayer-iOS
The SRG Media Player library for iOS provides a simple way to add a universal audio / video player to any iOS application.

### CODE REVIEW

**Comment by lfarah** [comment]
@dkhamsing @vsouza what do we do for this one? 😕

**Comment by dkhamsing** [comment]
not sure

**Comment by lfarah** [comment]
@dkhamsing let's just add it on both and then put the link on Travis' whitelist

**Comment by dkhamsing** [comment]
will update

**Pull request merged**
