### PR TITLE
Add PhotoCropEditor by @sprint84 to Image section

### PR DESCRIPTION
**Pull request by nschucky**
## Project URL

https://github.com/sprint84/PhotoCropEditor
## Description

Add PhotoCropEditor by @sprint84 to Image section
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
We can't add it since it is not compatible with Swift 3

**Comment by lfarah** [comment]
Waiting for [this issue](https://github.com/sprint84/PhotoCropEditor/issues/4#issuecomment-248464217)

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1934 | [301](https://httpstatuses.com/301) | https://github.com/neonichu/Chocolat redirects to<br>https://github.com/pepibumur/Chocolat


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
@nschucky they updated. Can you please rebase this so I can approve?
parrot-1

**Pull request closed without merging**
