### PR TITLE
Add Highlighter

### PR DESCRIPTION
**Pull request by younatics**
Highlight whatever you want!
## Project URL

https://github.com/younatics/Highlighter
## Description

 Highlight whatever you want! Highlighter will magically find UI objects such as UILabel, UITextView, UITexTfield, UIButton in your UITableViewCell or other Class.
## Why it should be included to `awesome-ios` (optional)
Listed trending few weeks ago. 
More than 500 stars
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
@vsouza @dkhamsing @victorgama Do you guys have an idea for a better section?

**Comment by younatics** [comment]
@lfarah  maybe, Reflection or text will be another consideration.

**Comment by victorgama** [comment]
`Text` suits it better, IMHO.

**Comment by lfarah** [comment]
Hey @younatics, can you please move it to /Text?

**Comment by younatics** [comment]
I did it~

**Comment by dkhamsing** [comment]
Thank you!

**Pull request merged**
