### PR TITLE
Add Countly for iOS Analytics

### PR DESCRIPTION
**Pull request by gorkem-cetin**

### CODE REVIEW

**Comment by dkhamsing** [comment]
@gorkem-cetin can you update your url to https://count.ly/ (httpS)

**Comment by gorkem-cetin** [comment]
There's an automatic redirection. Add anyways?

**Comment by gorkem-cetin** [comment]
Not sure if it's done correct way, but here it is :)

**Comment by lfarah** [comment]
Awesome, thanks!

**Pull request merged**
