### PR TITLE
Add SWNetworking

### PR DESCRIPTION
**Pull request by isamankumara**
## Project URL
https://github.com/skywite/SWNetworking

## Description
Using this library developer can save hundred hours. It is open-source and highly multi purpose library. Clean code and sleek features make SWnetworking an ideal choice. Powerful high-level networking abstractions built into Cocoa. It has a modular architecture with well-designed, feature-rich APIs that are a joy to use.

Its core being developed on Objective C,  makes it compatible on the following platforms :
-        iOS,
-        Mac OS X,
-        TV OS

The next question that would pop for any developer is, why build a framework as such when there a many similar ones available. The answer was quite straight forward. 9 out of 10 frameworks out there in the market have the following features:

1. Support all request methods
2. Offline request support
3. Sample Code
4. Cocoa Pod Support
5. SWIFT Compatible
6. Supports Apple UI Kit.
7. Background request support
8. Session manager
9. Reachability manager
10. Secured 
11. Free support offered around the framework
12. The framework will be continuously updated with the new OS drops
13. Community around the framework to support bug fixes
14. Code amendment flexibility
16. 99% Guaranteed on crash management for the framework
17. Block support
18. MIT License

The ones above are not only available on the other frameworks in the market, but is also available on SWNetworking, but here is what makes SWNetworking special:

19 . Offline sync support
20. The frameworks adds in a loading indicator when a request is sent, allows for addition of custom indicators as well
21. A sing line of code to initiate a request, which will approximately save 20 lines of code
22. Block with background request
23. Tag a request (set int value to identify requests)
24. Set priority for offline requests.
25. All the request/response body will generated automatically which would save the developer approximately 50-70 lines of coding

Up coming features
26. Carthage support
27. Automatically data mapping with model class
28 . Framework for native swift

## Checklist

- [x] Only one project is in the request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 and later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

add SWNetworking library into  readme.md

### CODE REVIEW

**Comment by isamankumara** [comment]
added SWNetworking library into readme.md

**Comment by victorgama** [comment]
I think the proposed addition should have a clearer description. 
@dkhamsing, @lfarah, what you think?

**Comment by lfarah** [comment]
@victorgama definitely

**Comment by dkhamsing** [comment]
agreed

@isamankumara please update your pull request with a better description of the library, what it can do, why we should use it

**Comment by isamankumara** [comment]
@dkhamsing Sorry I missed to add description for the pull request. I have added the description to pull request. Please review it. let me know if any other.

**Comment by dkhamsing** [comment]
@isamankumara hi, we meant update your commit entry for `awesome-ios`, it's too vague

**Comment by isamankumara** [comment]
@dkhamsing Can you check now ?

**Comment by victorgama** [comment]
Looks good! Thanks!

**Pull request merged**
