### PR TITLE
Add YOLOkit to Utility section

### PR DESCRIPTION
**Pull request by miguelarauj1o**
related to #365

### CODE REVIEW

**Comment by victorgama** [comment]
Would you mind to move the new item to the bottom of the category?
Thanks!

**Comment by miguelarauj1o** [comment]
I read what you said in #365: "...together with ```underscore.m```".
Sorry. My mistake. I change it in a minute :)

**Comment by victorgama** [comment]
Oh, I'm sorry. My intention was to state that YOLOKit and Underscore.m are akin. (Although I prefer YOLO over Underscore 😎)

**Comment by victorgama** [comment]
Thank you!

**Pull request merged**
