### PR TITLE
Removed XcodeColorSense

### PR DESCRIPTION
**Pull request by lfarah**
Not written in Swift 3

### CODE REVIEW

**Comment by lfarah** [comment]
@onmyway133 do you plan to update it?

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks: )</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
309 | Error | http://oclint.org/ <br> getaddrinfo: Name or service not known
2441 | Error | https://iconresizer.com/ <br> Connection refused - connect(2) for "iconresizer.com" port 443


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by onmyway133** [comment]
@lfarah Yeah, you can remove it because it is Xcode plugin. I now have https://github.com/onmyway133/XcodeColorSense2 which is an Xcode extension

You should write a script for this. There are a lot of libs.

**Comment by dkhamsing** [comment]
thanks!

**Pull request merged**
