### PR TITLE
Add Stanford - Developing iOS 11 Apps with Swift

### LINKED ISSUE #2147: Update Stanford iOS10 to iOS11 course
Hi,

In Getting Started section, Stanford course is iOS10. A new update for the same course is out with iOS11 around Sept 2017. ]Course link] (https://github.com/vsouza/awesome-ios/blob/master/.github/CONTRIBUTING.md).

### PR DESCRIPTION
**Pull request by serhii-londar**
Add Stanford - Developing iOS 11 Apps with Swift. 
Close #2147.

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 5 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
638 | [301](https://httpstatuses.com/301) | https://github.com/SocialObjects-Software/SOMotionDetector redirects to<br>https://github.com/arturdev/SOMotionDetector
944 | [404](https://httpstatuses.com/404) | https://github.com/immrss/Pip 
1284 | [301](https://httpstatuses.com/301) | https://creativesdk.adobe.com/ redirects to<br>https://www.adobe.io/apis/creativecloud/creativesdk.html
1666 | [301](https://httpstatuses.com/301) | https://github.com/ChromieIsDangerous/HamsterUIKit redirects to<br>https://github.com/Howardw3/HamsterUIKit
1911 | [404](https://httpstatuses.com/404) | https://github.com/0x73/SDevCircleButton 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dkhamsing** [comment]
Thx

**Comment by dkhamsing** [comment]
@serhii-londar shield we remove the iOS 10 course ?

**Comment by serhii-londar** [comment]
@dkhamsing it's still available. So I think no.

**Pull request merged**
