### PR TITLE
Moved TOActionSheet to /Alert & Action Sheet

### PR DESCRIPTION
**Pull request by lfarah**
## Project URL

https://github.com/TimOliver/TOActionSheet

## Category

/Alert & Action Sheet

## Description

 A custom-designed reimplementation of the UIActionSheet control for iOS

### CODE REVIEW

**Comment by lfarah** [comment]
Look what library I found... @TimOliver

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2877 | [302](https://httpstatuses.com/302) | http://www.ios-blog.co.uk/ redirects to<br>http://www.ios-blog.co.uk/cgi-sys/suspendedpage.cgi


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by TimOliver** [comment]
Hahah oh criminy. I haven't touched this one in a while. I feel a bit embarrassed. XD But thanks Lucas! :D 

Oh right. I've just completed [another one](https://github.com/TimOliver/TONavigationBar) that might be worth including here. I'll see if I can add a PR for that one. :D

**Comment by lfarah** [comment]
Oh, I saw that one in your Instagram. You should definitely make a PR!
BTW: I gave your lib a try... 😂
screen shot 2018-02-20 at 10 38 25 pm

**Comment by TimOliver** [comment]
Cool thanks! I just filed a PR for it. :D 

ROFL. Goddammit. Good effort. XD

**Pull request merged**
