### PR TITLE
Added Parade to the README

### PR DESCRIPTION
**Pull request by AntonTheDev**
Added Parade to the UI -> ScrollView category 

## Project URL
https://github.com/HelloElephant/Parade

## Category
UI -> Table View / Collection View

## Why it should be included to `awesome-ios` (optional)
It's a paradigm shift approach to scroll-jacking any type of scroll view to attach appearance, and disappearance, animation effects.

## Checklist
- [X] Only one project/change is in this pull request
- [X] Addition in chronological order (bottom of category)
- [X] Supports iOS 9 / tvOS 10 or later
- [X] Supports Swift 4 or later
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1245 | [301](https://httpstatuses.com/301) | https://pusher.com/push-notifications redirects to<br>https://pusher.com/beams
2343 | [301](https://httpstatuses.com/301) | https://github.com/xorshine/KafkaRefresh redirects to<br>https://github.com/OpenFeyn/KafkaRefresh


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@AntonTheDev Please, move the project to the [scrollview](https://github.com/vsouza/awesome-ios#scrollview) section

**Comment by AntonTheDev** [comment]
This actually works with scroll views, table views and collection views. I believe it feel more relevant as part of this section?

I may be wrong, I’ll await your response

**Comment by vsouza** [comment]
I'm going to split the TableView category into more sections, we have a lot of projects in this category.

So, we can merge this for now, and later we can discuss which subcategory we can rearrange.

Thank you.

**Comment by serhii-londar** [comment]
@vsouza I think we can create subcategories with projects for UITableView and UICollectionView and projects which are for booth of them. What do you think?

**Comment by vsouza** [comment]
@serhii-londar let's create an issue to discuss this 💛

**Pull request merged**
