### PR TITLE
Add TableKit

### PR DESCRIPTION
**Pull request by maxsokolov**
## Project URL
https://github.com/maxsokolov/TableKit

## Description
Type-safe declarative table views with Swift.

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Travis is failing for another reason

**Comment by lfarah** [comment]
Thanks for contributing, @maxsokolov. 
Really liked the declarative approach since setting up tableviews is a pain.
@morbix what do you think about it?

**Comment by Morbix** [comment]
@lfarah is nice to see that I am not "alone in the dark" worry about the way we have to work with tables in iOS.  @maxsokolov congratulations. Take a look in my pods too. We could share some thoughts about our libs. =]

**Comment by maxsokolov** [comment]
@lfarah thanks a lot! Yeah, tableviews is a pain, especially when you deal with really complex table views with lots of different cells. Declarative approach helps a lot, because you could build your table block by block. I've tried to provide the most flexible approach that is swifty :) generics play great there.

@Morbix thanks! I'll give it a try)

**Pull request merged**
