### PR TITLE
Added UITextField-Navigation to the TextField & TextView section

### PR DESCRIPTION
**Pull request by T-Pham**
## Project URL

https://github.com/T-Pham/UITextField-Navigation

## Description

Added UITextField-Navigation to the TextField & TextView section.
UITextField-Navigation adds next, previous and done buttons to the keyboard for your UITextFields. It allows you to specify a next text field either on the Interface Builder or programmatically. Then, you can access next and previous text fields of each UITextField easily.

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by T-Pham** [comment]
Not sure why Travis CI failed.

**Comment by dkhamsing** [comment]
it's unrelated to your changes, don't worry about it

**Comment by lfarah** [comment]
Cool lib, @T-Pham! I'll be contributing and adding some stuff there over next week.

Thanks for contributing to Awesome iOS! 😄

**Comment by T-Pham** [comment]
Thanks for merging @lfarah.
Anyone is welcomed to contribute to my lib 👍.

**Pull request merged**
