### PR TITLE
add KKPinCodeTextField

### PR DESCRIPTION
**Pull request by iamirzhan**
## Project URL
https://github.com/kolesa-team/ios_pinCodeTextField

## Category
TextField & TextView

## Description
A customizable verification code textField for phone verification codes, passwords etc.

 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2922 | [403](https://httpstatuses.com/403) | http://www.pixate.com/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
I'm thinking about [/Security](https://github.com/vsouza/awesome-ios#security). What do you think?

@vsouza 
@dkhamsing

**Comment by naeemshaikh90** [comment]
Yes [/Security](https://github.com/vsouza/awesome-ios#security) would be more suitable for this.

**Comment by iamirzhan** [comment]
@lfarah @naeemshaikh90 Thanks! I have moved it to /Security.

**Comment by lfarah** [comment]
Thanks!

**Pull request merged**
