### PR TITLE
CRRulerControl

### PR DESCRIPTION
**Pull request by vladdmitriev**
## Description
Customizable component, created by Cleveroad iOS developers, is aimed at turning a simple ruler into a handy and smart instrument
 
## Why it should be included to `awesome-ios` (optional)
I think this useful component should be included to `awesome-ios`, because with it, it's very comfortable to operate over graphics or any scalable elements. We appreciate your choice.

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please update the Pull Request title to contain the library name</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
987 | [301](https://httpstatuses.com/301) | https://github.com/alvinvarghese/EasyIAPs redirects to<br>https://github.com/aaalveee/EasyIAPs


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by vladdmitriev** [comment]
@danger-awesome-ios I have fixed the error

**Comment by dkhamsing** [comment]
Thx

**Comment by vladdmitriev** [comment]
@danger-awesome-ios Thank you too!

**Pull request merged**
