### PR TITLE
Add FSCalendar+Persian component to calendar section

### PR DESCRIPTION
**Pull request by Husseinhj**
I've added awesome and greatest calendar for iOS and it's full supporting Persian calendar

## Project URL
https://github.com/Husseinhj/FSCalendar

## Category
It added to Calendar category

## Description
Persian version of the FSCalendar. A fully customizable iOS calendar library, compatible with Objective-C and Swift
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hmmm, I don't know about this one. It's just a fork of FSCalendar in Persian.

@dkhamsing 
@vsouza

**Comment by Husseinhj** [comment]
Added to end of calendar category. @lfarah

**Comment by Husseinhj** [comment]
@lfarah They didn't check PR for supporting Persian calendar. I decided to use a fork of FSCalendar for supporting Persian on it.

**Comment by vsouza** [comment]
I'm in trouble here. This project is a fork, and the main project is abandoned. 28 Pull Requests open without an answer. So I will close this PR and remove FSCalendar from our list. 

Feel free to reopen and discuss guys.

**Pull request closed without merging**
