### PR TITLE
Added Moa by @evgenyneu

### PR DESCRIPTION
**Pull request by evgenyneu**
## Project URL

https://github.com/evgenyneu/moa

## Description

Add a suggestion for the Moa library to the README.

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @evgenyneu, thanks for contributing!

There's just a small problem. Please add [e] after 🔶 to show it is an extension:
> Projects in Swift will be marked with 🔶, Swift Extensions will be marked with 🔶[e]

* [Moa](https://github.com/evgenyneu/moa) - An image download extension of the image view for iOS, tvOS and macOS. :large_orange_diamond:[e]

**Comment by lfarah** [comment]
Really liked your library. Doing ``` UImage(data:NSData(url:NSURL(string:"")!)!)``` is a pain in the ass.
You made it waaaay easier!

Thanks again 😄

**Comment by evgenyneu** [comment]
Hi @lfarah, I marked the library as Swift extension.

**Comment by lfarah** [comment]
Hey, can you please rebase? There are some conflicts now...

**Comment by evgenyneu** [comment]
No worries, I do not know how to do the rebase, so I just merged the upstream master to my `moa` branch.

**Comment by lfarah** [comment]
Awesome! Thanks!

**Pull request merged**
