### PR TITLE
Add Rollout.io to Deployment / Distribution

### PR DESCRIPTION
**Pull request by agoldis**
## Project URL
https://rollout.io

## Description
Added text  `[Rollout.io](https://rollout.io/) - SDK to patch, fix bugs, modify and manipulate native apps (Obj-c & Swift) in real-time.` to `Deployment / Distribution` section

## Why it should be included to `awesome-ios` (optional)

This is a cool tool that developers should be aware of. 

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 301 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
435 | [404](https://httpstatuses.com/404) | https://github.com/tarunon/AnyObjectConvertible 
436 | [404](https://httpstatuses.com/404) | https://github.com/ankurp/Dollar 
437 | [404](https://httpstatuses.com/404) | https://github.com/antitypical/Result 
438 | [404](https://httpstatuses.com/404) | https://github.com/EvgenyKarkan/EKAlgorithms 
441 | [404](https://httpstatuses.com/404) | https://github.com/davecom/SwiftGraph 
446 | [404](https://httpstatuses.com/404) | https://github.com/samhann/Every.swift 
447 | [404](https://httpstatuses.com/404) | https://github.com/naoty/Timepiece 
448 | [404](https://httpstatuses.com/404) | https://github.com/malcommac/SwiftDate 
451 | [404](https://httpstatuses.com/404) | https://github.com/harlanhaskins/Punctual.swift 
452 | [404](https://httpstatuses.com/404) | https://github.com/radex/SwiftyTimer 
453 | [404](https://httpstatuses.com/404) | https://github.com/melvitax/DateHelper 
454 | [404](https://httpstatuses.com/404) | https://github.com/remirobert/Tempo 
455 | [404](https://httpstatuses.com/404) | https://github.com/boredzo/iso-8601-date-formatter 
456 | [404](https://httpstatuses.com/404) | https://github.com/thomaspaulmann/EmojiTimeFormatter 
457 | [404](https://httpstatuses.com/404) | https://github.com/lyft/Kronos 
458 | [404](https://httpstatuses.com/404) | https://github.com/instacart/TrueTime.swift 
459 | [404](https://httpstatuses.com/404) | https://github.com/joedaniels29/10Clock 
462 | [404](https://httpstatuses.com/404) | https://github.com/cesarferreira/SwiftEventBus 
463 | [404](https://httpstatuses.com/404) | https://github.com/mxcl/PromiseKit 
465 | [404](https://httpstatuses.com/404) | https://github.com/ReactKit/SwiftTask 
466 | [404](https://httpstatuses.com/404) | https://github.com/vadymmarkov/When 
467 | [404](https://httpstatuses.com/404) | https://github.com/freshOS/then 
468 | [404](https://httpstatuses.com/404) | https://github.com/BoltsFramework/Bolts-Swift 
469 | [404](https://httpstatuses.com/404) | https://github.com/deput/RWPromiseKit 
470 | [404](https://httpstatuses.com/404) | https://github.com/couchdeveloper/FutureLib 
477 | [404](https://httpstatuses.com/404) | https://github.com/nvzqz/FileKit 
478 | [404](https://httpstatuses.com/404) | https://github.com/marmelroy/Zip 
479 | [404](https://httpstatuses.com/404) | https://github.com/marmelroy/FileBrowser 
480 | [404](https://httpstatuses.com/404) | https://github.com/indragiek/Ares 
481 | [404](https://httpstatuses.com/404) | https://github.com/amosavian/FileProvider 
486 | [404](https://httpstatuses.com/404) | https://github.com/brynbellomy/Funky 
488 | [404](https://httpstatuses.com/404) | https://github.com/tptee/Oriole 
489 | [404](https://httpstatuses.com/404) | https://github.com/robrix/Prelude 
494 | [404](https://httpstatuses.com/404) | https://github.com/thoughtbot/Argo 
498 | [404](https://httpstatuses.com/404) | https://github.com/codelynx/ShogibanKit 
501 | [404](https://httpstatuses.com/404) | https://github.com/delba/Tactile 
502 | [404](https://httpstatuses.com/404) | https://github.com/b3ll/SwiftyGestureRecognition 
503 | [404](https://httpstatuses.com/404) | https://github.com/didierbrun/DBPathRecognizer 
504 | [404](https://httpstatuses.com/404) | https://github.com/igormatyushkin014/Sensitive 
507 | [404](https://httpstatuses.com/404) | https://github.com/SwiftKitz/Graphicz 
509 | [404](https://httpstatuses.com/404) | https://github.com/mpw/MPWDrawingContext 
510 | [404](https://httpstatuses.com/404) | https://github.com/davidcairns/DePict 
511 | [404](https://httpstatuses.com/404) | https://github.com/mchoe/SwiftSVG 
513 | [404](https://httpstatuses.com/404) | https://github.com/ibireme/YYAsyncLayer 
514 | [404](https://httpstatuses.com/404) | https://github.com/Nicejinux/NXDrawKit 
520 | [404](https://httpstatuses.com/404) | https://github.com/omergul123/Discovery 
521 | [404](https://httpstatuses.com/404) | https://github.com/LGBluetooth/LGBluetooth 
523 | [404](https://httpstatuses.com/404) | https://github.com/lauraskelton/simple-share 
524 | [404](https://httpstatuses.com/404) | https://github.com/rhummelmose/BluetoothKit 
525 | [404](https://httpstatuses.com/404) | https://github.com/manavgabhawala/CocoaMultipeer 
526 | [404](https://httpstatuses.com/404) | https://github.com/e-sites/Bluetonium 
530 | [404](https://httpstatuses.com/404) | https://github.com/tdginternet/TGCameraViewController 
533 | [404](https://httpstatuses.com/404) | https://github.com/rFlex/SCRecorder 
534 | [404](https://httpstatuses.com/404) | https://github.com/AlexLittlejohn/ALCameraViewController 
535 | [404](https://httpstatuses.com/404) | https://github.com/hyperoslo/ImagePicker 
536 | [404](https://httpstatuses.com/404) | https://github.com/imaginary-cloud/CameraManager 
537 | [404](https://httpstatuses.com/404) | https://github.com/yeahdongcn/RSBarcodes_Swift 
540 | [404](https://httpstatuses.com/404) | https://github.com/hyperoslo/BarcodeScanner 
541 | [404](https://httpstatuses.com/404) | https://github.com/mcmatan/JVTImageFilePicker 
542 | [404](https://httpstatuses.com/404) | https://github.com/HorizonCamera/HorizonSDK-iOS 
544 | [404](https://httpstatuses.com/404) | https://github.com/zhangao0086/DKCamera 
548 | [404](https://httpstatuses.com/404) | https://github.com/ricardopereira/QuickActions 
553 | [404](https://httpstatuses.com/404) | https://github.com/Instrument/Vicinity 
556 | [404](https://httpstatuses.com/404) | https://github.com/izotx/JMCBeaconManager 
562 | [404](https://httpstatuses.com/404) | https://github.com/mamaral/Facade 
565 | [404](https://httpstatuses.com/404) | https://github.com/robb/Cartography 
568 | [404](https://httpstatuses.com/404) | https://github.com/marty-suzuki/MisterFusion 
571 | [404](https://httpstatuses.com/404) | https://github.com/s4cha/Stevia 
572 | [404](https://httpstatuses.com/404) | https://github.com/floriankrueger/Manuscript 
575 | [404](https://httpstatuses.com/404) | https://github.com/evan-liu/FormationLayout 
579 | [404](https://httpstatuses.com/404) | https://github.com/puffinsupply/Restraint 
580 | [404](https://httpstatuses.com/404) | https://github.com/nakiostudio/EasyPeasy 
583 | [404](https://httpstatuses.com/404) | https://github.com/linkedin/LayoutKit 
584 | [404](https://httpstatuses.com/404) | https://github.com/gk-brown/MarkupKit 
585 | [404](https://httpstatuses.com/404) | https://github.com/stevestreza/Relayout 
593 | [404](https://httpstatuses.com/404) | https://github.com/SocialObjects-Software/SOMotionDetector 
598 | [404](https://httpstatuses.com/404) | https://github.com/jensmeder/DarkLightning 
603 | [404](https://httpstatuses.com/404) | https://github.com/Aufree/Hodor 
607 | [404](https://httpstatuses.com/404) | https://github.com/questbeat/Lin 
608 | [404](https://httpstatuses.com/404) | https://github.com/marmelroy/Localize-Swift 
612 | [404](https://httpstatuses.com/404) | https://github.com/metasmile/strsync 
614 | [404](https://httpstatuses.com/404) | https://github.com/viniciusmo/extract-localizable-string-plugin-xcode 
619 | [404](https://httpstatuses.com/404) | https://github.com/CocoaLumberjack/CocoaLumberjack 
620 | [404](https://httpstatuses.com/404) | https://github.com/fpillet/NSLogger 
622 | [404](https://httpstatuses.com/404) | https://github.com/delba/Log 
623 | [404](https://httpstatuses.com/404) | https://github.com/onevcat/Rainbow 
624 | [404](https://httpstatuses.com/404) | https://github.com/krzysztofzablocki/KZLinkedConsole 
630 | [404](https://httpstatuses.com/404) | https://github.com/AFNetworking/AFNetworkActivityLogger 
632 | [404](https://httpstatuses.com/404) | https://github.com/honghaoz/Loggerithm 
634 | [404](https://httpstatuses.com/404) | https://github.com/tadija/AELog 
635 | [404](https://httpstatuses.com/404) | https://github.com/tadija/AEConsole 
636 | [404](https://httpstatuses.com/404) | https://github.com/mattcomi/ReflectedStringConvertible 
639 | [404](https://httpstatuses.com/404) | https://github.com/johnno1962/SwiftTrace 
642 | [404](https://httpstatuses.com/404) | https://github.com/DeveloperLx/LxDBAnything 
645 | [404](https://httpstatuses.com/404) | https://github.com/DrewKiino/Atlantis 
649 | [404](https://httpstatuses.com/404) | https://github.com/collinhundley/Swift-AI 
654 | [404](https://httpstatuses.com/404) | https://github.com/route-me/route-me 
663 | [404](https://httpstatuses.com/404) | https://github.com/madbat/SwiftMath 
664 | [404](https://httpstatuses.com/404) | https://github.com/phimage/Arithmosophi 
666 | [404](https://httpstatuses.com/404) | https://github.com/aleph7/Upsurge 
670 | [404](https://httpstatuses.com/404) | https://github.com/lorentey/BigInt 
677 | [404](https://httpstatuses.com/404) | https://github.com/audiokit/AudioKit 
678 | [404](https://httpstatuses.com/404) | https://github.com/syedhali/EZAudio 
681 | [404](https://httpstatuses.com/404) | https://github.com/evgenyneu/Cephalopod 
684 | [404](https://httpstatuses.com/404) | https://github.com/tbaranes/AudioPlayerSwift 
685 | [404](https://httpstatuses.com/404) | https://github.com/delannoyk/AudioPlayer 
687 | [404](https://httpstatuses.com/404) | https://github.com/benzguo/MusicKit 
692 | [404](https://httpstatuses.com/404) | https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine2 
700 | [404](https://httpstatuses.com/404) | https://github.com/mattt/AnimatedGIFImageSerialization 
701 | [404](https://httpstatuses.com/404) | https://github.com/khaledmtaha/XAnimatedImage 
702 | [404](https://httpstatuses.com/404) | https://github.com/bahlo/SwiftGif 
714 | [404](https://httpstatuses.com/404) | https://github.com/kean/DFImageManager 
716 | [404](https://httpstatuses.com/404) | https://github.com/NYTimes/NYTPhotoViewer 
717 | [404](https://httpstatuses.com/404) | https://github.com/ideaismobile/IDMPhotoBrowser 
720 | [404](https://httpstatuses.com/404) | https://github.com/TimOliver/TOCropViewController 
723 | [404](https://httpstatuses.com/404) | https://github.com/marty-suzuki/SABlurImageView 
724 | [404](https://httpstatuses.com/404) | https://github.com/path/FastImageCache 
728 | [404](https://httpstatuses.com/404) | https://github.com/madebybowtie/FlagKit 
729 | [404](https://httpstatuses.com/404) | https://github.com/ibireme/YYWebImage 
731 | [404](https://httpstatuses.com/404) | https://github.com/josejuanqm/Silo 
733 | [404](https://httpstatuses.com/404) | https://github.com/gauravkatoch007/banana 
736 | [404](https://httpstatuses.com/404) | https://github.com/EddyBorja/EBPhotoPages 
741 | [404](https://httpstatuses.com/404) | https://github.com/kaishin/ImageScout 
742 | [404](https://httpstatuses.com/404) | https://github.com/luiyezheng/JLStickerTextView 
744 | [404](https://httpstatuses.com/404) | https://github.com/abiaad/PASImageView 
746 | [404](https://httpstatuses.com/404) | https://github.com/Inspirato/SwiftPhotoGallery 
748 | [404](https://httpstatuses.com/404) | https://github.com/mwaterfall/MWPhotoBrowser 
751 | [404](https://httpstatuses.com/404) | https://github.com/BradLarson/GPUImage2 
753 | [404](https://httpstatuses.com/404) | https://github.com/dollarshaveclub/ImageButter 
754 | [404](https://httpstatuses.com/404) | https://github.com/suzuki-0000/SKPhotoBrowser 
759 | [404](https://httpstatuses.com/404) | https://github.com/izotx/JMCMarchingAnts 
760 | [404](https://httpstatuses.com/404) | https://github.com/MailOnline/ImageViewer 
761 | [404](https://httpstatuses.com/404) | https://github.com/BeauNouvelle/FaceAware 
762 | [404](https://httpstatuses.com/404) | https://github.com/dkalaitzidis/SwiftyAvatar 
763 | [404](https://httpstatuses.com/404) | https://github.com/FlexMonkey/ShinpuruImage 
764 | [404](https://httpstatuses.com/404) | https://github.com/lbrndnr/ImagePickerSheetController 
766 | [404](https://httpstatuses.com/404) | https://github.com/zvonicek/ImageSlideshow 
777 | [404](https://httpstatuses.com/404) | https://github.com/sgr-ksmt/PDFGenerator 
784 | [404](https://httpstatuses.com/404) | https://github.com/shogo4405/lf.swift 
791 | [404](https://httpstatuses.com/404) | https://github.com/mobileplayer/mobileplayer-ios 
794 | [404](https://httpstatuses.com/404) | https://github.com/gontovnik/Periscope-VideoViewController 
795 | [404](https://httpstatuses.com/404) | https://github.com/immrss/SSVideoPlayer 
799 | [404](https://httpstatuses.com/404) | https://github.com/mhergon/AVPlayerViewController-Subtitles 
804 | [404](https://httpstatuses.com/404) | https://github.com/entotsu/VideoPager 
814 | [404](https://httpstatuses.com/404) | https://github.com/badoo/Chatto 
818 | [404](https://httpstatuses.com/404) | https://github.com/MessageKit/MessageKit-iOS 
819 | [404](https://httpstatuses.com/404) | https://github.com/little2s/NoChat 
827 | [404](https://httpstatuses.com/404) | https://github.com/pokeb/asi-http-request 
833 | [404](https://httpstatuses.com/404) | https://github.com/dingbat/nsrails 
837 | [404](https://httpstatuses.com/404) | https://github.com/ashleymills/Reachability.swift 
838 | [404](https://httpstatuses.com/404) | https://github.com/coderyi/NetworkEye 
843 | [404](https://httpstatuses.com/404) | https://github.com/qiniu/happy-dns-objc 
845 | [404](https://httpstatuses.com/404) | https://github.com/MLSDev/TRON 
847 | [404](https://httpstatuses.com/404) | https://github.com/evermeer/EVURLCache 
848 | [404](https://httpstatuses.com/404) | https://github.com/netguru/ResponseDetective 
850 | [404](https://httpstatuses.com/404) | https://github.com/JustHTTP/Just 
852 | [404](https://httpstatuses.com/404) | https://github.com/Isuru-Nanayakkara/Reach 
854 | [404](https://httpstatuses.com/404) | https://github.com/qiniu/iOS-netdiag 
856 | [404](https://httpstatuses.com/404) | https://github.com/azizuysal/NetKit 
864 | [404](https://httpstatuses.com/404) | https://github.com/3lvis/Networking 
866 | [404](https://httpstatuses.com/404) | https://github.com/thoughtbot/Swish 
870 | [404](https://httpstatuses.com/404) | https://github.com/mavris/MMLanScan 
877 | [404](https://httpstatuses.com/404) | https://github.com/MailCore/mailcore2 
884 | [404](https://httpstatuses.com/404) | https://github.com/naoty/SwiftCSV 
896 | [404](https://httpstatuses.com/404) | https://github.com/delba/JASON 
900 | [404](https://httpstatuses.com/404) | https://github.com/matthewcheok/JSONCodable 
904 | [404](https://httpstatuses.com/404) | https://github.com/bignerdranch/Freddy 
908 | [404](https://httpstatuses.com/404) | https://github.com/ibireme/YYModel 
910 | [404](https://httpstatuses.com/404) | https://github.com/JohnSundell/Wrap 
911 | [404](https://httpstatuses.com/404) | https://github.com/freshOS/Arrow 
914 | [404](https://httpstatuses.com/404) | https://github.com/typelift/Tyro 
915 | [404](https://httpstatuses.com/404) | https://github.com/JohnSundell/Unbox 
916 | [404](https://httpstatuses.com/404) | https://github.com/daltoniam/JSONJoy-Swift 
922 | [404](https://httpstatuses.com/404) | https://github.com/wiggzz/GuardedSwiftyJSON 
946 | [404](https://httpstatuses.com/404) | https://github.com/frozon/passbook 
958 | [404](https://httpstatuses.com/404) | https://github.com/sandorgyulai/InAppFramework 
961 | [404](https://httpstatuses.com/404) | https://github.com/alvinvarghese/EasyIAPs 
964 | [404](https://httpstatuses.com/404) | https://github.com/MaxKramer/SwiftLuhn 
965 | [404](https://httpstatuses.com/404) | https://github.com/MaxKramer/ObjectiveLuhn 
969 | [404](https://httpstatuses.com/404) | https://github.com/nickoneill/PermissionScope 
971 | [404](https://httpstatuses.com/404) | https://github.com/wircho/ICanHas 
972 | [404](https://httpstatuses.com/404) | https://github.com/zakkhoyt/VWWPermissionKit 
973 | [404](https://httpstatuses.com/404) | https://github.com/iosphere/ISHPermissionKit 
987 | [404](https://httpstatuses.com/404) | https://github.com/fastlane/fastlane/tree/master/pem 
988 | [404](https://httpstatuses.com/404) | https://github.com/KnuffApp/Knuff 
1026 | [404](https://httpstatuses.com/404) | https://github.com/RxSwiftCommunity/NSObject-Rx 
1030 | [404](https://httpstatuses.com/404) | https://github.com/Wolox/ReactiveArray 
1032 | [404](https://httpstatuses.com/404) | https://github.com/lsunsi/ReduxSwift 
1038 | [404](https://httpstatuses.com/404) | https://github.com/evermeer/EVReflection 
1039 | [404](https://httpstatuses.com/404) | https://github.com/johnlui/JSONNeverDie 
1059 | [404](https://httpstatuses.com/404) | https://github.com/tumblr/TMTumblrSDK 
1075 | [404](https://httpstatuses.com/404) | https://github.com/AgileBits/onepassword-app-extension 
1078 | [404](https://httpstatuses.com/404) | https://github.com/pinterest/ios-pdk 
1089 | [404](https://httpstatuses.com/404) | https://github.com/pjebs/EasySocial 
1093 | [404](https://httpstatuses.com/404) | https://github.com/timonus/TJDropbox 
1095 | [404](https://httpstatuses.com/404) | https://github.com/onmyway133/github.swift 
1096 | [404](https://httpstatuses.com/404) | https://github.com/CloudRail/cloudrail-si-ios-sdk 
1097 | [404](https://httpstatuses.com/404) | https://github.com/96-problems/medium-sdk-swift 
1099 | [404](https://httpstatuses.com/404) | https://github.com/pvzig/SlackKit 
1105 | [404](https://httpstatuses.com/404) | https://github.com/yankodimitrov/SwiftPasscodeLock 
1111 | [404](https://httpstatuses.com/404) | https://github.com/Gurpartap/AESCrypt-ObjC 
1116 | [404](https://httpstatuses.com/404) | https://github.com/jancassio/SweetHMAC 
1118 | [404](https://httpstatuses.com/404) | https://github.com/SwiftP2P/SwiftSSL 
1119 | [404](https://httpstatuses.com/404) | https://github.com/TakeScoop/SwiftyRSA 
1120 | [404](https://httpstatuses.com/404) | https://github.com/mikaoj/EnigmaKit 
1124 | [404](https://httpstatuses.com/404) | https://github.com/krzyzanowskim/CryptoSwift 
1125 | [404](https://httpstatuses.com/404) | https://github.com/sgl0v/SCrypto 
1130 | [404](https://httpstatuses.com/404) | https://github.com/matthewpalmer/Locksmith 
1150 | [404](https://httpstatuses.com/404) | https://github.com/nestproject/Frank 
1153 | [404](https://httpstatuses.com/404) | https://github.com/johnno1962/Dynamo 
1155 | [404](https://httpstatuses.com/404) | https://github.com/colemancda/NetworkObjects 
1160 | [404](https://httpstatuses.com/404) | https://github.com/jverkoey/nimbus 
1171 | [404](https://httpstatuses.com/404) | https://github.com/marmelroy/Format 
1181 | [404](https://httpstatuses.com/404) | https://github.com/fdzsergio/Reductio 
1182 | [404](https://httpstatuses.com/404) | https://github.com/SwiftStudies/SmarkDown 
1184 | [404](https://httpstatuses.com/404) | https://github.com/szweier/SZMentions 
1187 | [404](https://httpstatuses.com/404) | https://github.com/T-Pham/NoOptionalInterpolation 
1191 | [404](https://httpstatuses.com/404) | https://github.com/mattt/FormatterKit 
1193 | [404](https://httpstatuses.com/404) | https://github.com/gkaimakas/SwiftValidators 
1195 | [404](https://httpstatuses.com/404) | https://github.com/eddiekaiger/SwiftyAttributes 
1205 | [404](https://httpstatuses.com/404) | https://github.com/Skyscanner/Dixie 
1208 | [404](https://httpstatuses.com/404) | https://github.com/railsware/Sleipnir 
1214 | [404](https://httpstatuses.com/404) | https://github.com/recruit-mp/ABKit 
1217 | [404](https://httpstatuses.com/404) | https://github.com/mokemokechicken/CrashMonkey 
1225 | [404](https://httpstatuses.com/404) | https://github.com/johnno1962/Remote 
1236 | [404](https://httpstatuses.com/404) | https://github.com/venmo/DVR 
1237 | [404](https://httpstatuses.com/404) | https://github.com/SwiftKit/Cuckoo 
1238 | [404](https://httpstatuses.com/404) | https://github.com/plu/parallel_ios_tests 
1247 | [404](https://httpstatuses.com/404) | https://github.com/devlucky/Kakapo 
1254 | [404](https://httpstatuses.com/404) | https://github.com/alexdrone/ios-fontawesome 
1288 | [404](https://httpstatuses.com/404) | https://github.com/filipealva/PickerView 
1289 | [404](https://httpstatuses.com/404) | https://github.com/hughbe/phone-number-picker 
1304 | [404](https://httpstatuses.com/404) | https://github.com/kasper-lahti/PageControl 
1308 | [404](https://httpstatuses.com/404) | https://github.com/DanisFabric/RainbowNavigation 
1310 | [404](https://httpstatuses.com/404) | https://github.com/collinhundley/APCustomBlurView 
1311 | [404](https://httpstatuses.com/404) | https://github.com/antiguab/BAFluidView 
1320 | [404](https://httpstatuses.com/404) | https://github.com/hyperoslo/Spots 
1323 | [404](https://httpstatuses.com/404) | https://github.com/500px/greedo-layout-for-ios 
1325 | [404](https://httpstatuses.com/404) | https://github.com/gskbyte/GranadaLayout 
1326 | [404](https://httpstatuses.com/404) | https://github.com/Ramotion/navigation-stack 
1327 | [404](https://httpstatuses.com/404) | https://github.com/andreamazz/UIView-draggable 
1328 | [404](https://httpstatuses.com/404) | https://github.com/marmelroy/PeekPop 
1338 | [404](https://httpstatuses.com/404) | https://github.com/kronik/ScalePicker 
1342 | [404](https://httpstatuses.com/404) | https://github.com/PureSwift/Cacao 
1351 | [404](https://httpstatuses.com/404) | https://github.com/Guzlan/BackgroundVideoiOS 
1359 | [404](https://httpstatuses.com/404) | https://github.com/awesome-labs/LFLoginController 
1364 | [404](https://httpstatuses.com/404) | https://github.com/shashankpali/EZYGradientView 
1367 | [404](https://httpstatuses.com/404) | https://github.com/146BC/StyleKit 
1383 | [404](https://httpstatuses.com/404) | https://github.com/TBXark/TKRubberIndicator 
1395 | [404](https://httpstatuses.com/404) | https://github.com/relatedcode/ProgressHUD 
1406 | [404](https://httpstatuses.com/404) | https://github.com/ykyouhei/KYNavigationProgress 
1408 | [404](https://httpstatuses.com/404) | https://github.com/ninjinkun/NJKWebViewProgress 
1416 | [404](https://httpstatuses.com/404) | https://github.com/dabing1022/DBMetaballLoading 
1423 | [404](https://httpstatuses.com/404) | https://github.com/LeonardoCardoso/AudioIndicatorBars 
1430 | [404](https://httpstatuses.com/404) | https://github.com/codestergit/SweetAlert-iOS 
1446 | [301](https://httpstatuses.com/301) | https://github.com/OEASLAN/OEANotification redirects to<br>https://github.com/OEA/OEANotification
1449 | [404](https://httpstatuses.com/404) | https://github.com/cwRichardKim/RKDropdownAlert 
1453 | [404](https://httpstatuses.com/404) | https://github.com/ytakzk/Hokusai 
1456 | [404](https://httpstatuses.com/404) | https://github.com/morizotter/SwiftyDrop 
1458 | [404](https://httpstatuses.com/404) | https://github.com/okmr-d/DOAlertController 
1461 | [404](https://httpstatuses.com/404) | https://github.com/Codeido/PMAlertController 
1464 | [404](https://httpstatuses.com/404) | https://github.com/cruffenach/CRToast 
1465 | [404](https://httpstatuses.com/404) | https://github.com/devxoul/Toaster 
1474 | [404](https://httpstatuses.com/404) | https://github.com/Minitour/EasyNotificationBadge 
1480 | [404](https://httpstatuses.com/404) | https://github.com/okmr-d/DOFavoriteButton 
1482 | [404](https://httpstatuses.com/404) | https://github.com/0x73/SDevCircleButton 
1487 | [404](https://httpstatuses.com/404) | https://github.com/kciter/KCFloatingActionButton 
1491 | [404](https://httpstatuses.com/404) | https://github.com/suzuki-0000/AnimatablePlayButton 
1496 | [404](https://httpstatuses.com/404) | https://github.com/sprint84/ProgressButton 
1500 | [404](https://httpstatuses.com/404) | https://github.com/yannickl/DynamicButton 
1509 | [404](https://httpstatuses.com/404) | https://github.com/jonathantribouharet/JTCalendar 
1511 | [404](https://httpstatuses.com/404) | https://github.com/unixzii/Daysquare 
1519 | [404](https://httpstatuses.com/404) | https://github.com/Yalantis/YALField 
1527 | [404](https://httpstatuses.com/404) | https://github.com/m1entus/MZFormSheetPresentationController 
1529 | [404](https://httpstatuses.com/404) | https://github.com/manuelescrig/SuggestionsBox 
1538 | [404](https://httpstatuses.com/404) | https://github.com/michaeltyson/TPKeyboardAvoiding 
1577 | [404](https://httpstatuses.com/404) | https://github.com/Azuritul/AZDropdownMenu 
1594 | [404](https://httpstatuses.com/404) | https://github.com/KittenYang/KYGooeyMenu 
1598 | [404](https://httpstatuses.com/404) | https://github.com/edekhayser/FrostedSidebar 
1606 | [404](https://httpstatuses.com/404) | https://github.com/andreamazz/BubbleTransition 
1614 | [404](https://httpstatuses.com/404) | https://github.com/jonathantribouharet/JTMaterialTransition 
1625 | [404](https://httpstatuses.com/404) | https://github.com/ltebean/LTNavigationBar 
1647 | [404](https://httpstatuses.com/404) | https://github.com/cemolcay/PullToRefreshCoreText 
1648 | [404](https://httpstatuses.com/404) | https://github.com/boztalay/BOZPongRefreshControl 
1662 | [404](https://httpstatuses.com/404) | https://github.com/glenyi/FloatRatingView 
1665 | [404](https://httpstatuses.com/404) | https://github.com/marketplacer/Cosmos 
1670 | [404](https://httpstatuses.com/404) | https://github.com/ktanaka117/ScrollingFollowView 
1675 | [404](https://httpstatuses.com/404) | https://github.com/12Rockets/VolumeControl 
1715 | [404](https://httpstatuses.com/404) | https://github.com/alikaragoz/AKASegmentedControl 
1728 | [404](https://httpstatuses.com/404) | https://github.com/lucoceano/Pager 
1744 | [404](https://httpstatuses.com/404) | https://github.com/fastred/ConfigurableTableViewController 
1750 | [404](https://httpstatuses.com/404) | https://github.com/manuelescrig/MEVFloatingButton 
1774 | [404](https://httpstatuses.com/404) | https://github.com/matbeich/StickyCollectionView-Swift 
1777 | [404](https://httpstatuses.com/404) | https://github.com/DavdRoman/Bohr 
1795 | [404](https://httpstatuses.com/404) | https://github.com/jverdi/JVFloatLabeledTextField 
1841 | [404](https://httpstatuses.com/404) | https://github.com/robb/Underscore.m 
1887 | [404](https://httpstatuses.com/404) | https://github.com/skyline75489/SwiftRouter 
1913 | [404](https://httpstatuses.com/404) | https://github.com/Ramotion/paper-onboarding 
1967 | [404](https://httpstatuses.com/404) | https://github.com/metasmile/ai2appiconset 
2285 | [301](https://httpstatuses.com/301) | https://github.com/sxyx2008/awesome-ios-animation redirects to<br>https://github.com/ameizi/awesome-ios-animation
2286 | [301](https://httpstatuses.com/301) | https://github.com/sxyx2008/awesome-ios-chart redirects to<br>https://github.com/ameizi/awesome-ios-chart


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by agoldis** [comment]
@dkhamsing @vsouza Guys, can i do something to promote this PR? Thank you!

**Comment by lfarah** [comment]
@agoldis sorry for the delay... I was on a trip in Germany and I just got back!

I'm a big fan of Rollout.io and I'm glad you guys know AwesomeiOS!

Thanks for contributing 😃 👍

**Comment by agoldis** [comment]
@lfarah 😊  thank you!

**Pull request merged**
