### PR TITLE
Add SnapKit to Layout category

### PR DESCRIPTION
**Pull request by gfpacheco**

### CODE REVIEW

**Comment by dkhamsing** [comment]
Please add it at the end of the section, thanks

**Comment by gfpacheco** [comment]
I added it below Masonry because they're maintained by the same organization and they do pretty much the same. Masonry  is in a bugfix only state and it's team recommends changing to SnapKit, since the new one is written in Swift and is the only one getting new features.

But if you still think it shall be added to the bottom I'll do

**Comment by dkhamsing** [comment]
Thanks for the explanation, the order is chronological also put it at the end will work 😀

**Comment by lfarah** [comment]
I think that in this case, it is better not to put in chronological order

**Comment by gfpacheco** [comment]
There you go =]

**Comment by lfarah** [comment]
@vsouza

**Comment by dkhamsing** [comment]
Merging 
Let me know if you have a different idea

**Pull request merged**
