### PR TITLE
Add iOS Developer interviews

### PR DESCRIPTION
**Pull request by Aymenworks**
A small guide to help those looking to hire a developer for iOS work. ( also designer, but anyway ^^)

### CODE REVIEW

**Comment by victorgama** [comment]
Not sure if creating a brand new category is a good idea. @dkhamsing, @vsouza any thoughts?

**Comment by dkhamsing** [comment]
Maybe have it somewhere in `Good Websites`

**Comment by Aymenworks** [comment]
It's already in `Good Websites`, no ?

**Comment by dkhamsing** [comment]
Right I meant a sub category of `Good Websites`

**Comment by Aymenworks** [comment]
Hoo ok, i'll you choose :)

**Comment by dkhamsing** [comment]
Can you move it to `News, Blogs and Feeds`
Thanks

**Comment by Aymenworks** [comment]
Done!

**Comment by dkhamsing** [comment]
Thx

**Pull request merged**
