### PR TITLE
Added Pickery

### PR DESCRIPTION
**Pull request by Performador**
https://github.com/Performador/Pickery

Pickery is an AWS based photos app. It uploads your pictures to S3 and provides a simple and efficient browsing experience.

 

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
754 | [301](https://httpstatuses.com/301) | https://github.com/zalando/MapleBacon redirects to<br>https://github.com/zalando-incubator/MapleBacon


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by naeemshaikh90** [comment]
Hey @Performador , thanks for contributing to AwesomeiOS! 👍
Great work, but before collaborators can merge your PR, I need you to fix this [issue](https://github.com/Performador/Pickery/issues/2).

**Comment by dkhamsing** [comment]
@naeemshaikh90 @Performador we usually do not add apps to our list, thanks

@lfarah can we put something in contributing guidelines?

**Comment by naeemshaikh90** [comment]
Yes I forgot that😁

**Comment by Performador** [comment]
Wrong project, my bad. Sorry.

**Pull request closed without merging**
