### PR TITLE
add ios net diagnosis library

### PR DESCRIPTION
**Pull request by longbai**

### CODE REVIEW

**Comment by victorgama** [comment]
Not sure about this one, since the Readme is in Chinese.

cc/ @vsouza @dkhamsing @lfarah

**Comment by dkhamsing** [comment]
Good point

@longbai can you add a description/usage in English in the README?

**Comment by lfarah** [comment]
I think we can close it and wait until the README is in english. I opened a issue there

**Comment by dkhamsing** [comment]
Let's give it some time, wait for March 1

**Comment by longbai** [comment]
OK, I will add soon and add usage in readme

**Comment by longbai** [comment]
@victorgama @vsouza @dkhamsing @lfarah ,  I have add english description and some usage.

**Comment by dkhamsing** [comment]
Thx

**Comment by vsouza** [comment]
thanks :+1:

**Pull request merged**
