### PR TITLE
Add OneStore

### PR DESCRIPTION
**Pull request by muukii**
Add OneStore

## Project URL
https://github.com/muukii/OneStore

## Description
A single value proxy for NSUserDefaults, with clean API. 

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
@muukii  99 day streak? How did you get that? I'm struggling to pass my 44 day streak!

Thanks for contributing! 🎉

**Comment by lfarah** [comment]
Please add the lib to the end of the section, after **PredicateEditor**

**Comment by muukii** [comment]
@lfarah 
I'm sorry.
I've fixed it.

**Comment by lfarah** [comment]
@muukii No problem. Thanks! 😄

**Pull request merged**
