### PR TITLE
Add Input Mask library.

### PR DESCRIPTION
**Pull request by taflanidi**
## Project URL
https://github.com/RedMadRobot/input-mask-ios

## Description
Pattern-based user input formatter, parser and validator for iOS.
 
## Why it should be included to `awesome-ios` (optional)
Previously proprietary, the library participated in several mobile banking applications, allowing to add handy text formatting into payment forms; thus, the lib is well-tested and proven worthy.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1 | [503](https://httpstatuses.com/503) | https://raw.githubusercontent.com/vsouza/awesome-ios/master/awesome_logo.png 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by victorgama** [comment]
Hi @taflanidi! Thanks for contributing! 🙌 
Would you mind rebasing your changes so we can get this merged?

**Comment by taflanidi** [comment]
@victorgama corrections applied.

Looks like "one-project-change" detector script was failing because of the full stop I've added, this blocker is kinda silly.

**Comment by vsouza** [comment]
I ran the project again on Travis and passed. We need to look later because danger is doing it.

**Comment by victorgama** [comment]
Silly indeed 😛
Thank you, @taflanidi!

**Pull request merged**
