### PR TITLE
Added OptionalExtensions

### PR DESCRIPTION
**Pull request by RuiAAPeres**

### CODE REVIEW

**Comment by lfarah** [comment]
Please add it to the end of the list

**Comment by RuiAAPeres** [comment]
@lfarah isn't it alphabetically ordered?

**Comment by lfarah** [comment]
@RuiAAPeres No, it is by order of commit

**Comment by dkhamsing** [comment]
Thanks

**Comment by RuiAAPeres** [comment]
Oh, hi @dkhamsing :cake: !

**Comment by dkhamsing** [comment]
:wink:

**Pull request merged**
