### PR TITLE
Added MJRefresh.

### PR DESCRIPTION
**Pull request by arasu01**
## Project URL
https://github.com/CoderMJLee/MJRefresh

## Description
An easy way to use pull-to-refresh.

## Checklist

- [x] Only one project is in the request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 and later
- [ ] Has a commit from less than 2 years ago
- [ ] Has a **clear** README in English

### CODE REVIEW

**Comment by dkhamsing** [comment]
Thank you for contributing to `awesome-ios` :smile:

**Comment by lfarah** [comment]
@dkhamsing, [MJRefresh](https://github.com/CoderMJLee/MJRefresh) can't be added because it doesn't follow all the Awesome iOS rules:
> Has a clear README in English

**Comment by dkhamsing** [comment]
@lfarah dohh my bad
let me open an issue there .. otherwise will remove

thanks!

**Comment by lfarah** [comment]
Can we *un-merge* and wait for a couple weeks until they update their ```README.md```, so we can *re-merge* it?

**Comment by dkhamsing** [comment]
We cannot un-merge, just revert.. so might as well do that in two weeks (was gonna give it a month)

**Comment by dkhamsing** [comment]
Actually this was a squashed commit, so cannot un-merge, just remove separately

**Comment by dkhamsing** [comment]
Anyway, @lfarah I will track this personally and fix in a month's time or another time frame if you prefer

Thanks

**Comment by lfarah** [comment]
Awesome. Let's hope they update their readme

**Pull request merged**
