### PR TITLE
Add Peek to the list of Debugging tools

### PR DESCRIPTION
**Pull request by Vkt0r**
## Project URL
https://github.com/shaps80/Peek

## Category
Debugging

## Description
Add the reference to the library in the `README`
 
## Checklist

- [x] Only one project/change is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 / tvOS 10 or later
- [ ] Supports Swift 4 or later
- [ ] Has a commit from less than 2 years ago
- [ ] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
577 | Dupe | https://github.com/shaps80/Peek 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by serhii-londar** [comment]
@Vkt0r It's already added. Please check [Tools section](https://github.com/vsouza/awesome-ios#tools).

**Comment by Vkt0r** [comment]
@serhii-londar 😢 my bad. It should not be in the Debugging section  ??

**Comment by serhii-londar** [comment]
@Vkt0r It's duplication. We do not add same projects twice please read [CONTRIBUTING.md](https://github.com/vsouza/awesome-ios/blob/master/.github/CONTRIBUTING.md). If you think it should be in 'Debugging' section, please open issue and we will discuss it.

**Comment by Vkt0r** [comment]
👍

**Pull request closed without merging**
