### PR TITLE
Add TableViewDragger by @KyoheiG3 to Table View / Collection View sec…

### PR DESCRIPTION
**Pull request by nschucky**
## Project URL

https://github.com/KyoheiG3/TableViewDragger
## Description

Add TableViewDragger by @KyoheiG3 to Table View / Collection View section
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

…tion

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 3 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
576 | [301](https://httpstatuses.com/301) | https://github.com/SwiftBond/Bond redirects to<br>https://github.com/ReactiveKit/Bond
678 | [301](https://httpstatuses.com/301) | https://github.com/evgenyneu/sound-fader-ios redirects to<br>https://github.com/evgenyneu/Cephalopod
681 | [301](https://httpstatuses.com/301) | https://github.com/recisio/AudioPlayerSwift redirects to<br>https://github.com/tbaranes/AudioPlayerSwift


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
We have to wait because @KyoheiG3 needs to approve [this pull request](https://github.com/KyoheiG3/TableViewDragger/pull/4)

**Comment by KyoheiG3** [comment]
Hi, @lfarah 
[Pull request](https://github.com/KyoheiG3/TableViewDragger/pull/4) was approved and merged.

**Comment by lfarah** [comment]
Thank you @nschucky and @KyoheiG3 😄

**Pull request merged**
