### PR TITLE
Adding CircularRevealKit

### PR DESCRIPTION
**Pull request by ppamorim**
## Project URL
https://github.com/T-Pro/CircularRevealKit

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by naeemshaikh90** [comment]
It should be in [#animation](https://github.com/vsouza/awesome-ios#animation) 🤔
What you thing guys? @dkhamsing @lfarah @victorgama

**Comment by ppamorim** [comment]
@naeemshaikh90 Done.

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1461 | [301](https://httpstatuses.com/301) | https://github.com/andrew8712/DCKit redirects to<br>https://github.com/agordeev/DCKit


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ppamorim** [comment]
@naeemshaikh90 What is this?

**Comment by dkhamsing** [comment]
@ppamorim dont worry about it, someone else will take care of it

**Comment by naeemshaikh90** [comment]
@ppamorim thanks for contributing to `awesome-ios` 🎉🎉🎉

**Comment by ppamorim** [comment]
@naeemshaikh90 It's a pleasure!

**Pull request merged**
