### PR TITLE
Add 360 VR Player

### PR DESCRIPTION
**Pull request by hanton**
[360 VR Player](https://github.com/hanton/HTY360Player) - A open source, ad-free, native and universal 360 degree panorama video player for iOS.

### CODE REVIEW

**Comment by victorgama** [comment]
Nice project! Would you mind moving it to the bottom of the category? Thanks. (:

**Comment by hanton** [comment]
sorry, PR is update :)

**Comment by victorgama** [comment]
Looks like you have a conflict now. Fix it so I can get this merged. :smiley:

**Comment by hanton** [comment]
my bad :( 
please close this PR, i have created a new one in https://github.com/vsouza/awesome-ios/pull/440

**Comment by victorgama** [comment]
No problem! :metal:

**Pull request closed without merging**
