### PR TITLE
Added XMinerClient

### PR DESCRIPTION
**Pull request by Luccifer**
Hello everyone! I have added a monero miner with some pre-maked UI. Feel free to test and play.

## Project URL
https://github.com/Luccifer/XMinerClient

## Category
It can be added to 'Utility'.

## Description
Simple and optimized Monero miner little client. Some UI is already preinstalled, everything can be changed for your own purposes
 
## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
711 | Error | https://github.com/Proxitee/iOS-SDK <br> Net::ReadTimeout
1869 | [301](https://httpstatuses.com/301) | https://github.com/jackymelb/awesome-ios-animation redirects to<br>https://github.com/jzau/awesome-ios-animation


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @Luccifer, thanks for contributing!
Unfortunately, I cannot approve your PR because [Apple is not accepting apps that are mining cryptocurrencies](https://www.theverge.com/2018/3/14/17119474/apple-mac-calendar-app-cryptocurrency-mining)

**Comment by Luccifer** [comment]
@ifarah, is that awesome-ios or awesome Apple rules for iOS? 
Never mind, may be better to open some sort of category for such cases, they can be very helpful for IT research and etc.. but, who cares :)

**Comment by lfarah** [comment]
I agree with you that the code is valuable, but unfortunately, we cannot accept to avoid people getting their apps rejected because they didn't know about these rules.

**Pull request closed without merging**
