### PR TITLE
feat: add SwiftLinter

### PR DESCRIPTION
**Pull request by muyexi**
## Project URL
https://github.com/muyexi/SwiftLinter

## Category
Linter

## Description
Add SwiftLinter to "Linter" category

## Checklist
- [x] Only one project/change is in this pull request
- [] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
206 | [403](https://httpstatuses.com/403) | https://www.udemy.com/arkit-beginner-to-professional/?couponCode=CREATORS 
1498 | [301](https://httpstatuses.com/301) | https://github.com/mobilefirstinc/MFCard redirects to<br>https://github.com/RC7770/MFCard


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@muyexi I'm sorry. I didn't understand how this projects is different to the [swift lint](https://github.com/realm/SwiftLint)

**Comment by muyexi** [comment]
* The script in the pod only checks modified files in your git repo.
* The same SwiftLint config file is shared between projects, it's easier to manage.

**Comment by vsouza** [comment]
Thanks @muyexi .

**Pull request merged**
