### PR TITLE
Add Underscore.m in Utility

### LINKED ISSUE #75: Underscore.m
https://github.com/robb/Underscore.m by @robb looks really cool, not sure where it fits..

### PR DESCRIPTION
**Pull request by dkhamsing**
Created a new section called Utility, close #75

### CODE REVIEW

**Comment by vsouza** [comment]
can you fix the conflicts?

**Comment by dkhamsing** [comment]
Fixed

**Comment by vsouza** [comment]
:smile:

**Comment by dkhamsing** [comment]
:smile:

**Pull request merged**
