### PR TITLE
Add SkrybaMD Documentation generator Tool

### PR DESCRIPTION
**Pull request by robertherdzik**
I have added SkrybaMD Markdown Documentation generator Tool

## Project URL
https://github.com/robertherdzik/SkrybaMD

## Category
Tools

## Description
Append another row to Tool section

## Why it should be included to `awesome-ios` (mandatory)
Tool is very useful once your team and project starts to grow. In easy give you possibility to maintain Documentation and is less error prone than manual changing the numeration of the subject and indentation. You simply have one patter source file and base on this output is generated automatically.
I see that readme of awesome-ios could be done and maintain using this tool.

## Checklist

- [ ] Has 50 GitHub stargazers or more
- [x] Only one project/change is in this pull request
- [x] Isn't an archived project
- [ ] Has more than one contributor
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @robertherdzik, thanks for contributing 🎉 
Unfortunately we cannot merge your PR yet because it doesn't contain unit tests. 
Let us know if you need any help or ideas.

**Comment by robertherdzik** [comment]
@ifeegoo Thank you for response, Im going to add Unit Tests during the weekend ;)

**Comment by robertherdzik** [comment]
@ifeegoo Hi, Unit Tests and Integration already added to the script 🎉

**Comment by lfarah** [comment]
@robertherdzik great! That was fast ⚡️

**Comment by vsouza** [comment]
@robertherdzik Thanks for contributing!

**Pull request merged**
