### PR TITLE
Add SwiftyMenu to Awesome iOS List

### PR DESCRIPTION
**Pull request by KarimEbrahemAbdelaziz**
## Project URL
https://github.com/KarimEbrahemAbdelaziz/SwiftyMenu

## Category
Menu

## Description
Simple and Elegant Drop down menu for iOS 🔥💥

## Why it should be included to `awesome-ios` (mandatory)
Because it's built with a unique feature that doesn't exist in most common DropDown menus in the list.

## Checklist
- [x] Has 50 Github stargazers or more
- [x] Only one project/change is in this pull request
- [x] Isn't an archived project
- [x] Has more than one contributor
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by KarimEbrahemAbdelaziz** [comment]
@lfarah could you take a look here, please ? :)

**Comment by KarimEbrahemAbdelaziz** [comment]
@lfarah Any updates ?

**Comment by KarimEbrahemAbdelaziz** [comment]
@simonmitchell Any updates ?

**Comment by simonmitchell** [comment]
Hi @KarimEbrahemAbdelaziz! I’m not a contributor to this list I’m afraid so can’t help you out myself! I’m sure this will get looked at in due course ☺️

**Comment by vsouza** [comment]
Hey @KarimEbrahemAbdelaziz, thanks for contributing 🎉
Unfortunately, we cannot merge your PR yet because it doesn't contain unit tests.
Feel free to reopen when it's ready.

**Comment by vsouza** [comment]
My bad. I didn't see the tests in your example.

**Comment by vsouza** [comment]
@KarimEbrahemAbdelaziz Merged! Thanks.

**Pull request merged**
