### PR TITLE
Updated Category spaces

### LINKED ISSUE #960: Update spaces
Some categories are missing a space before the *
screen shot 2016-07-19 at 7 58 18 pm

Libraries affected:

- [x] Color
- [x] Command Line
- [x] Concurrency
- [x] Date & Time
- [x] Files
- [x] Games
- [x] Gesture
- [x] Graphics
- [x] Layout
- [x] Permissions
- [x] Reactive Programming
- [x] Encryption

### PR DESCRIPTION
**Pull request by lfarah**

### CODE REVIEW

**Comment by lfarah** [comment]
@dkhamsing @vsouza approve?

**Comment by dkhamsing** [comment]
the output is fine but in markdown, you don't really need a space before `*` after a `#` header

the update should be 

```
* [Chamel...
```

and not

```
 * [Chamel..
```

**Comment by lfarah** [comment]
I did that because 80% of the lib was like this, but I can write a script to fix all the spacing

**Comment by dkhamsing** [comment]
if it is easy, you should set new standard irrespective of what's been done
thanks

**Comment by lfarah** [comment]
@dkhamsing is it good now?

**Comment by dkhamsing** [comment]
Yes I think so

**Comment by dkhamsing** [comment]
Ok to merge

**Pull request merged**
