### PR TITLE
Add SwiftQueue

### PR DESCRIPTION
**Pull request by lucas34**
## Project URL
https://github.com/lucas34/SwiftQueue

## Description
Job Scheduler with Concurrent run, failure/retry, persistence, repeat, delay and more
 
## Why it should be included to `awesome-ios` (optional)
My requirement was quite simple, run tasks with execution constraints. I couldn't find any library for IOS that can do this easily. Existing libs are all lacking of functionalities. So I decided to make my own, inspired by popular job scheduler's library on android like android-priority-jobqueue or android-job.

## Checklist

- [X] Only one project/change is in this pull request
- [X] Addition in chronological order (bottom of category)
- [X] Supports iOS 9 / tvOS 10 or later
- [X] Supports Swift 3 or later
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2369 | [301](https://httpstatuses.com/301) | https://github.com/Swiftification/Dispatch redirects to<br>https://github.com/JARMourato/Dispatch


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @lucas34, thanks for contributing! 👍 

Please fix the issue above before we can merge your PR

**Comment by lucas34** [comment]
I haven't worked with Danger before, but the Ci test failed because of "Danger does not have write access to the PR to set a PR status.". The first time I submitted my PR I got the report properly.

**Comment by dkhamsing** [comment]
He means this issue https://github.com/lucas34/SwiftQueue/issues/3

**Comment by lucas34** [comment]
Well I fix and closed the issue on my repo. If the bot try to update the status on my repo. It won't be able to do it. Should I give permission to awesome-bot on my repo or something ? Or make another PR. I'm a bit clueless about this PR permission issue.

**Comment by lfarah** [comment]
Hey @lucas34, no problem! Thanks again for contributing!

**Pull request merged**
