### PR TITLE
Adds ReviewKit to list of projects!

### PR DESCRIPTION
**Pull request by simonmitchell**
## Project URL

https://github.com/simonmitchell/ReviewKit

## Category

Utility

## Description

ReviewKit allows you to prompt users for review at the ideal time, based on whether they are having a good experience in your app.

## Why it should be included to `awesome-ios` (mandatory)
ReviewKit seems to be the only (If not, at least the most extensive) framework out there that tries to achieve gatekeeping review prompts in this way. It is versatile, customisable, and supports heavy customisation (Is very generic). Whilst it is simple in nature, it is very powerful tool.

## Checklist

- [ ] Has 50 GitHub stargazers or more
- [x] Only one project/change is in this pull request
- [x] Isn't an archived project
- [ ] Has more than one contributor
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by simonmitchell** [comment]
I'm aware this is a controversial topic even amongst the developer community, however I created this library as a lesser of two evils: We have a lot of clients who REQUIRE us to prompt users for reviews, and at least if we make sure they're having a good time, then they're not asked for an annoying review when they are already having a bad experience with the app!

**Comment by lfarah** [comment]
Hey @simonmitchell, thanks for contributing! I loved the score system!

**Comment by simonmitchell** [comment]
Cheers! It's recently gone out in a release of one of my apps, so hoping it'll make a difference to my average review! :D

**Comment by vsouza** [comment]
@simonmitchell Thanks for contributing!

**Comment by simonmitchell** [comment]
@vsouza no worries, thanks for adding it in! :D

**Pull request merged**
