### PR TITLE
Added ESPullToRefresh

### PR DESCRIPTION
**Pull request by sonique6784**
## Project URL
https://github.com/eggswift/pull-to-refresh

## Description
added ESPullToRefresh in the Pull To Refresh section, it a nice pull to refresh that can be customised. it has an option to have nice animation while refreshing.
 
## Why it should be included to `awesome-ios` (optional)
the animation while refreshing are customisable with an easy way

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1145 | [301](https://httpstatuses.com/301) | https://github.com/fhsjaagshs/FHSTwitterEngine redirects to<br>https://github.com/natesymer/FHSTwitterEngine
1223 | [301](https://httpstatuses.com/301) | https://github.com/vapor/Redbird redirects to<br>https://github.com/vapor/redis


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @sonique6784, cool lib 👍 

Thanks for contributing! 😄

**Comment by naeemshaikh90** [comment]
Hey @sonique6784 thanks for contributing to `awesome-ios`😀

**Comment by sonique6784** [comment]
My pleasure  😄 , awesome list!

**Pull request merged**
