### PR TITLE
Add AEXML

### PR DESCRIPTION
**Pull request by tadija**
## Description
I've added XML section right after JSON, and mine XML parser Swift framework - AEXML.

## Checklist:
- [ ] Tests passed.

### CODE REVIEW

**Comment by dkhamsing** [comment]
Hm fyi test not being picked up by `travis ci` at the moment

**Comment by tadija** [comment]
Oops, I missunderstood that one, my unit tests are passing. :)

**Comment by dkhamsing** [comment]
@tadija ah no problem

**Comment by tadija** [comment]
Should I just wait for this "Checking for ability to automatically merge…" to finish and then add a checkbox in previous comment?

**Comment by dkhamsing** [comment]
@tadija nah, you should be ok, a project contributor can look it over

thanks

**Comment by dkhamsing** [comment]
Thank you for contributing to `awesome-ios` :smile:

**Pull request merged**
