### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eugenebokhan**
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by eugenebokhan** [comment]
Added "Awesome ML" open source app for demonstrating different image processing CoreML models on iOS to "Machine Learning" section.

**Comment by lfarah** [comment]
Hello @eugenebokhan, thanks for contributing!
Unfortunately, we cannot accept example apps, but you can submit a PR to @dkhamsing's [open source apps list](https://github.com/dkhamsing/open-source-ios-apps)

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please update the Pull Request title to contain the library name</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by eugenebokhan** [comment]
Hello @lfarah, thanks for reply!

**Pull request closed without merging**
