### PR TITLE
Added Swift-Prompts by @gabrielalva

### PR DESCRIPTION
**Pull request by GabrielAlva**
Hi,
I added the SwiftPrompts repo to the list, Thanks.

Best regards, Gabe

### CODE REVIEW

**Comment by dkhamsing** [comment]
Can u put it at the bottom ? Thx

**Comment by GabrielAlva** [comment]
sure thing!

**Comment by GabrielAlva** [comment]
I just added it at the bottom, Thank you.

**Comment by dkhamsing** [comment]
Thx

**Pull request merged**
