### PR TITLE
Added LLSpinner by @alaphao

### PR DESCRIPTION
**Pull request by alaphao**
## Project URL
https://github.com/alaphao/LLSpinner

## Description
Added LLSpinner to the Activity Indicator section

## Checklist

- [X] Only one project/change is in this pull request
- [X] Addition in chronological order (bottom of category)
- [X] Supports iOS 8 or later
- [X] Supports Swift 3
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @alaphao, thanks for contributing!
It's always good to see other Brazilians in the open source world! 🎉

**Comment by alaphao** [comment]
Thank you @lfarah, I do not have many open source contributions but I'm looking forward to explore more of this world 😄

**Comment by lfarah** [comment]
@alaphao I took 2 years to create my first lib. Before that I was only contributing to other libs...
If you wanna contribute to other libs, let me know because I know some cool projects that need help 😉

**Comment by alaphao** [comment]
@lfarah I do want to contribute to some cool libs, please tell me more about it

**Pull request merged**
