### PR TITLE
MagicPie

### PR DESCRIPTION
**Pull request by AlexandrGraschenkov**
Added link to the most powerful chart library. The best change made ever

## Description

I added to [294 line](https://github.com/vsouza/awesome-ios/pull/1364/commits/631cdada6fccad4c07e5a3e0a821bc33bc0f0a6a#diff-04c6e90faac2675aa89e2176d2eec7d8R294) text: "[MagicPie](https://github.com/AlexandrGraschenkov/MagicPie) - Awesome layer based pie chart. Fantasticly fast and fully customizable. Amazing animations available with MagicPie!!1 :large_orange_diamond: 🎉 ✨✨✨✨✨"
 
## Why it should be included to `awesome-ios` (optional)
It's awesome

## Checklist

- [x] Only one project/change is in this pull request
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English
- [x] Addition in chronological order (bottom of category)

### CODE REVIEW

**Comment by AlexandrGraschenkov** [comment]
You can't comment at this time — your comment cannot be blank.

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 4 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please update the Pull Request title to contain the library name</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
415 | [301](https://httpstatuses.com/301) | http://developer.couchbase.com/mobile/ redirects to<br>https://developer.couchbase.com/mobile/
2417 | [503](https://httpstatuses.com/503) | https://www.amazon.com/Programming-Objective-C-6th-Developers-Library/dp/0321967607 
2420 | [503](https://httpstatuses.com/503) | https://www.amazon.com/Core-Data-iOS-Data-Driven-Applications/dp/0321670426 
2421 | [503](https://httpstatuses.com/503) | https://www.amazon.com/Cocoa-Design-Patterns-Erik-Buck/dp/0321535022 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dkhamsing** [comment]
addition should be at the bottom

**Comment by AlexandrGraschenkov** [comment]
Okay =(

**Comment by lfarah** [comment]
Cool lib, @AlexandrGraschenkov! Thanks for contributing 😄

**Pull request merged**
