### PR TITLE
add SwiftyXML to README.md

### PR DESCRIPTION
**Pull request by chenyunguiMilook**
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
956 | [301](https://httpstatuses.com/301) | https://github.com/chenyunguiMilook/SwiftyXML.git redirects to<br>https://github.com/chenyunguiMilook/SwiftyXML
2082 | [301](https://httpstatuses.com/301) | https://buddybuild.com/ redirects to<br>https://www.buddybuild.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Hey @chenyunguiMilook, thanks for contributing and good job on the library.
I'd ask you to fix the following issue before we can approve.

**Comment by chenyunguiMilook** [comment]
@lfarah now SwiftyXML support cocoapods, carthage, swift package manager~

**Comment by lfarah** [comment]
You're fast! Thanks for contributing 🚀 🚀 🚀 🚀

**Pull request merged**
