### PR TITLE
Added paypal to list of payments

### PR DESCRIPTION
**Pull request by sherifnada**
## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
@dkhamsing @vsouza I never understood our ```/SDK``` Category because of problems like this, since we'll have to open an exception on Travis for every single lib since every SDK will be in another category.
What are your thoughts?

**Comment by dkhamsing** [comment]
I'm ok with the duplication but yeah it's more work for us

**Comment by lfarah** [comment]
@dkhamsing do you think the SDK category is necessary?

**Comment by dkhamsing** [comment]
it serves a purpose
but i'm open

**Comment by vsouza** [comment]
To be honest I do not see a better way to organize the SDK's, if anyone has a suggestion would be great. 😄

**Comment by lfarah** [comment]
@sherifnada we're gonna approve your pull request. Can you please rebase?

**Comment by dkhamsing** [comment]
@sherifnada can you rebase

**Pull request closed without merging**
