### PR TITLE
Add ios-swift-collapsible-table-section by @jeantimex to Table View /…

### PR DESCRIPTION
**Pull request by nschucky**
## Project URL

https://github.com/jeantimex/ios-swift-collapsible-table-section
## Description

Add ios-swift-collapsible-table-section by @jeantimex to Table View / Collection View section
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

… Collection View section

### CODE REVIEW

**Comment by jeantimex** [comment]
Thanks @nschucky for adding my project to this awesome repo! I feel excited and lucky, will continue to make the project even better.

**Comment by lfarah** [comment]
This is not a library. Just an example app

**Comment by jeantimex** [comment]
Hi @nschucky and @lfarah, finally I made a pod for this project, and it's released, see https://github.com/jeantimex/CollapsibleTableSectionViewController. The implementation is different from https://github.com/rob-nash/CollapsableTable, I'd like to let developers use this controller as easy as using a UITableviewController, that is to configure the data and settings from protocol.

I love awesome-ios project and it's the best Swift community in github, so I really want to contribute, please let me know how I can have my project list in your repo, I will try my best, thanks again! 

Also I wrote a medium for the implementation here: https://medium.com/@jeantimex/how-to-implement-collapsible-table-section-in-ios-142e0c6266fd

**Comment by dkhamsing** [comment]
cool, can you open a pull request :)

**Comment by jeantimex** [comment]
Sure, will do! Thanks @dkhamsing!

**Comment by lfarah** [comment]
Oh wow, this is quality! Good job on the lib, @jeantimex! 🙌
You also did something that almost nobody does, which was a Medium post. Really liked that!
Thanks for wanting to wanting to contribute. This lib reached the point we are now thanks to our contributors!

**Comment by jeantimex** [comment]
Thanks @lfarah! Here is the pull request: https://github.com/vsouza/awesome-ios/pull/1886 :)

**Pull request closed without merging**
