### PR TITLE
Added XLActionController library and Action Sheet category

### PR DESCRIPTION
**Pull request by mtnbarreto**
https://github.com/xmartlabs/XLActionController

### CODE REVIEW

**Comment by victorgama** [comment]
Please move the new item to the UI category

**Comment by mtnbarreto** [comment]
done!

**Comment by mtnbarreto** [comment]
done!

**Comment by victorgama** [comment]
Do you mind moving the new item to the bottom of the category, as stated in the [Contribution Guidelines](https://github.com/vsouza/awesome-ios/blob/master/CONTRIBUTING.md)?

**Comment by mtnbarreto** [comment]
sorry! now should be fine!

**Pull request merged**
