### PR TITLE
Added Porcupine

### PR DESCRIPTION
**Pull request by amiranhari**
Including Porcupine, a wake-word detection engine.
## Project URL
https://github.com/Picovoice/Porcupine

## Category
Machine Learning

## Description
On-device wake word detection engine for macOS, iOS, and watchOS, powered by deep learning.
 
## Why it should be included to `awesome-ios` (optional)
There no wake-word detection engines in the list.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
I'm not sure about Machine Learning. What about [/Audio](https://github.com/vsouza/awesome-ios#audio)?

**Comment by amiranhari** [comment]
That makes more sense. Updated the PR.

**Comment by lfarah** [comment]
Thanks for contributing 👍

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
7 | [521](https://httpstatuses.com/521) | https://img.shields.io/github/issues-pr-closed/vsouza/awesome-ios.svg 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Pull request merged**
