### PR TITLE
Add Swimat - XCode plugin to format Swift code

### PR DESCRIPTION
**Pull request by Jintin**
Add Swimat - XCode plugin to format Swift code

### CODE REVIEW

**Comment by victorgama** [comment]
Please move the new item to the end of the section.

**Comment by Jintin** [comment]
Please check again. Thank you.

**Comment by victorgama** [comment]
Nice! Now please rebase so we can merge it, ok?
Thank you!

**Comment by Jintin** [comment]
Sorry, I modify this all on github site.
How can I do now?

**Comment by dkhamsing** [comment]
Hm I will close this because there were changes that conflict with your pull request
Please do it again

**Pull request closed without merging**
