### PR TITLE
Added Gitignore Templates Under Other Xcode Section

### PR DESCRIPTION
**Pull request by aashishtamsya**
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by vsouza** [comment]
@aashishtamsya  please, squash this commits. Or if you feel more confortable you can close this PR and send a new with only  one commit.

Thank you.

**Comment by dkhamsing** [comment]
New entry should go to the bottom

**Comment by aashishtamsya** [comment]
Okay I will do the same next time

**Comment by aashishtamsya** [comment]
Added the one repo per push in chronological order (bottom of category)

**Pull request merged**
