### PR TITLE
Added JQSwiftIcon to UI

### PR DESCRIPTION
**Pull request by josejuanqm**
## Project URL

https://github.com/josejuanqm/JQSwiftIcon
## Description

Added JQSwiftIcon project onto the bottom of the list of UI
## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by dkhamsing** [comment]
this pull request has a conflict, can u fix it

**Comment by josejuanqm** [comment]
Hey, sorry but.. whats the conflict? im sorry for my english in advance 😆

**Comment by victorgama** [comment]
@josejuanqm Your fork is out-of-sync to the upstream repository. You just need to fetch and rebase your changes. 😄  

If you need help through this operation, you can refer to [this](http://stackoverflow.com/a/7244456) StackOverflow answer. 

Thanks for contributing!

**Comment by josejuanqm** [comment]
Thanks for your help! i think its now updated :)

**Comment by dkhamsing** [comment]
If you look at the diff https://github.com/vsouza/awesome-ios/pull/876/files you would see if has changes that we do not want: >>>> HEAD ...

Can you try again and fix the new conflicts as well

You could always open a new pull request from https://github.com/vsouza/awesome-ios

**Comment by josejuanqm** [comment]
Thanks! ill open a new one after fixing the conflicts.

**Pull request closed without merging**
