### PR TITLE
Add How to train your own model for CoreML

### PR DESCRIPTION
**Pull request by kingreza**
## Project URL
tutorial: http://reza.codes/2017-07-29/how-to-train-your-own-dataset-for-coreml/
project: https://github.com/kingreza/SeeFood

## Description
Added How to train your own model for CoreML: An in depth guide on training your own Caffe models using DIGITS and converting them into CoreML for iOS.
 
## Why it should be included to `awesome-ios` (optional)
This guide is currently the most in depth and complete tutorial on how to train and integrate your own CoreML model. It has been featured on  [This week in Swift](https://swiftnews.curated.co/issues/141#start), [Weekly Swift](http://digest.swiftweekly.com/issues/swift-weekly-issue-88-67892) and [Swift LibHunt](https://swift.libhunt.com/newsletter/61) and continues to make the rounds on twitter. This tutorial would be a solid addition to awesome-ios for anyone interested in CoreML who wishes to go beyond using available models. 

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1561 | [404](https://httpstatuses.com/404) | https://github.com/mancunianetz/iCheckbox 
2649 | [301](https://httpstatuses.com/301) | http://www.tutorialspoint.com/ios/ redirects to<br>https://www.tutorialspoint.com/ios/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
@vsouza @dkhamsing what do you guys think?

**Comment by kingreza** [comment]
So what's the verdict gentlemen?

**Comment by dkhamsing** [comment]
Uh no?

**Comment by kingreza** [comment]
@dkhamsing care to elaborate?

**Comment by lfarah** [comment]
I'd say no because it's more like a tutorial blog post instead of a repository or a tool

**Comment by kingreza** [comment]
Hmm, the only reason I submitted was because the about section starts with:

> A curated list of awesome iOS frameworks, libraries, **tutorials**, Xcode plugins, components and much more. 

But if you feel this is not a good fit, I apologize for taking up your time.

**Comment by lfarah** [comment]
Hey @kingreza, you made a good post and I'm gonna definitely read it and try it out once I have time to start learning CoreML stuff.

I totally get why you thought it was a good fit and I'm glad you opened a PR!
In my perspective, the **tutorials** part includes [Getting Started](https://github.com/vsouza/awesome-ios#getting-started) and [Good Websites](https://github.com/vsouza/awesome-ios#good-websites).
Especially /Good Websites/Blogs, we have a list of awesome blogs like @NatashaTheRobot's. We don't have a single post from her blog, but the whole blog

**Comment by kingreza** [comment]
Ah I get it. Thanks for the clarification. 
@dkhamsing you should be more friendly. Try it, it's nice.

**Comment by dkhamsing** [comment]
Sorry!

**Pull request closed without merging**
