### PR TITLE
Added Jasonette - ios.

### PR DESCRIPTION
**Pull request by arasu01**
JASONETTE-iOS

## Project URL
https://github.com/Jasonette/JASONETTE-iOS

## Description
Native App over HTTP. Create your own native iOS app with nothing but JSON.
 
It was useful library and I thought it needs to added to awesome swift. But I don't know where it comes, so I added under reactive programming.

## Checklist

- [x] Only one project/change is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 or later
- [ ] Supports Swift 3
- [ ] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2055 | [404](https://httpstatuses.com/404) | https://github.com/drekka/Alchemic-Swift 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by arasu01** [comment]
I think Alchemic-Swift library is no more exist. Can I remove it?

**Comment by dkhamsing** [comment]
no, thanks

**Comment by lfarah** [comment]
Hey @arasu01, thanks for contributing again!

Don't worry about that because I'll fix by myself! 😉

**Pull request merged**
