### PR TITLE
Add SocialLib

### PR DESCRIPTION
**Pull request by darkcl**

### CODE REVIEW

**Comment by lfarah** [comment]
@dkhamsing ??

**Comment by vsouza** [comment]
seems we need to add `--allow-redirect` flag in awesome-bot

**Comment by dkhamsing** [comment]
I'll fix this issue

**Comment by dkhamsing** [comment]
Looks like Lucas took care of it, keeping those options will let us detect when there is a change (here a project was renamed)

**Comment by lfarah** [comment]
@dkhamsing and why is travis still failing this project?

**Comment by lfarah** [comment]
@dkhamsing why is it still failing?

**Comment by dkhamsing** [comment]
Looks good now after your "Updated WCFastCell link"
Please open a different issue for Travis next time

**Comment by dkhamsing** [comment]
Oh you mean why is this pull request failing? It is because it was failing at the time it was run

**Pull request merged**
