### PR TITLE
Added Colorify to Color section

### PR DESCRIPTION
**Pull request by czater**
## Project URL

https://github.com/czater/Colorify
## Description

Adding Colorify to Colors section.

## Why it should be included to `awesome-ios` (optional)
Colorify is a very fresh color library that includes latest and most trendy colors from 2017. Also is very easy to use because we only need to write Colorify.Red instead of UIColor.OtherLib.Colors.Red or something.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
766 | [301](https://httpstatuses.com/301) | https://github.com/zalando-incubator/MapleBacon redirects to<br>https://github.com/JanGorman/MapleBacon
992 | [301](https://httpstatuses.com/301) | http://www.netmera.com redirects to<br>https://www.netmera.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by czater** [comment]
@vsouza

**Comment by victorgama** [comment]
Hi @czater! Welcome to Awesome iOS!
I believe this project is a Swift Extension, correct?
If so, please include the `[e]` indicator in the new entry, as indicated in our [Contribution Guidelines](https://github.com/vsouza/awesome-ios/blob/master/.github/CONTRIBUTING.md).

Thank you! 🙌

**Comment by czater** [comment]
Hello @victorgama 

Nope, it's color pallete :)

**Comment by victorgama** [comment]
Hi @czater! Sorry for the misclassification! I got carried away by [this line](https://github.com/czater/Colorify/blob/master/Colorify/Classes/Colorify.swift#L149)

**Comment by victorgama** [comment]
Thank you! 🎊

**Pull request merged**
