### PR TITLE
weavy: navigation framework in App Routing

### PR DESCRIPTION
**Pull request by twittemb**
Add Weavy, a navigation framework in App Routing.

## Project URL
https://github.com/twittemb/Weavy

## Category
App Routing

## Description
Weavy is a navigation framework for iOS applications based on a weaving pattern. It is based on a Coordinator concept + Reactive programming with RxSwift.
 
## Why it should be included to `awesome-ios` (optional)
Because there is not much Reactive coordinator frameworks in the list I think :-)

## Checklist

- [X] Only one project/change is in this pull request
- [X] Addition in chronological order (bottom of category)
- [X] Supports iOS 9 / tvOS 10 or later
- [X] Supports Swift 4 or later
- [X] Has a commit from less than 2 years ago
- [X ] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 4 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
638 | [301](https://httpstatuses.com/301) | https://github.com/SocialObjects-Software/SOMotionDetector redirects to<br>https://github.com/arturdev/SOMotionDetector
944 | [404](https://httpstatuses.com/404) | https://github.com/immrss/Pip 
1284 | [301](https://httpstatuses.com/301) | https://creativesdk.adobe.com/ redirects to<br>https://www.adobe.io/apis/creativecloud/creativesdk.html
1911 | [404](https://httpstatuses.com/404) | https://github.com/0x73/SDevCircleButton 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by twittemb** [comment]
Hi @vsouza 
Is there something I can do to improve this PR ? CI seems to be broken. Is it possible to merge this PR anyway ?
Have a good day.
Thx.

**Comment by lfarah** [comment]
Hey @twittemb, don't worry about that. We'll take care of it

**Comment by lfarah** [comment]
Thanks for contributing 👍

**Pull request merged**
