### PR TITLE
Add SYBlinkAnimationKit

### PR DESCRIPTION
**Pull request by shoheiyokoyama**
***SYBlinkAnimationKit*** is a blink effect animation framework for iOS, written in Swift.

### CODE REVIEW

**Comment by lfarah** [comment]
Should be in #Animation

**Comment by shoheiyokoyama** [comment]
OK. fixed.

**Comment by shoheiyokoyama** [comment]
Why Travis CI build failed?

**Comment by victorgama** [comment]
There's a duplicated item, it's not related to this PR. Thank you for the contribution. (:

**Pull request merged**
