### PR TITLE
Added LTHRadioButton

### PR DESCRIPTION
**Pull request by rolandleth**
## Project URL
https://github.com/rolandleth/LTHRadioButton

## Description
A radio button with a pretty fill animation, slightly inspired by Google Material's one.
 
## Why it should be included to `awesome-ios` (optional)
I am not aware of any radio buttons, at least not with pretty animations.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

Not sure if I should've added `by @rolandleth` to the commit, I just saw a lot of them in the history. Let me know if I should remove it, or if anything else is required. 👋

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1839 | [404](https://httpstatuses.com/404) | https://github.com/sag333ar/SRKControls 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Hey @rolandleth, thanks for contributing and good job on your lib, specially with the organized README with gif.
The only thing is that I wanna ask you to move it to the [/Button](https://github.com/vsouza/awesome-ios#button) category

**Comment by rolandleth** [comment]
Hey @Ifarah, thank you!

Hmm, I thought about that, but it's not a button per se, and it has no button-like functionality, it's more of a checkbox. Then I found one of those, and I added it there.

If you think it's better suited there anyway, I'll do it when I get home.

**Comment by lfarah** [comment]
@vsouza @dkhamsing @nschucky what do you guys think?

**Comment by dkhamsing** [comment]
i guess it is fine in `ui`, for now

**Comment by rolandleth** [comment]
Thank you!

**Pull request merged**
