### PR TITLE
Added Dotzu.

### PR DESCRIPTION
**Pull request by arasu01**
## Project URL
https://github.com/remirobert/Dotzu

## Description
iOS app debugger while using the app. Crash report, logs, network.
 
## Checklist

- [x] Only one project/change is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 or later
- [ ] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1038 | [301](https://httpstatuses.com/301) | https://tapglue.github.io/ redirects to<br>http://www.tapglue.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Albin-CR** [comment]
Can any one tell me how to fix this issue?

**Comment by dkhamsing** [comment]
At line 1038, replace the link tapglue.github.io by tapglue.com
Pls do so in a separate pull request

Thx

**Comment by lfarah** [comment]
I'm thinking about [/Code Quality](https://github.com/vsouza/awesome-ios#code-quality)

@arasu01 @dkhamsing @naeemshaikh90 @victorgama what do you guys think?

**Comment by arasu01** [comment]
@lfarah 👍 .

**Comment by lfarah** [comment]
Alright. Everybody approved. @arasu01 please make the change so we can merge this PR

**Comment by arasu01** [comment]
@lfarah done.

**Comment by lfarah** [comment]
Done 22 later hahahah

**Pull request merged**
