### PR TITLE
added GeoEditor

### PR DESCRIPTION
**Pull request by xkomczax**
I added GeoEditor, which is the commercial source code for building an app which can create a vector map from scanned (or in general raster) maps

## Project URL
https://www.maptiler.com/mobile/

## Category
Maps

## Description
I added GeoEditor, which is the commercial source code for building an app which can create a vector map from scanned (or in general raster) maps
 
## Why it should be included to `awesome-ios` (optional)
Because it's awesome (and runs on iOS) ;-)

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 3 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
753 | [301](https://httpstatuses.com/301) | https://github.com/knly/Evergreen redirects to<br>https://github.com/nilsleiffischer/Evergreen
1417 | [301](https://httpstatuses.com/301) | https://github.com/skylab-inc/Edge redirects to<br>https://github.com/skylab-inc/Lightning
1797 | [301](https://httpstatuses.com/301) | https://github.com/storehouse/Advance redirects to<br>https://github.com/timdonnelly/Advance


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
@arasu01 @dkhamsing @vsouza what do you guys think? 🤔

**Comment by dkhamsing** [comment]
Not sure about this one 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vsouza** [comment]
If we can't see the source code, the developers can't see if this project is an awesome project. So, personally, I'm not sure about this project join in the list.

**Comment by dkhamsing** [comment]
Let’s close this, I agree with @vsouza 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lfarah** [comment]
Agree with @vsouza. Thanks guys!

**Pull request closed without merging**
