### PR TITLE
Add Roman

### PR DESCRIPTION
**Pull request by nvzqz**

### CODE REVIEW

**Comment by nvzqz** [comment]
Sorted the Text section alphabetically

**Comment by lfarah** [comment]
Shoudn't have :watch: tag

**Comment by nvzqz** [comment]
The library supports watchOS. Is the tag only for watchOS-specific projects?

**Comment by victorgama** [comment]
@nvzqz Yes, the tag is only for watchOS-specific projects. (:

**Comment by nvzqz** [comment]
Fixed

**Comment by victorgama** [comment]
Thank you!

**Pull request merged**
