### PR TITLE
Added additional iOS Tutorial link

### PR DESCRIPTION
**Pull request by zhiyao92**
## Project URL
www.daddycoding.com

## Category
Link

## Description
The site has a record of posting updates weekly for the past few years it has ever come to existence. The site show case some of the tutorials that range from beginners to advance level. 

## Why it should be included to `awesome-ios` (mandatory)
This will just be an additional resources for those who wish to learn more about iOS as the site itself provides iOS Tutorials.

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 8 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
410 | [301](https://httpstatuses.com/301) | https://github.com/CoreCharts/CoreCharts redirects to<br>https://github.com/cagricolak/CoreCharts
499 | [301](https://httpstatuses.com/301) | https://github.com/arikis/Overdrive redirects to<br>https://github.com/saidsikira/Overdrive
610 | [301](https://httpstatuses.com/301) | https://github.com/alexdrone/Dispatch redirects to<br>https://github.com/alexdrone/DispatchStore
943 | [301](https://httpstatuses.com/301) | https://github.com/kean/Yalta redirects to<br>https://github.com/kean/Align
1289 | [301](https://httpstatuses.com/301) | https://github.com/JustHTTP/Just redirects to<br>https://github.com/dduan/Just
2055 | [301](https://httpstatuses.com/301) | https://github.com/alaphao/LLSpinner redirects to<br>https://github.com/alephao/LLSpinner
3017 | [301](https://httpstatuses.com/301) | https://github.com/tumblr/SwiftCompilationPerformanceReporter redirects to<br>https://github.com/TumblrArchive/SwiftCompilationPerformanceReporter
3250 | [301](https://httpstatuses.com/301) | https://www.daddycoding.com redirects to<br>https://daddycoding.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@zhiyao92 Projects should use `[PACKAGE](LINK) - DESCRIPTION.` format in our README. Can you fix this?

**Comment by zhiyao92** [comment]
Done

**Comment by vsouza** [comment]
@zhiyao92 Thanks for contributing!

**Pull request merged**
