### PR TITLE
Add JRSplitVC

### PR DESCRIPTION
**Pull request by tommypeps**
Add JRSplitVC

### CODE REVIEW

**Comment by lfarah** [comment]
Please fix the conflicts

**Comment by tommypeps** [comment]
@lfarah  ok ?

**Comment by lfarah** [comment]
I still can't merge. You need to fix the conflicts

**Comment by tommypeps** [comment]
Sorry @lfarah only add one line, I don't see problem

**Comment by lfarah** [comment]
@tommypeps the problem is that after you commited, many other apps were added to the list, so you need to change your commit by putting JRSplitVC in the end of the current list, after [StarryStars](https://github.com/vsouza/awesome-ios#websocket)

**Comment by miguelarauj1o** [comment]
@tommypeps, search ```git rebase```

**Comment by tommypeps** [comment]
Thanks @miguelarauj1o

**Comment by dkhamsing** [comment]
Closed with #362

**Pull request closed without merging**
