### PR TITLE
Added Emojica to Text.

### PR DESCRIPTION
**Pull request by xoudini**
## Project URL
https://github.com/xoudini/emojica

## Description
Edited README, added Emojica to the Text section, since the framework handles strings.
 
## Why it should be included to `awesome-ios` (optional)
Well, there isn't another framework/library for iOS that replaces the standard Apple emoji with custom emoji sets.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by victorgama** [comment]
That is a really, really nice readme. 😍

**Comment by xoudini** [comment]
@victorgama Thank you! 😊

**Comment by victorgama** [comment]
Thank you for contributing! 🎉

**Comment by xoudini** [comment]
Cheers! 🎉

**Pull request merged**
