### PR TITLE
Add VTAcknowledgementsViewController

### PR DESCRIPTION
**Pull request by vtourraine**
Add VTAcknowledgementsViewController

## Project URL
https://github.com/vtourraine/VTAcknowledgementsViewController

## Description
Add a new entry for VTAcknowledgementsViewController in the Utility category.
 
## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1807 | [301](https://httpstatuses.com/301) | https://github.com/Lab111/Hedwig redirects to<br>https://github.com/dereklimbus/hedwig
2071 | [301](https://httpstatuses.com/301) | https://github.com/lab111/pivot-slider redirects to<br>https://github.com/dereklimbus/pivot-slider


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @vtourraine, thanks for contributing 👍

**Comment by lfarah** [comment]
Your library is good, but we need to find a better place for it.
[LicensePlist](https://github.com/mono0926/LicensePlist) is in /Tools
[EasyAbout](https://github.com/JARMourato/EasyAbout) is in /Utility
This lib is about to be added in Utility

Should we put under /UI? Is there any better section for it?
@vsouza @dkhamsing @victorgama

**Comment by vtourraine** [comment]
@lfarah Thanks for the feedback!

Finding the right section is tricky. I wouldn’t consider it a “tool”, because it’s really a custom view controller, presenting a specific kind of data. “Utility” feels correct (even if it’s a bit too generic), “UI” makes sense too.

**Comment by lfarah** [comment]
@vtourraine I don't like tools because it's more for programs or scripts like this:
* [PlayAlways](https://github.com/insidegui/PlayAlways) - Create Xcode playgrounds from your menu bar :large_orange_diamond:

**Comment by vtourraine** [comment]
@lfarah Agreed: “I wouldn’t consider it a ‘tool’”

**Comment by dkhamsing** [comment]
Hey I'm merging this

@lfarah can you move LicensePlist to Tools?

**Comment by dkhamsing** [comment]
thanks @vtourraine !

**Comment by dkhamsing** [comment]
merci!!

**Comment by lfarah** [comment]
@dkhamsing LicensePlist is already on /Tools. Did you mean /Utility?

**Comment by dkhamsing** [comment]
Yes. Thx!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
