### PR TITLE
Adding Arrow JSON Parsing Library

### PR DESCRIPTION
**Pull request by s4cha**
## Project URL
https://github.com/s4cha/Arrow

## Description
Elegant JSON Parsing in Swift.
This intends to make using JSON in swift a breeze :)

## Checklist
- [x] Only one project is in the request
- [x] `Travis CI` pass (using Bitrise)
- [x] Supports iOS 7 and later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by victorgama** [comment]
Hey @s4cha! Isn't iOS 7 and later supported? 😁

**Comment by lfarah** [comment]
@victorgama I just checked and it is

**Comment by lfarah** [comment]
@s4cha thanks for contributing and keep up with the awesome libraries 😉

**Comment by victorgama** [comment]
@lfarah 👌

**Pull request merged**
