### PR TITLE
JHProgressHUD changed link

### PR DESCRIPTION
**Pull request by shubh10**
JHProgressHUD developer seems inactive for a long while and he is not merging pull requests, so replaced the link with my fork. Let me know if this is wrong and any other solution is possible.

## Project URL

https://github.com/shubh10/JHProgressHUD

## Description

-Added support for swift3

## Why it should be included to `awesome-ios` (optional)
Old version is already on `awesome-ios` but below checklist is not valid on that anymore and original developer unavailable since September 2016

## Checklist

- [x] Only one project/change is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 4 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
525 | [301](https://httpstatuses.com/301) | https://github.com/omergul123/Discovery redirects to<br>https://github.com/omergul/Discovery
545 | [301](https://httpstatuses.com/301) | https://github.com/omergul123/LLSimpleCamera redirects to<br>https://github.com/omergul/LLSimpleCamera
685 | [404](https://httpstatuses.com/404) | https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ios_examples/ 
2571 | [500](https://httpstatuses.com/500) | http://iphonedevsdk.com/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by shubh10** [comment]
Left `Addition in chronological order (bottom of category)` uncheked since the library is already listed but link is changed. Also about the PCLBlurEffectAlert  (it was in my previous pull request and already on the list)

**Comment by dkhamsing** [comment]
We'll remove https://github.com/harikrishnant1991/JHProgressHUD for now, thx

**Comment by shubh10** [comment]
sure

**Pull request closed without merging**
