### PR TITLE
Update Dangerfile to provide a better error message

### PR DESCRIPTION
**Pull request by KrauseFx**
Yah, :emoji: :and: :so:

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Please only add one library per Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by KrauseFx** [comment]
That's not even one library 😉

**Comment by dkhamsing** [comment]
Thx man

**Comment by KrauseFx** [comment]
🚀

**Pull request merged**
