### PR TITLE
Auto Layout Magic will enable you to design on one screen, and the tool will generate constraints for you!

### PR DESCRIPTION
**Pull request by akordadev**
## Project URL
http://akordadev.github.io/AutoLayoutMagic/

## Description
Auto Layout Magic will enable you to design on one screen, and the tool will generate constraints for you!

## Checklist

- [x] Only one project is in the request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @akordadev, congrats on making your first open source project. The community is really happy on having you as a contributor! 😄 
Unfortunately I can't approve your project right now because *it doesn't have a clear ```README.md```*. I will open an issue on the Github repo explaining how the *README* should be and I'm more than happy on helping you! 😉

**Comment by dkhamsing** [comment]
https://github.com/matiassingers/awesome-readme

**Comment by akordadev** [comment]
I have updated and improved the README.  What do you think?

**Comment by vsouza** [comment]
thanks.

**Pull request merged**
