### PR TITLE
CRPageViewController

### PR DESCRIPTION
**Pull request by vladdmitriev**
## Project URL
https://github.com/Cleveroad/CRPageViewController

## Description
While a standard page view allows you to navigate between pages by using simple gestures, our component goes further
 
## Why it should be included to `awesome-ios` (optional)
I think this useful component should be included to awesome-ios, because it allows defining a page size by setting width and heights manually. Thus, users will be able to control the placement of pages on the screens in the way which is more suitable for them.

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by vladdmitriev** [comment]
@danger-awesome-ios How can I "rebase to get rid of the merge commits in this Pull Request" ?

**Comment by dkhamsing** [comment]
@vladdmitriev please disregard the warning

however, can you update your pull request.. the project should be at the end

thx

**Comment by dkhamsing** [comment]
Thx

**Pull request merged**
