### PR TITLE
Alternative approach to mark this repository as Swift

### PR DESCRIPTION
**Pull request by dmfrancisco**
This is just a cosmetic change, so feel free to close this PR 😄 

This adds a `.gitattributes` file that forces linguist to update the language stats. In this case it ignores `Dangerfile`, making the repository 100% about Swift. With this change it was possible to simplify `helloworld.swift`.

It may take a while for the bar to update after merging, but you can see the updated version in [the fork](https://github.com/listcommunity/awesome-ios). There's more information about linguist including other approaches [here](https://github.com/github/linguist#overrides).

Thank you for maintaining this awesome list 👏

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
5 | Dupe | https://gitter.im/vsouza/awesome-ios 
2685 | [503](https://httpstatuses.com/503) | https://boombox.io/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@dmfrancisco YOU ARE MY HERO ❤️ 

Thanks so much. It's very important to us be marked as 'Swift Repo', because a lot of developers find us by Github search based on language.

Thank you 🎉

**Comment by lfarah** [comment]
That's awesome! Thanks for the fix 👏 👏 👏 👏

**Comment by dkhamsing** [comment]
Well done

**Pull request merged**
