### PR TITLE
Component kit

### PR DESCRIPTION
**Pull request by Epskampie**
Add ComponentKit.

### CODE REVIEW

**Comment by lfarah** [comment]
Can you fix the conflicts please?

**Comment by Epskampie** [comment]
Fixed! Now please merge before it breaks again.

**Comment by dkhamsing** [comment]
Hey, almost there
Can you remove `GoogleMaterialIconFont` from your pull request?

**Comment by Epskampie** [comment]
Check it

**Comment by dkhamsing** [comment]
:tada:

**Pull request merged**
