### PR TITLE
Add Skeleton

### LINKED ISSUE #1839: Skeleton
[Skeleton](https://github.com/gonzalonunez/Skeleton) - An easy way to create sliding CAGradientLayer animations! Works great for creating skeleton screens for loading content. :large_orange_diamond:

### PR DESCRIPTION
**Pull request by aaronjsutton**
Add Skeleton under Animation, close #1839

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 4 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
264 | [502](https://httpstatuses.com/502) | https://github.com/hyperoslo/Cache 
876 | [301](https://httpstatuses.com/301) | https://github.com/terflogag/FacebookImagePicker redirects to<br>https://github.com/floriangbh/FacebookImagePicker
1376 | [301](https://httpstatuses.com/301) | https://github.com/SwiftOnEdge/Edge redirects to<br>https://github.com/skylab-inc/Edge
2405 | [301](https://httpstatuses.com/301) | https://github.com/terflogag/OpenSourceController redirects to<br>https://github.com/floriangbh/OpenSourceController


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by aaronjsutton** [comment]
Activity Indicator may be a better fit.

**Comment by aaronjsutton** [comment]
@dkhamsing Moved to activity indicator

**Comment by dkhamsing** [comment]
Thank you

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
