### PR TITLE
Add MBNetworkMonitor, MBNetworkIndicator to Networking section

### PR DESCRIPTION
**Pull request by emaloney**
Hello,

I've added to new entries in the Networking section for the MBNetworkMonitor and MBNetworkIndicator classes.

Submitting this pull request for your consideration.

Thanks,
E.

### CODE REVIEW

**Comment by vsouza** [comment]
Please correct the description of your links. According to the contribution guide "Keep your descriptions short and simple but descriptive."

"A modern replacement for Apple's Reachability class that uses CoreTelephony to report more information about the user's network connection." - I think that would be enough.

**Comment by emaloney** [comment]
Would this suffice? I've trimmed down the description as you suggested, but used part of it to link to the documentation. I can remove the link altogether if you feel strongly about it.

Thanks!

**Comment by emaloney** [comment]
Thanks, Vinicius.

I've updated the pull request:

https://github.com/vsouza/awesome-ios/pull/62 <https://github.com/vsouza/awesome-ios/pull/62>

**Comment by vsouza** [comment]
thank you!

**Pull request merged**
