### PR TITLE
StarWars.iOS added to Animation

### PR DESCRIPTION
**Pull request by emretekince**

### CODE REVIEW

**Comment by victorgama** [comment]
Please mark the new item with the orange diamond (:large_orange_diamond:), since it is written in Swift.
I would also remove the url. @dkhamsing, @vsouza, any thoughts?

**Comment by dkhamsing** [comment]
Should it go into UI

**Comment by lfarah** [comment]
Please fix the conflicts

**Comment by lfarah** [comment]
@dkhamsing  @victorgama  @vsouza should we commit by ourselves? It's been a month

**Comment by victorgama** [comment]
@lfarah I considered just closing it due to lack of activity. 😅

**Comment by dkhamsing** [comment]
Just close it 😁

**Comment by vsouza** [comment]
Closed.

**Pull request closed without merging**
