### PR TITLE
Add Crossroad

### PR DESCRIPTION
**Pull request by giginet**
## Project URL
https://github.com/giginet/Crossroad

## Category
Routing

## Description
Crossroad is an URL router focused on handling Custom URL Schemes. Using this, you can route multiple URL schemes and fetch arguments and parameters easily.

## Why it should be included to `awesome-ios` (optional)

This library is used with various apps.
## Checklist

- [x] Only one project/change is in this pull request
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 3 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1 | [302](https://httpstatuses.com/302) | https://github.com/vsouza/awesome-ios/blob/master/header.png?raw=true redirects to<br>https://github.com/vsouza/awesome-ios/raw/master/header.png
313 | [301](https://httpstatuses.com/301) | https://github.com/yuzushioh/EthereumKit redirects to<br>https://github.com/D-Technologies/EthereumKit
3026 | [301](https://httpstatuses.com/301) | http://bgr.com/ios-7/ redirects to<br>https://bgr.com/ios-7/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by giginet** [comment]
This change is not useful for my adding library.
However, in this time, I fixed broken CI.

https://github.com/vsouza/awesome-ios/pull/2553/commits/81762c8f788a1fad563d79bd4e9f5193f5a9dbaa

**Comment by vsouza** [comment]
@giginet Thanks for fixing CI.

**Comment by lfarah** [comment]
Thanks for contributing, @giginet 🎉

**Pull request merged**
