### PR TITLE
MalertView lib by Vitor Mesquita

### PR DESCRIPTION
**Pull request by vitormesquita**
## Project URL
https://github.com/vitormesquita/Malert

## Description
I put in Alert Views my recently lib (Malert)
 
## Why it should be included to `awesome-ios` (optional)
I think that awesome-ios is a great channel to be recognized and many people see your github. :)

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
170 | [301](https://httpstatuses.com/301) | http://www.codeproject.com/Articles/88929/Getting-Started-with-iPhone-and-iOS-Development redirects to<br>https://www.codeproject.com/articles/88929/getting-started-with-iphone-and-ios-development
2077 | [302](https://httpstatuses.com/302) | https://swiftlang.ng.bluemix.net/#/repl redirects to<br>https://swiftlang.ng.bluemix.net/verify


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by vitormesquita** [comment]
Hi awesome team, 

I was seeing this issues which your boot generate, and I don't know how I can resolve it.
Can you help me how to resolve?

Thank you

**Comment by dkhamsing** [comment]
@vitormesquita pls disregard the errors, thanks

**Comment by vitormesquita** [comment]
Ok no problem, but how can I do my pull request be accepted?

**Comment by dkhamsing** [comment]
just wait for someone to review
thanks

**Comment by victorgama** [comment]
LGTM. Thank you for contributing, @vitormesquita! 🎉

**Comment by vitormesquita** [comment]
Thank you too 🎉🎉

**Pull request merged**
