### PR TITLE
add Coinpaprika API client

### PR DESCRIPTION
**Pull request by dstranz**
## Project URL
https://github.com/coinpaprika/coinpaprika-api-swift-client

## Category
Blockchain

## Description
Coinpaprika API client with free & frequently updated market data from the world of crypto: coin prices, volumes, market caps, ATHs, return rates and more.

## Why it should be included to `awesome-ios` 
- API is free & unlimited (not paid like in other services)
- API provides data about whole cryptocurrencies world using data downloaded directly from several exchange markets
- library is simple & open source

## Checklist
- [x] Only one project/change is in this pull request
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1212 | [301](https://httpstatuses.com/301) | https://github.com/prynt/PryntTrimmerView redirects to<br>https://github.com/HHK1/PryntTrimmerView
1571 | [301](https://httpstatuses.com/301) | https://github.com/facebook/facebook-ios-sdk redirects to<br>https://github.com/facebook/facebook-objc-sdk


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by arasu01** [comment]
@dstranz : Keep one project/change in this pull request as per checklist.
Also resolve conflicts.

**Comment by dstranz** [comment]
@arasu01 Sorry, I want to fix previous Danger warnings about redirects. Now it only one change without conflicts.

**Comment by vsouza** [comment]
@dstranz Thanks for contributing

**Pull request merged**
