### PR TITLE
Rearranging README

### PR DESCRIPTION
**Pull request by miguelarauj1o**

### CODE REVIEW

**Comment by miguelarauj1o** [comment]
Please, someone check this carefully.

**Comment by vsouza** [comment]
can explain your intentions?

**Comment by olivierlesnicki** [comment]
Looks like its alphabetically sorted...

**Comment by miguelarauj1o** [comment]
@vsouza, the intention is to sort the topics.

**Comment by miguelarauj1o** [comment]
I should have done this for every two topics, not many at once. @vsouza, @dkhamsing, I think this PR should be closed.

**Comment by vsouza** [comment]
that's ok. Thanks anyway.

**Pull request closed without merging**
