### PR TITLE
Add AsyncLocationKit

### PR DESCRIPTION
**Pull request by gre4ixin**
## Project URL

https://github.com/AsyncSwift/AsyncLocationKit

## Category

Location

## Description

Wrapper for Apple CoreLocation framework with new Concurency Model (async/await). 

## Why it should be included to `awesome-ios` (mandatory)

simple and modern way to work with CoreLocation.

## Checklist

- [x] Has 50 GitHub stargazers or more
- [x] Only one project/change is in this pull request
- [x] Isn't an archived project
- [x] Has more than one contributor
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by gre4ixin** [comment]
🚀
@philipturner @arasu01

**Comment by philipturner** [comment]
This seems very legitimate to me. I'd have to do a deeper dive to validate each point specifically, but the activity looks like it deserves recognition:
- Multiple externally submitted issues (which are resolved)
- Multiple pull requests (which are also resolved)
- Active community interest
- Clearly provides something useful to the developer

@vsouza I apologize for being somewhat inconsiderate when asking for my AR project to be recognized around 1 year ago. Even taking my opinion with a grain of salt, it should be obvious this project meets the required criteria.

**Comment by gre4ixin** [comment]
@vsouza 👋🏻

**Comment by philipturner** [comment]
I think he only hops on GitHub once every few months, so he'll probably merge this issue the next time he hops on.

**Comment by vsouza** [comment]
@gre4ixin Sorry for the delay. Thanks for contributing!

**Pull request merged**
