### PR TITLE
Add HGPlaceholders Library

### PR DESCRIPTION
**Pull request by HamzaGhazouani**
## Project URL
https://github.com/HamzaGhazouani/HGPlaceholders

## Description
Nice library to show placeholders and Empty States for any UITableView/UICollectionView in your project
 
## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks: )</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
314 | Error | http://oclint.org/ <br> getaddrinfo: Name or service not known
2453 | Error | https://iconresizer.com/ <br> Connection refused - connect(2) for "iconresizer.com" port 443


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @HamzaGhazouani, thanks for contributing and good job on your lib.
Please add your library at the end of the Table View section please.

**Comment by HamzaGhazouani** [comment]
Hey @lfarah, it's done :) thanks

**Comment by dkhamsing** [comment]
@HamzaGhazouani thank you!

**Comment by HamzaGhazouani** [comment]
you are welcome :)

**Pull request merged**
