### PR TITLE
Added AMSMB2 framework

### PR DESCRIPTION
**Pull request by amosavian**
## Project URL

https://github.com/amosavian/AMSMB2

## Category

Files

## Description

This is small Swift library for iOS, macOS and tvOS which wraps libsmb2 and allows to connect a SMB2/3 share and do file operation.

## Checklist

- [x] Only one project/change is in this pull request
- [ ] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
849 | [301](https://httpstatuses.com/301) | https://github.com/alexdrone/FlexboxLayout redirects to<br>https://github.com/alexdrone/flexboxswfit_deprecated
3144 | [302](https://httpstatuses.com/302) | http://ios-goodies.com redirects to<br>https://ios-goodies.com/#_=_


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@amosavian We cannot merge your PR yet until you write some tests for your lib. Feel free to open another PR once it is ready.

**Comment by amosavian** [comment]
@vsouza I have internal test in my main project and this library have test, They are not placed in framework itself.

**Comment by amosavian** [comment]
Indeed I can't add test to framework due to nature of SMB. You must have a local server to do test. It is a non-trivial job to setup a server in travis.

**Comment by lfarah** [comment]
Thanks for adding tests and thanks for contributing!

**Pull request merged**
