### PR TITLE
Added MiniTabBar

### PR DESCRIPTION
**Pull request by D-32**
## Project URL
https://github.com/D-32/MiniTabBar

## Description
A clean simple alternative to the UITabBar. Only shows the title when being tapped on. Gives the app a way cleaner look :)
 
## Why it should be included to `awesome-ios` (optional)
I think other developers can also profit from it.

## Checklist
- [X] Only one project/change is in this pull request
- [X] Addition in chronological order (bottom of category)
- [X] Supports iOS 9 or later
- [X] Supports Swift 3
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
755 | [301](https://httpstatuses.com/301) | https://github.com/zalando/MapleBacon redirects to<br>https://github.com/zalando-incubator/MapleBacon
2050 | [301](https://httpstatuses.com/301) | https://github.com/omaralbeik/SwifterSwift redirects to<br>https://github.com/SwifterSwift/SwifterSwift


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Hey @D-32, nice lib! I took a look and it looks good for one of my freelance projects!

Please just fix the Issue above so we can merge your PR over here

**Comment by D-32** [comment]
@lfarah I've updated the readme: https://github.com/D-32/MiniTabBar/issues/1

**Comment by D-32** [comment]
Thanks! :)

**Pull request merged**
