### PR TITLE
Remove broken link

### PR DESCRIPTION
**Pull request by Devinsuit**
## Checklist

- [ ] Only one project/change is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 or later
- [ ] Supports Swift 3
- [ ] Has a commit from less than 2 years ago
- [ ] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
944 | [301](https://httpstatuses.com/301) | https://github.com/apollostack/apollo-ios redirects to<br>https://github.com/apollographql/apollo-ios


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by naeemshaikh90** [comment]
I have updated broken link. :) #1434

**Comment by Devinsuit** [comment]
@naeemshaikh90 could you remove LilithProgressHUD? I'll close my PR.

**Comment by naeemshaikh90** [comment]
@Devinsuit ok 👍🏻

**Comment by Devinsuit** [comment]
@naeemshaikh90  thanks!

**Pull request closed without merging**
