### PR TITLE
Delete helloworld.swift

### PR DESCRIPTION
**Pull request by miguelarauj1o**
**helloworld.swift** is useless to awesome-ios

### CODE REVIEW

**Comment by dkhamsing** [comment]
@miguelarauj1o isnt it used to mark the repo as swift project

screen shot 2017-05-26 at 1 43 31 pm

**Comment by miguelarauj1o** [comment]
Really, just to give a swift flavor to appearance?

**Comment by dkhamsing** [comment]
yeah sure.. what do you think

**Comment by miguelarauj1o** [comment]
Other great lists (e.g. [purescript](https://github.com/passy/awesome-purescript), [ruby](https://github.com/markets/awesome-ruby), [javascript](https://github.com/sorrycc/awesome-javascript) and [java](https://github.com/akullpp/awesome-java)) don´t do this. But, you guys decide.

**Comment by victorgama** [comment]
Actually, we used this to give exposure to the project, since it is listed on the _trending_ lists and such.
Currently, we are in the 8th position of the [Trending Swift Repositories this month](https://github.com/trending/swift?since=monthly).

I'd say @vsouza should exclusively call the shots on this one.

**Comment by miguelarauj1o** [comment]
Nice, great move. I should have thought.

**Comment by vsouza** [comment]
@miguelarauj1o unfortunately we have to keep this file here. I've been thinking for a while about a new solution to mark this repo as a Swift project, to keep our project relevant on Github search. But for now, this is the solution.

I have some ideas to change this file, in a few weeks I'll attempt to implement this in awesome-ios and send a pull request.

**Pull request closed without merging**
