### PR TITLE
Added LocalizationKit to internationalize your app

### PR DESCRIPTION
**Pull request by willpowell8**
LocalizationKit within the Localization section to localize your app translations and texts.

## Project URL
https://github.com/willpowell8/LocalizationKit_iOS
https://www.localizationkit.com
https://www.localizationkit.com/app

## Description
LocalizationKit is a way of easily setting up an existing app or starting a new app to support mulitiple languages which you can manage and control remotely. It takes less than 5 minutes to add. It has storyboard and xib support with interface builder and leverages http and websockets to deliver updates and changes.
 
## Why it should be included to `awesome-ios` (optional)
As a developer I am fed up with people asking "Can you just change this text to say ...?" or that "label is not quite right" and I wanted to build a mechanism where people can change the texts without requiring redevelopment. Hence I created the LocalizationKit

## Checklist
- [X] Only one project/change is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [X] Supports iOS 9 or later
- [X] Supports Swift 3
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @willpowell8, awesome library 👍 

I just need you to add it in the end of the category

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by willpowell8** [comment]
I have moved it to the last row in the section. Is that now okay?

**Comment by dkhamsing** [comment]
Thx

**Pull request merged**
