### PR TITLE
Updated SwiftyTask lib

### PR DESCRIPTION
**Pull request by Albinzr**
Changed github link to new for SwiftyTask

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 3 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1172 | [301](https://httpstatuses.com/301) | https://github.com/MailOnline/Reactor redirects to<br>https://github.com/RuiAAPeres/Reactor
2045 | [404](https://httpstatuses.com/404) | https://github.com/dereklimbus/hedwig 
2369 | [404](https://httpstatuses.com/404) | https://github.com/dereklimbus/pivot-slider 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Albinzr** [comment]
Is there any specification on the error?

**Comment by Albinzr** [comment]
I feel like there are broken links?

**Comment by vsouza** [comment]
@Albinzr Please move the project to the end of the category. The broken links I'll fix them.

**Pull request closed without merging**
