### PR TITLE
Add Inapptics in Analytics category

### PR DESCRIPTION
**Pull request by ArVan**
## Project URL

[https://inapptics.com](https://inapptics.com)

## Description

`Inapptics` helps analyze and visualize user behavior in mobile apps. Provides visual user journeys, heatmaps and crash replays.
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by dkhamsing** [comment]
What do you think @arasu01 @serhii-londar @aaronjsutton

**Comment by aaronjsutton** [comment]
Looks good to me, and fits well in it’s category.

**Comment by serhii-londar** [comment]
Good for me.

**Comment by dkhamsing** [comment]
Thx team!

**Pull request merged**
