### PR TITLE
Added MFCard

### PR DESCRIPTION
**Pull request by arpandesai**
MFCard is minimal credit card UI for payments integration.

Added MFCard repo. 

## Project URL
http://github.com/mobilefirstinc/mfcard 

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by arpandesai** [comment]
MFCard is an awesome looking Credit Card input & validation control

**Comment by arpandesai** [comment]
@lfarah here you go !

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2438 | [503](https://httpstatuses.com/503) | https://www.amazon.com/Programming-Objective-C-6th-Developers-Library/dp/0321967607 
2442 | [503](https://httpstatuses.com/503) | https://www.amazon.com/Cocoa-Design-Patterns-Erik-Buck/dp/0321535022 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Thanks for contributing 😃

**Comment by arpandesai** [comment]
Thank you ! Honored to be part of the list. More energy to you and your team. 

How's the newsletter working ? 

-- Arpan Desai 
+91 999 875-5114

**Comment by lfarah** [comment]
Hey @arpandesai, thanks!

I'll be sending AwesomeiOS.Weekly [4] by tomorrow. It took a looooooooong time because my Mac broke for 1 month and I didn't have backups of my library quality bot... Now I got my Mac back and almost finishing the 4th email! 👍

**Comment by arpandesai** [comment]
Great ! 

— Arpan Desai

**Pull request merged**
