### PR TITLE
Added ExtensionalSwift

### PR DESCRIPTION
**Pull request by 4taras4**
ExtensionalSwift

## Project URL

https://github.com/4taras4/SwiftExtension
## Description

 ExtensionalSwift libryary of extensions
## Why it should be included to `awesome-ios` (optional)
ExtensionalSwift it's libryary for collect usefull swift extensions and help to other devs do thngs faster
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 3 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
330 | [301](https://httpstatuses.com/301) | https://github.com/oarrabi/Swiftline redirects to<br>https://github.com/nsomar/Swiftline
335 | [301](https://httpstatuses.com/301) | https://github.com/oarrabi/Guaka redirects to<br>https://github.com/nsomar/Guaka
1489 | [301](https://httpstatuses.com/301) | https://github.com/oarrabi/OAStackView redirects to<br>https://github.com/nsomar/OAStackView


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dkhamsing** [comment]
Hi
We only accept GitHub projects with at least 15 stars
https://github.com/matteocrippa/awesome-swift/blob/master/.github/CONTRIBUTING.md

Thanks

**Comment by victorgama** [comment]
Hi @4taras4!
As of our [Contribution Guidelines](https://github.com/vsouza/awesome-ios/blob/master/.github/CONTRIBUTING.md), Swift Extensions must have the `[e]` suffix.

Would you mind updating your PR so we can get this merged?

Thank you! 🙌

**Comment by 4taras4** [comment]
@victorgama Fixed

**Pull request merged**
