### PR TITLE
add Fusuma in Camera section

### PR DESCRIPTION
**Pull request by muhasturk**
## Project URL
https://github.com/ytakzk/Fusuma

## Description
Instagram-like photo browser and a camera feature with a few line of code in Swift.

## Checklist
- [x] Only one project is in the request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 and later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by dkhamsing** [comment]
Fusuma is already on the list under Images

**Comment by dkhamsing** [comment]
Will move it

**Comment by muhasturk** [comment]
in my opinion should be in camera section

**Comment by dkhamsing** [comment]
Can you open a pull request to move it?

**Comment by dkhamsing** [comment]
@muhasturk moved, thank you

**Pull request closed without merging**
