### PR TITLE
added JustHUD in Activity Indicator

### PR DESCRIPTION
**Pull request by shubh10**
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 5 link issues, a project collaborator will take care of these, thanks: )</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
260 | [301](https://httpstatuses.com/301) | https://github.com/philackm/Scrollable-GraphView redirects to<br>https://github.com/philackm/ScrollableGraphView
1581 | [301](https://httpstatuses.com/301) | https://github.com/SaeidBsn/GDCheckbox redirects to<br>https://github.com/saeid/GDCheckbox
1849 | [301](https://httpstatuses.com/301) | https://github.com/SaeidBsn/GDPersianCalendar redirects to<br>https://github.com/saeid/GDPersianCalendar
1862 | [301](https://httpstatuses.com/301) | https://github.com/jpotts18/SwiftValidator redirects to<br>https://github.com/SwiftValidatorCommunity/SwiftValidator
2333 | [301](https://httpstatuses.com/301) | https://github.com/SaeidBsn/SwiftyGuideOverlay redirects to<br>https://github.com/saeid/SwiftyGuideOverlay


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by shubh10** [comment]
Do I need to change anything?

**Comment by vsouza** [comment]
@shubh10 sorry. It's a redirect issue, we will solve this later. For now I'll accept your pull request. Thanks for contributing on Awesome-iOS

**Comment by shubh10** [comment]
Thanks. Yeah I'm aware of the redirect issue. I might fix that myself and put another pull req if get time :p

**Comment by shubh10** [comment]
Thank You.

**Pull request merged**
