### PR TITLE
Added AZTableViewController in Readme.md

### PR DESCRIPTION
**Pull request by AfrozZaheer**
## Project URL
https://github.com/AfrozZaheer/AZTableViewController 

## Category
UITableView 

## Description
Elegant and easy way to integrate pagination with dummy views in TableVIew. 
 
## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2737 | [404](https://httpstatuses.com/404) | https://swiftnews.curated.co/ 
2737 | [404](https://httpstatuses.com/404) | https://swiftnews.curated.co 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by AfrozZaheer** [comment]
Hi, I'm getting issue travis-ci failed due to some library.

**Comment by dkhamsing** [comment]
Please create a new pull request only adding your project

Fixing the other issues will be done by someone else

Thx!

**Comment by AfrozZaheer** [comment]
sure

**Pull request closed without merging**
