### PR TITLE
Add LNPopupController, LNInterpolation and LNChevronView to repo.

### PR DESCRIPTION
**Pull request by LeoNatan**
## Project URL

https://github.com/LeoNatan/LNPopupController
https://github.com/LeoNatan/LNInterpolation
https://github.com/LeoNatan/LNChevronView
## Description

Adding three of my frameworks. `LNPopupController` is already popular. The other two are new.
## Checklist

- [ ] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by LeoNatan** [comment]
I added three frameworks, and added them in one PR. 😃 They are all mine, so there should be no issues.

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 1 link issue</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1445 | [301](https://httpstatuses.com/301) | https://github.com/OEASLAN/OEANotification redirects to<br>https://github.com/OEA/OEANotification


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
```README.md``` in both Swift and Objective-C? Love it! 🎉🎉🎉🎉

**Comment by lfarah** [comment]
The only problem i found is in [LNChevronView](https://github.com/LeoNatan/LNChevronView).
We encourage people to send a pull request for each library to avoid problems like this, on where one of the libraries is not valid, but the other ones are

**Comment by lfarah** [comment]
Please fix [this issue](https://github.com/LeoNatan/LNChevronView/issues/1)

**Comment by lfarah** [comment]
Also [this one](https://github.com/LeoNatan/LNInterpolation/issues/1)

**Comment by LeoNatan** [comment]
Can you tell me what is invalid so I can fix? The chevron view is a very simple framework.

**Comment by lfarah** [comment]
@LeoNatan just opened issues. Let me know what you think 😉

**Comment by LeoNatan** [comment]
I do not support CocoaPods. I'll add Carthage instructions soon.

**Comment by lfarah** [comment]
@LeoNatan CocoaPods is not a requirement for libs in AwesomeiOS, but we request an installation section on the ```Readme.md```

**Comment by LeoNatan** [comment]
Cool. It's good to have, I agree.

**Comment by LeoNatan** [comment]
@lfarah I updated the repositories with installation instructions.

**Comment by lfarah** [comment]
@LeoNatan can you add more information on **LNChevronView**? You can check a complete one [HERE](https://github.com/awesome-labs/iOS-readme-template)

**Comment by lfarah** [comment]
@LeoNatan let me know if you need any help!

**Comment by lfarah** [comment]
@LeoNatan I think it would be cool to say where this chevron view is used, how to implement on Storyboard and how to implement programmatically. There are a lot of people new to programming and they require more information.

**Comment by LeoNatan** [comment]
OK, I'll add some more information later.

**Comment by LeoNatan** [comment]
@lfarah Added more information to the README.

**Comment by lfarah** [comment]
@LeoNatan perfect! Now you just have to rebase because there are merge conflicts.
Lemme know if you need any help! 👍

**Comment by LeoNatan** [comment]
@lfarah Merged.

**Comment by dkhamsing** [comment]
Bad merge, should not be deleting anything 
Can u fix it

**Comment by LeoNatan** [comment]
@dkhamsing  Ehh, I wonder what happened. Will take care of that soon.

**Comment by dkhamsing** [comment]
closing for now, feel free to submit again

we prefer you send one project per pull request

thanks!

**Pull request closed without merging**
