### PR TITLE
Added delightful framework for iOS to easily persist structs, images, and data. 

### PR DESCRIPTION
**Pull request by karthironald**
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1557 | [404](https://httpstatuses.com/404) | https://github.com/mancunianetz/iCheckbox 
2645 | [301](https://httpstatuses.com/301) | http://www.tutorialspoint.com/ios/ redirects to<br>https://www.tutorialspoint.com/ios/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by karthironald** [comment]
Hai, I haven't changed anything in lines 1557 and 2645. Can you please help me to resolve it?

**Comment by karthironald** [comment]
Hai,
 I haven't changed anything in lines 1557 and 2645. Can you please help me to resolve it?

Regards,

Karthick Selvaraj
Junior iOS developer

**Comment by dkhamsing** [comment]
Those errors will be fixed by someone else

Thx

**Comment by karthironald** [comment]
Fine, but I would like to add more libraries in future days, if i face same issue again and again means it will make delay in our process. So please try to fix it asap. :)


Regards,

Karthick Selvaraj
Junior iOS developer

**Pull request merged**
