### PR TITLE
Add RSKKeyboardAnimationObserver to UI section.

### PR DESCRIPTION
**Pull request by ruslanskorb**
This adds a keyboard animation observer called [RSKKeyboardAnimationObserver](https://github.com/ruslanskorb/RSKKeyboardAnimationObserver) to the UI section.

Thanks! :gem:

### CODE REVIEW

**Comment by ruslanskorb** [comment]
Also, I think we can group the libraries and frameworks related to the keyboard into the **Keyboard** subgroup.

**Comment by lfarah** [comment]
@ruslanskorb So, I was thinking about this and right now I'm putting things like [IQKeyboardManager](https://github.com/hackiftekhar/IQKeyboardManager) under Textfields

**Comment by ruslanskorb** [comment]
@lfarah Because of this I have put RSKKeyboardAnimationObserver under TextFields too :-]

**Comment by lfarah** [comment]
Awesome!

**Comment by lfarah** [comment]
But I'll keep in mind that we need a better Keyboards section, @ruslanskorb !

**Comment by ruslanskorb** [comment]
Thanks! :+1:

**Pull request merged**
