### PR TITLE
SAPinViewController

### PR DESCRIPTION
**Pull request by siavashalipour**
- added `SAPinViewController` GitHub repo link and description

Simple and easy to use default iOS PIN screen. This simple library allows you to draw a fully customisable PIN screen same as the iOS default PIN view. My inspiration to create this library was form THPinViewController, however SAPinViewController is completely implemented in Swift. Also the main purpose of creating this library was to have simple, easy to use and fully customisable PIN screen.
## Project URL

https://github.com/siavashalipour/SAPinViewController
## Description

 - added a new category for customisable PassCode View in UI view section.
- added SAPinViewController GitHub repo link and description

## Checklist

- [x] Only one project/change is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please update the Pull Request title to contain the library name</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by siavashalipour** [comment]
Any Updates? What should I fix? I've already Updated the PR

**Comment by victorgama** [comment]
Hi @siavashalipour! Thank you for contributing!

Would you mind moving your project to the [Security](https://github.com/vsouza/awesome-ios#security) category, rather than creating a new one?

Thank you! ✨

**Comment by siavashalipour** [comment]
Hi @victorgama , Yeah sure no worries. :)

**Comment by siavashalipour** [comment]
@victorgama Done :) . sorry about 4 commits, at first I added it to the wrong section and also forgot to delete the one category that I added before ;P .

**Comment by dkhamsing** [comment]
Thx

**Pull request merged**
