### PR TITLE
Added JMCMarchingAnts by @izotx

### PR DESCRIPTION
**Pull request by FelipeNBrito**
## Project URL

https://github.com/izotx/JMCMarchingAnts

## Description

Library that lets you add marching ants (animated) selection to the edges of the images.

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @FelipeNBrito, thanks for contributing.
The lib needs to be updated to the newest swift before we can add it on Awesome iOS.
I'm working on sending them a pull request right now

**Comment by lfarah** [comment]
Just opened [an issue](https://github.com/izotx/JMCMarchingAnts/issues/2) and a [Pull Request](https://github.com/izotx/JMCMarchingAnts/pull/3)

**Comment by lfarah** [comment]
You guys were fast! 🚀 🚀 🚀

**Comment by FelipeNBrito** [comment]
Thanks @lfarah

**Pull request merged**
