### PR TITLE
Added Kotlin for Swift Developers

### PR DESCRIPTION
**Pull request by aashishtamsya**
Added Link in Reference Section for a project about **Kotlin Development for Swift Developers**.

## Project URL
[Project URL](https://github.com/aashishtamsya/Kotlin-for-Swift-Developers)

## Description
This project focus only on Kotlin, not Android Application Development with Kotlin. I feel the need to learning Kotlin basics and building a string Kotlin foundation before jumping into Android Development.
 
## Why it should be included to `awesome-ios`

It should be added in awesome-ios so that swift developers will have a hands on starting point to start development in Kotlin which will eventually lead **_Swift Developers to develop for both Android & iOS_**.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 3 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1253 | [301](https://httpstatuses.com/301) | https://github.com/hyperoslo/Keychain redirects to<br>https://github.com/hyperoslo/Keychains
2584 | [301](https://httpstatuses.com/301) | http://tryobjectivec.codeschool.com/ redirects to<br>https://www.codeschool.com/courses/try-objective-c
2619 | Error | http://swiftsandbox.io <br> getaddrinfo: Name or service not known


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
What do you guys think, @vsouza @dkhamsing @naeemshaikh90?

**Comment by victorgama** [comment]
I don't think this fits the purpose of this repository. 🤔

**Comment by naeemshaikh90** [comment]
Agree with @victorgama .

**Comment by vsouza** [comment]
Agree with @victorgama too.

**Comment by victorgama** [comment]
Let's close this one, then. Thank you for the PR, @aashishtamsya!

**Pull request closed without merging**
