### PR TITLE
Add Aptabase

### PR DESCRIPTION
**Pull request by goenning**
Thanks for your contribution! This is a template that can make it easier when submitting your contribution:

**Your Project**: Aptabase  
**Project URL**: https://github.com/aptabase/aptabase
**Category**: Analytics
**Description**: Aptabase is an open source, privacy-first and simple analytics for apps. The server is [aptabase/aptabase](https://github.com/aptabase/aptabase) and the Swift SDK is [aptabase/aptabase-swift](https://github.com/aptabase/aptabase-swift)

Inclusion requirements:
- [X] Has 50 GitHub stargazers or more
- [X] Only one project/change is in this pull request
- [X] Isn't an archived project
- [X] Has more than one contributor
- [X] Has unit tests, integration tests or UI tests
- [X] Addition in alphabetical order (bottom of category)
- [X] Supports iOS 12 / tvOS 10 or later
- [X] Supports Swift 4 or later
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English
 
:heart: Awesome iOS Contributors

### CODE REVIEW

**Comment by vsouza** [comment]
@goenning please, change the url to the Github project.

**Comment by goenning** [comment]
hi @vsouza can we keep the url as the custom domain? Seems like some other projects also have their URL pointing to a custom domain so I suppose it's allowed?

I actually changed it to https://aptabase.com/for-swift which is the iOS specific page. That page explain what the project is about and has links back to GitHub.

Does that work for you?

Obrigado :)

**Comment by vsouza** [comment]
@goenning I'm changing all the projects with custom domains and implementing validations with Github API. Will suit better change to the github url.

**Comment by vsouza** [comment]
@goenning Nevermind. I'll accept the pull request with the custom domain. In the future we can discuss further more.

**Pull request merged**
