### PR TITLE
removed dc animation

### PR DESCRIPTION
**Pull request by goktugyil**
cause it hasn't been updated for 2 years

### CODE REVIEW

**Comment by goktugyil** [comment]
@lfarah

**Comment by vsouza** [comment]
I agree that an outdated project could not be useful to the list. But if we apply this in this repo, we should make a clean in other cases. don't?

**Comment by lfarah** [comment]
@vsouza In about an year, we should do this cleaning. About this case right now, not worth it

**Comment by dkhamsing** [comment]
Created an issue for this

Closing for now

**Pull request closed without merging**
