### PR TITLE
Add CuckooAlert on Alert View

### PR DESCRIPTION
**Pull request by singcodes**
add CuckooAlert on Alert View section.

## Project URL
https://github.com/singcodes/CuckooAlert

## Description
Using method swizzling, make multiple UIAlertControllers can use presentViewController for on view controller. 

## Checklist
- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English
- [x] `Travis CI` pass

### CODE REVIEW

**Comment by vsouza** [comment]
@singcodes can you rebase please?

**Comment by singcodes** [comment]
Oh, sorry, I couldn't understand clearly. @vsouza  You mean rebase to my fork of awesome-iso?

**Comment by singcodes** [comment]
@vsouza
oh, I have forgot did it.

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dkhamsing** [comment]
@singcodes sorry we are not gonna accept your project as it is still a "work in progress"

**Comment by singcodes** [comment]
@dkhamsing 
Sorry, I haven't not yet fully understand current process of pull to request. Can I ask explain more that "work in progress", please? It's my libs problem? or commits?

**Comment by dkhamsing** [comment]
Your README says 
> 0.0.1
> Work in progress

That's not something we want included on the list 
Thx

**Comment by singcodes** [comment]
@dkhamsing 
OMG. I should delete it. will fix it.

**Comment by singcodes** [comment]
@dkhamsing 
oh, that's not exactly intent do it's mean. Would you allow pull to request to remove that part?

**Comment by dkhamsing** [comment]
Hm @lfarah 
What do you think

**Comment by singcodes** [comment]
@dkhamsing 
I commits to CuckooAlert for udpate README.md

**Pull request closed without merging**
