### PR TITLE
Add Kraken description in README.md

### PR DESCRIPTION
**Pull request by sabirvirtuoso**
## Project URL
https://github.com/sabirvirtuoso/Kraken

## Description
Kraken is a dependency injection framework for Swift with easy to use syntax. Among the very few dependency injection containers available for Swift, Kraken is a great and easy one to get started. Kraken provides almost all the features of a good dependency container along with easy syntax. Available for use in iOS.

## Checklist

- [x] Only one project is in the request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @sabirvirtuoso, your library is awesome and we appreciate your contribution.
The only problem is that the lib needs to be in the end of the category:
>   Addition in chronological order (bottom of category)

Thanks. 😄

**Comment by sabirvirtuoso** [comment]
The library is now added in chronological order. Please accept the pull request.

**Comment by vsouza** [comment]
I have to call retry build on travis. 

Thanks for contribution.

**Comment by lfarah** [comment]
😃

**Pull request merged**
