### PR TITLE
Added a link for Chart library

### PR DESCRIPTION
**Pull request by dhirenthirani**
## Checklist

- [ ] Only one project is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [ ] `Travis CI` pass
- [ ] Supports iOS 7 or later
- [ ] Has a commit from less than 2 years ago
- [ ] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @dhirenthirani, thanks for the contribution. Could you please move the library to the end of the section?

**Comment by dhirenthirani** [comment]
@lfarah , I have moved it at the end but y did u asked me to do that?

**Comment by dfed** [comment]
See the checklist: `Addition in chronological order (bottom of category)` :)

**Comment by lfarah** [comment]
@dhirenthirani we do this in order to have a better organization of the list 😉

**Comment by lfarah** [comment]
Also shoudn't have :large_orange_diamond: because it is an Objective-C library, but don't worry because I'll fix it.

Thanks for contributing 👍

**Pull request merged**
