### PR TITLE
Added Stacktrace to podcasts

### PR DESCRIPTION
**Pull request by pavelshadrin**
**Your Project**: _Stacktrace_  
**Project URL**: _https://stacktracepodcast.fm/_  
**Category**: _Podcasts_  
**Description**: _An awesome podcast about iOS development by Rambo and Sundell (already on the list as well)_
 
:heart: Awesome iOS Contributors

### CODE REVIEW

**Review by TRISS708 — APPROVED** [review]

**Comment by vsouza** [comment]
@pavelshadrin Thanks for contributing!

**Comment by TRISS708** [comment]
Hi, may I ask what’s going on? I’m kind of scaredSent from my iPhoneOn Jul 24, 2023, at 10:31 AM, Vinicius Souza ***@***.***> wrote:﻿
@pavelshadrin Thanks for contributing!

**Comment by TRISS708** [comment]
Hi, could you reply to inform me what’s happening here? I deleted GitHub because I couldn’t link a  node.js repository as the hackers would instantly comment and put codes in first. I reported them. They even posted the VM they built and put us and lord knows who else insideSent from my iPhoneOn Jul 24, 2023, at 10:31 AM, Vinicius Souza ***@***.***> wrote:﻿
@pavelshadrin Thanks for contributing!

**Comment by TRISS708** [comment]
Why have you not told me what this is about?? Apple GitHub has been putting codes on me and won’t even tell me what they are doing so I don’t believe them to be helping my ransomware situation. I’m configured to a hackers Mac OS who’s robbing me blind and attacked me on lockdown. You deny my bounties but I got a private investigator and found their codes. I’ll submit later. But can you reverse whatever these people did without my permission This matter is going to court. I’ve lost my job and 5k. I’m coming at every company who failed me and GitHub won’t stop allowing attacks either. Sent from my iPhoneOn Jul 24, 2023, at 1:11 PM, Trisha Rohrer ***@***.***> wrote:﻿Hi, may I ask what’s going on? I’m kind of scaredSent from my iPhoneOn Jul 24, 2023, at 10:31 AM, Vinicius Souza ***@***.***> wrote:﻿
@pavelshadrin Thanks for contributing!

**Pull request merged**
