### PR TITLE
Added TinyConstraints to Layout

### PR DESCRIPTION
**Pull request by yoha**
Added TinyConstraints to Layout

## Project URL
https://github.com/roberthein/TinyConstraints

## Description

same as above
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
@dkhamsing wtf is shippable?

**Comment by lfarah** [comment]
Hey @yoha, cool lib 👍 

thanks again for coming back and contributing!

**Comment by yoha** [comment]
@lfarah always glad to contribute! :)

**Comment by naeemshaikh90** [comment]
#1453 😄

**Comment by dkhamsing** [comment]
@lfarah no idea
Let me now if u find out

**Comment by lfarah** [comment]
@vsouza?

**Comment by vsouza** [comment]
Yes, I've added shippable build for awesome-iOS. But it's still failling, we can ignore this for now.

**Comment by vsouza** [comment]
Yes, I've added shippable build for awesome-iOS. But it's still failing, we can ignore this for now.

**Pull request merged**
