### PR TITLE
Added AZEmptyState

### PR DESCRIPTION
**Pull request by Minitour**
## Project URL
https://github.com/Minitour/AZEmptyState

## Description
A UIControl subclass that makes it easy to create empty states.
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 5 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1766 | [301](https://httpstatuses.com/301) | https://github.com/gizmoboy7/VCFloatingActionButton redirects to<br>https://github.com/giridharvc7/VCFloatingActionButton
2537 | Error | https://www.ioscreator.com/ <br> Connection refused - connect(2) for "www.ioscreator.com" port 443
2652 | [502](https://httpstatuses.com/502) | https://www.manning.com/books/hello-swift 
2653 | [502](https://httpstatuses.com/502) | https://www.manning.com/books/ios-development-with-swift 
2654 | [502](https://httpstatuses.com/502) | https://www.manning.com/books/anyone-can-create-an-app 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by miguelarauj1o** [comment]
@Minitour, pull requests should have only one commit.

**Comment by Minitour** [comment]
I'll guess I'll have to recreate this pull request.

**Comment by miguelarauj1o** [comment]
You could splash commits.
See https://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one

**Pull request closed without merging**
