### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Giiovannini**
## Project URL

https://github.com/CosmicMind/Material
## Description

Material is an animation and graphics framework that allows developers to easily create beautiful applications. 
## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English
- [x] `Travis CI` pass

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found links issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Please update the Pull Request title</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
372 | [301](https://httpstatuses.com/301) | https://github.com/qutheory/fluent redirects to<br>https://github.com/vapor/fluent
1614 | [301](https://httpstatuses.com/301) | https://github.com/qutheory/vapor redirects to<br>https://github.com/vapor/vapor


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dkhamsing** [comment]
@lfarah please rename pull request title in the future, thx

**Comment by lfarah** [comment]
@dkhamsing it wasn't me 😢

**Comment by dkhamsing** [comment]
yeah i meant before merging, but it's all good
thx

**Pull request merged**
