### PR TITLE
Add VHUD

### PR DESCRIPTION
**Pull request by RemyDCF**
Added VHUD to UI/Activity Indicator, a simple HUD.

## Project URL
https://github.com/xxxAIRINxxx/VHUD

## Description
Simple HUD.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
638 | [301](https://httpstatuses.com/301) | https://github.com/comyarzaheri/TuningFork redirects to<br>https://github.com/comyar/TuningFork


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Hey @RemyDCF, we gotta wait until [this pull request](https://github.com/xxxAIRINxxx/VHUD/pull/1) is accepted before adding it to AwesomeiOS.

Thanks for contributing! 👍

**Comment by RemyDCF** [comment]
The pull request on VHUD project was merged. Can you merge my pull request ?

**Comment by lfarah** [comment]
Hey @RemyDCF, thanks for the update. Unfortunately I can't merge since there are conflicts. Please rebase your pull request.

**Comment by RemyDCF** [comment]
Rebased

**Comment by vsouza** [comment]
@RemyDCF you should remove `<<<<HEAD` from your commit. avoid to broken whole file

**Comment by vsouza** [comment]
thanks @RemyDCF  :)

**Pull request merged**
