### PR TITLE
Add AELog and AEConsole

### PR DESCRIPTION
**Pull request by tadija**
## Project URL
https://github.com/tadija/AELog
https://github.com/tadija/AEConsole

## Description
I've added AELog - Minimalistic but flexible logging approach in Swift and AEConsole - which is displaying debug log from AELog in Console UI overlay on top of any app. (both under Logging). 

## Checklist:
- [ ] One project per pull request
- [ ] `Travis CI` pass

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @tadija, we'd love if next time you made a PR for each library to make things easier.
Your libraries are awesome! :wink:

**Comment by tadija** [comment]
Thanks for nice words @lfarah!
Ok, I'll make sure to create separate PRs in future. It doesn't matter if two are very related like from this PR?

**Comment by lfarah** [comment]
It just make things easier if you always make it separate PRs. That's how I organize all my emails and stuff I gotta review before approving the PR.
But in the end of the day, I always say that the contributors are doing a favor, so I won't bitch about small stuff to make their lives more difficult

**Comment by tadija** [comment]
ok, I understand, no problem, thanks for making the exception this time! o/

**Pull request merged**
