### PR TITLE
Add Koyomi by @shoheiyokoyama

### PR DESCRIPTION
**Pull request by havthgem**
## Project URL
https://github.com/shoheiyokoyama/Koyomi

## Description
Simple customizable calendar component in Swift
 
## Why it should be included to `awesome-ios` (optional)
Clean and customizable

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [ ] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 3 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1446 | [301](https://httpstatuses.com/301) | https://github.com/OEASLAN/OEANotification redirects to<br>https://github.com/OEA/OEANotification
2285 | [301](https://httpstatuses.com/301) | https://github.com/sxyx2008/awesome-ios-animation redirects to<br>https://github.com/ameizi/awesome-ios-animation
2286 | [301](https://httpstatuses.com/301) | https://github.com/sxyx2008/awesome-ios-chart redirects to<br>https://github.com/ameizi/awesome-ios-chart


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dkhamsing** [comment]
Looks good
Let's wait for `swift3`

**Comment by shoheiyokoyama** [comment]
Please wait a little longer :stuck_out_tongue_closed_eyes:

**Comment by havthgem** [comment]
@shoheiyokoyama がんばれ！

**Comment by shoheiyokoyama** [comment]
@dkhamsing
@havthgem 
Hi, conversion to swift3 has just finished :confetti_ball: :tada:
Thank you for waiting :smiley:

**Comment by lfarah** [comment]
Thanks, @shoheiyokoyama 😃 👍

**Pull request merged**
