### PR TITLE
Add BatteryView

### PR DESCRIPTION
**Pull request by yonat**
## Project URL
https://github.com/yonat/BatteryView

## Description
Simple battery shaped UIView.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by yonat** [comment]
And that's the last one...

**Comment by lfarah** [comment]
What do you guys think, @dkhamsing @vsouza?

**Comment by victorgama** [comment]
@lfarah I believe @yonat can provide us a use case of this library, so we can figure out how to proceed with this PR. ✨

**Comment by yonat** [comment]
Ah, I use it to show the battery level of bluetooth peripherals, so users can know when to charge them.

**Comment by victorgama** [comment]
LGTM! Could you please rebase your changes? We will merge them right after. :)

**Comment by yonat** [comment]
@victorgama thanks, just did.

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
766 | [301](https://httpstatuses.com/301) | https://github.com/zalando-incubator/MapleBacon redirects to<br>https://github.com/JanGorman/MapleBacon
992 | [301](https://httpstatuses.com/301) | http://www.netmera.com redirects to<br>https://www.netmera.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by yonat** [comment]
@victorgama I just rebased.

**Comment by victorgama** [comment]
@yonat Thank you!

**Pull request merged**
