### PR TITLE
add SwiftyHelpOverlay

### PR DESCRIPTION
**Pull request by SaeidBsn**
## Project URL
https://github.com/SaeidBsn/SwiftyGuideOverlay

## Description
Add SwiftyGuideOverlay lib to repo
App Intro / instruction component to show data over app UI at run time and real-time!

## Why it should be included to `awesome-ios` (optional)
Very useful library to show instructions over app UI also easy to use!

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
603 | [502](https://httpstatuses.com/502) | https://locationkit.io 
2545 | [522](https://httpstatuses.com/522) | http://rypress.com/tutorials/objective-c/index 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by victorgama** [comment]
@SaeidBsn Hi there!
Would you mind moving your project from `UI` to `Walkthrough / Intro / Tutorial`? 

Also, if possible, please do rebase your changes to keep them in a single commit.

Thank you for contributing! 🙌

**Comment by victorgama** [comment]
Nice! Thank you! :)

**Comment by SaeidBsn** [comment]
@victorBaro Thank you very much for modifications and suggestions 👍

**Pull request merged**
