### PR TITLE
Add NextGrowingTextView

### PR DESCRIPTION
**Pull request by muukii**

### CODE REVIEW

**Comment by victorgama** [comment]
Would you mind moving your project to the bottom of the category? Thanks!

**Comment by dkhamsing** [comment]
Also should move to TextField

**Comment by dkhamsing** [comment]
@muukii can you update pull request

**Comment by lfarah** [comment]
@vsouza 25 days... can I close this and commit it myself?

**Comment by dkhamsing** [comment]
Sure

**Comment by vsouza** [comment]
:smile:

**Pull request closed without merging**
