### PR TITLE
classic-problem-solving-algorithms-and-data-structures-in-swift added under 'other awesome lists'

### PR DESCRIPTION
**Pull request by smalam119**
## Project URL
https://github.com/smalam119/classic-problem-solving-algorithms-and-data-structures-in-swift

## Category
Data Structure

## Description
A collection of popular algorithms, data structures and problem solving written in Swift 4
 
## Why it should be included to `awesome-ios` (optional)
I believe my repo will be helpful for Swift developers to learn and contribute to data structure, algorithm etc.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please update the Pull Request title to contain the library name</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by smalam119** [comment]
pull request title updated.

**Comment by vsouza** [comment]
Please, move to 'Other Awesome Lists' category

**Comment by smalam119** [comment]
you welcome. now added under 'other awesome lists'

**Pull request merged**
