### PR TITLE
Add playkit-ios.

### PR DESCRIPTION
**Pull request by arasu01**
Playkit iOS

## Project URL
https://github.com/kaltura/playkit-ios

## Description
PlayKit: Kaltura Player SDK for iOS. 
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [ ] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by naeemshaikh90** [comment]
What you thing guys? @dkhamsing @victorgama ?

**Comment by vsouza** [comment]
@naeemshaikh90 What's wrong with this project?

**Comment by victorgama** [comment]
Hi @arasu01, thank you for contributing! :tada:
Would you mind moving it to `SDK/Official` so we can get this merged?

Thank you!

**Comment by arasu01** [comment]
@victorgama: Done.

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2543 | [522](https://httpstatuses.com/522) | http://rypress.com/tutorials/objective-c/index 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by naeemshaikh90** [comment]
Hey @arasu01 thanks for contributing to `awesome-ios` 🎉🎉🎉

**Pull request merged**
