### PR TITLE
Add ScrollingFollowView by @ktanaka117 to ScrollView section

### PR DESCRIPTION
**Pull request by ktanaka117**
## Project URL

https://github.com/ktanaka117/ScrollingFollowView

## Description

Add a library to README.md.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 2 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
679 | [301](https://httpstatuses.com/301) | https://github.com/evgenyneu/sound-fader-ios redirects to<br>https://github.com/evgenyneu/Cephalopod
682 | [301](https://httpstatuses.com/301) | https://github.com/recisio/AudioPlayerSwift redirects to<br>https://github.com/tbaranes/AudioPlayerSwift


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by ktanaka117** [comment]
@lfarah

The reason of creating a **ScrollView** section is that I think this library is related to UIScrollView.

I want to hear the reason if there is no need to create a new section or you don't want to create a new section.

**Comment by vsouza** [comment]
@lfarah If we has more projects like this, I think will be more appropriate a new section.

**Comment by lfarah** [comment]
Found more libs. Merging this!

**Comment by cm-TanakaKenji** [comment]
Thanks!

**Pull request merged**
