### PR TITLE
Add ViperServices

### PR DESCRIPTION
**Pull request by ladeiko**
## Project URL

https://github.com/ladeiko/ViperServices

## Category

Injection

## Description

Simple dependency injection supporting boot order of services

## Why it should be included to `awesome-ios` (optional)
It's simple 

## Checklist

- [x] Only one project/change is in this pull request
- [x] Has unit tests, integration tests or UI tests
- [ ] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [ ] Has a commit from less than 2 years ago
- [ ] Has a **clear** README in English

### CODE REVIEW

**Comment by vsouza** [comment]
@ladeiko Thanks for contributing. Please, can you fill the `description` section in your repository?

**Comment by ladeiko** [comment]
Description where?

**Comment by vsouza** [comment]
@ladeiko this:

screen shot 2018-07-09 at 11 29 50 am

**Comment by ladeiko** [comment]
Added

**Comment by vsouza** [comment]
@ladeiko Thanks for contributing.

**Pull request merged**
