### PR TITLE
Add Microfeatures

### PR DESCRIPTION
**Pull request by pepibumur**
## Project URL
https://github.com/microfeatures

## Description
Add microfeatures
 
## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
@pepibumur nice lib 👍 
Please add a ```:large_orange_diamond:``` in the end of the description since it is a Swift project

**Comment by pepibumur** [comment]
Done @lfarah

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
637 | [301](https://httpstatuses.com/301) | https://github.com/SocialObjects-Software/SOMotionDetector redirects to<br>https://github.com/arturdev/SOMotionDetector
1283 | [301](https://httpstatuses.com/301) | https://creativesdk.adobe.com/ redirects to<br>https://www.adobe.io/apis/creativecloud/creativesdk.html


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dkhamsing** [comment]
thx

**Pull request merged**
