### PR TITLE
Added KDDragAndDropCollectionView

### PR DESCRIPTION
**Pull request by mmick66**
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1 | [500](https://httpstatuses.com/500) | https://raw.githubusercontent.com/vsouza/awesome-ios/master/awesome_logo.png 
2369 | [301](https://httpstatuses.com/301) | https://github.com/Swiftification/Dispatch redirects to<br>https://github.com/JARMourato/Dispatch


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @mmick66, thanks for contributing 🙌

In order for me to merge your PR, please fix the issues above

**Comment by mmick66** [comment]
Hello lfarah, I made the change in the Installation section of the readme file. Any progress on your side?

**Comment by lfarah** [comment]
Hey @mmick66, thanks again for contributing!

**Pull request merged**
