### PR TITLE
Added ReactiveAPI

### PR DESCRIPTION
**Pull request by gotev**
ReactiveAPI allows you to write clean, concise and declarative network code relying on URLSession, with the power of RxSwift. Inspired by Retrofit.

## Project URL
https://github.com/sky-uk/ReactiveAPI

## Category
Networking

## Description
Write clean, concise and declarative network code relying on URLSession, with the power of RxSwift. Inspired by Retrofit.

## Why it should be included to `awesome-ios` (mandatory)
It speeds up iOS network coding, it reduces errors and allows you to have much shorter and more readable code if compared to standard URLSession or other libraries such as Alamofire or Moya. It has working examples on how to work with both authenticated and unauthenticated APIs, together with a demo backend which can be used for testing.

## Checklist

- [ ] Has 50 Github stargazers or more
- [x] Only one project/change is in this pull request
- [x] Isn't an archived project
- [x] Has more than one contributor
- [ ] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later (Swift 5)
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 15 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
237 | [301](https://httpstatuses.com/301) | https://www.bugsnag.com/platforms/ios-crash-reporting/ redirects to<br>https://www.bugsnag.com/platforms/ios-crash-reporting
306 | [301](https://httpstatuses.com/301) | https://github.com/svtek/ARKitEnvironmentMapper redirects to<br>https://github.com/svhawks/ARKitEnvironmentMapper
488 | [301](https://httpstatuses.com/301) | https://github.com/jianstm/Crayon redirects to<br>https://github.com/luoxiu/Crayon
653 | [301](https://httpstatuses.com/301) | https://github.com/jianstm/Schedule redirects to<br>https://github.com/luoxiu/Schedule
1384 | [301](https://httpstatuses.com/301) | https://www.urbanairship.com/products/mobile-app-engagement redirects to<br>https://airship.com/products/mobile-app-engagement
1389 | [301](https://httpstatuses.com/301) | http://www.carnival.io redirects to<br>https://www.sailthru.com
1439 | [301](https://httpstatuses.com/301) | https://github.com/DanToml/Jay redirects to<br>https://github.com/endocrimes/Jay
1458 | [301](https://httpstatuses.com/301) | https://github.com/bernikowich/NSTEasyJSON redirects to<br>https://github.com/bernikovich/NSTEasyJSON
1660 | [404](https://httpstatuses.com/404) | https://github.com/genadyo/Lyft 
1807 | [404](https://httpstatuses.com/404) | https://github.com/loiclec/Apodimark 
2923 | [301](https://httpstatuses.com/301) | https://github.com/jianstm/Once redirects to<br>https://github.com/luoxiu/Once
2947 | [301](https://httpstatuses.com/301) | https://github.com/svtek/VideoSplashKit redirects to<br>https://github.com/svhawks/VideoSplashKit
3045 | [301](https://httpstatuses.com/301) | https://github.com/facebook/FBSimulatorControl redirects to<br>https://github.com/facebook/idb
3309 | [301](https://httpstatuses.com/301) | https://www.imore.com/node/24121 redirects to<br>https://www.imore.com/debug
3319 | [302](https://httpstatuses.com/302) | http://consultpodcast.com/ redirects to<br>https://consultpodcast.com/#_=_


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@gotev We cannot merge your PR yet until you fill all of the contribution guideline requirements. Feel free to open PR once it is ready.

Please check our [CONTRIBUTION GUIDELINES](https://github.com/vsouza/awesome-ios/blob/master/.github/CONTRIBUTING.md)

**Comment by gotev** [comment]
Is it for the existing link issues?

**Comment by vsouza** [comment]
@gotev Nope. Some items contribution guidelines aren't cover in this project. Once it is ready, you can reopen this PR. Thank you.

**Comment by gotev** [comment]
Thanks, so we can close this and then I'll make a PR once all the things are met

**Pull request closed without merging**
