### PR TITLE
adding ProgressMeter iOS library

### PR DESCRIPTION
**Pull request by khawajafarooq**
## Project URL
https://github.com/khawajafarooq/ProgressMeter

## Description
Following are the changes:
1. Adding category `ProgressView` under UI section
2. Adding ProgressMeter iOS library under `ProgressView` section
 
## Why it should be included to `awesome-ios` (optional)
Adding value to progress view with a meter like UI and custom annotations. Everything is enabled for iOS >=9.0 and Swift 4.0. The control supports autolayout.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 3 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
854 | [301](https://httpstatuses.com/301) | https://github.com/terflogag/FacebookImagePicker redirects to<br>https://github.com/floriangbh/FacebookImagePicker
1355 | [301](https://httpstatuses.com/301) | https://github.com/SwiftOnEdge/Edge redirects to<br>https://github.com/skylab-inc/Edge
2389 | [301](https://httpstatuses.com/301) | https://github.com/terflogag/OpenSourceController redirects to<br>https://github.com/floriangbh/OpenSourceController


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dkhamsing** [comment]
Thanks @khawajafarooq 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by khawajafarooq** [comment]
Hi, are you going to merge it?

**Comment by lfarah** [comment]
Sorry for the delay, @khawajafarooq!
Thank you so much for contributing and good job on the lib 👍

**Pull request merged**
