### PR TITLE
Add DateTimePicker

### PR DESCRIPTION
**Pull request by naeemshaikh90**
## Project URL
https://github.com/itsmeichigo/DateTimePicker

## Description
A nicer iOS UI component for picking date and time
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 2 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1914 | [301](https://httpstatuses.com/301) | https://github.com/movielala/VideoSplashKit redirects to<br>https://github.com/mojilala/VideoSplashKit
2158 | [301](https://httpstatuses.com/301) | https://www.reddit.com/r/iosprogramming redirects to<br>https://www.reddit.com/r/iOSProgramming/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by azawawi** [comment]
@naeemshaikh90  The project states **iOS 9 and later**  (not iOS 8.0+) in its `README.md`.

**Comment by lfarah** [comment]
@azawawi What do you think about this? #1198

**Comment by lfarah** [comment]
Thanks! 😉

**Pull request merged**
