### PR TITLE
Add iOS Security Class  

### PR DESCRIPTION
**Pull request by karek314**
## Project URL
#1277 
#1276 

## Description
https://github.com/karek314/awesome-ios/commit/c2c415c89b4d04ebbf2f33da61378b6b85619f7e
 
## Why it should be included to `awesome-ios` (optional)
Refer to 
#1277 
#1276 

## Checklist
- [ ] Only one project/change is in this pull request
- [X] Addition in chronological order (bottom of category)
- [X] Supports iOS 9 or later
- [ ] Supports Swift 3
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
987 | [301](https://httpstatuses.com/301) | https://github.com/alvinvarghese/EasyIAPs redirects to<br>https://github.com/aaalveee/EasyIAPs


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Hey @karek314, thanks for contributing!
Your libraries are awesome but they need some work before I can add it to AwesomeiOS.
As you can see above, I already opened an issue on iOS App Security Class.

Regarding [Objective-C-CLI-Obfuscator](https://github.com/karek314/Objective-C-CLI-Obfuscator), I'd ask you to fix the Git repository and transform into an actual repository instead of being a fork. I'd ask you to improve the README as well.

**Comment by lfarah** [comment]
@karek314 now we're just missing the README changes on Objective-C-CLI-Obfuscator!

**Comment by karek314** [comment]
@lfarah Hello, It has been updated recently.
https://github.com/karek314/Objective-C-CLI-Obfuscator

**Comment by lfarah** [comment]
I'm worried about the Apple Review thing because some users may not know that there's a special branch. @dkhamsing what do you think?

**Comment by dkhamsing** [comment]
Apple reviews issue is not so good ..

**Comment by karek314** [comment]
@lfarah - i've added direct url to that branch in description.
@dkhamsing  - not sure what do you mean ?

**Comment by dkhamsing** [comment]
I mean that is a problem and maybe we should not add this project to the list

I will let @lfarah decide

**Comment by karek314** [comment]
@dkhamsing As i've said, it happens sometimes. Developer agreement have couple weird conflicting rules about this, from my understanding it should be allowed by apple, it seems there is some confusing among apple reviewers, anyway i've mentioned about possible outcome of usage, Apple store is not only one possible distribution of apps, might be helpful for some people.

**Comment by victorgama** [comment]
I would agree with @karek314 if this repository was not iOS-centric. 
Given the App Store is the only official distribution method for both business and public apps, I also think we should not add this project to the list.

@lfarah its up to you.

**Comment by karek314** [comment]
@victorgama Apps can be also signed with special distribution certificate and distributed from website, it's official afaik. unofficial is cydia and some other stores form pangu etc.

Im still standing on my position that it's useful to add. Branch apple-review-safe is safe for submission. If not, it's not problem, obfuscation can be easily removed by simply deleting symbols header and restoring storyboards, apple will not suspend developer account for that, they will just ask to remove obfuscation in case they don't like it.

**Comment by lfarah** [comment]
I'm sorry @karek314, but I agree with @dkhamsing and @victorgama.

Can you please remove ```Objective-C-CLI-Obfuscator``` from the PR?

**Comment by karek314** [comment]
Ok, fair enough. Removed obfuscator.

**Pull request merged**
