### PR TITLE
nef - Xcode Editor Extension

### PR DESCRIPTION
**Pull request by miguelangel-dev**
## Project URL
https://github.com/bow-swift/nef-plugin

## Category
Extensions (Xcode 8+)

## Description
This project provides an extension for Xcode to integrate some nef features directly in the IDE. Using the core of nef, you can export snippets from your code selection directly in Xcode.

## Why it should be included to `awesome-ios` (mandatory)
You know all of those code screenshots you see on social networks, or at meetups and conferences? Do you want to share images of your code with your team? This Xcode extension makes it easy to create and share beautiful images of your source code.

## Checklist
- [ ] Has 50 GitHub stargazers or more (it has been launched today but is under umbrella another repository, and it has more than 50 stars - https://github.com/bow-swift/nef)
- [x] Only one project/change is in this pull request
- [x] Isn't an archived project
- [x] Has more than one contributor
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 3 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
4 | [302](https://httpstatuses.com/302) | https://triplebyte.com/a/azelHFa/d redirects to<br>https://triplebyte.com/
1980 | [404](https://httpstatuses.com/404) | https://github.com/oxozle/OXPatternLock 
2008 | [301](https://httpstatuses.com/301) | https://github.com/Babylonpartners/DrawerKit redirects to<br>https://github.com/babylonhealth/DrawerKit


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@miguelangel-dev Can you remove the extra links in description. I'm finishing a bot to check some useful information to keep awesome-ios updated with healthy projects, and the extra links could be a problem.

**Comment by miguelangel-dev** [comment]
Done, thanks!

**Comment by miguelangel-dev** [comment]
@vsouza do you need any other action from me?

**Comment by vsouza** [comment]
@miguelangel-dev Thanks for contributing!

**Pull request merged**
