### PR TITLE
Added SuperDelegate

### PR DESCRIPTION
**Pull request by dfed**
Created an [UI]ApplicationDelegate section and added SuperDelegate to it.

## Project URL
https://github.com/square/SuperDelegate

## Description
Added the Section "Content -> UI -> ApplicationDelegate" and added the SuperDelegate project to it.

## Checklist
- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
@dkhamsing @vsouza what do you guys think? 💭💭💭

**Comment by onmyway133** [comment]
@dfed this is nice 🎉

**Comment by lfarah** [comment]
@onmyway133 @victorgama  do you guys know any other ```ApplicationDelegate``` libraries?

**Comment by vsouza** [comment]
@lfarah we can merge this?

**Comment by lfarah** [comment]
Hey @dfed, I discussed with @vsouza and we think it's better to add * SuperDelegate* under ```Tools```

**Comment by dfed** [comment]
Sounds great! I've updated the commit. Appreciate the consideration :)

**Pull request merged**
