### PR TITLE
Pull Request Report

### LINKED ISSUE #983: Report link issues in pull request
[danger-junit](https://github.com/orta/danger-junit) lets you report your test suite problems back to the PR elegantly, so instead of having to open Travis every time to see why the test failed, it's already there on the PR.

### PR DESCRIPTION
**Pull request by dkhamsing**
Integrating `awesome_bot` and `danger`: generate link report in pull request.
Close #983.

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found links issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Please only add one library per Pull Request</td>
    </tr>
  </tbody>
</table>

### Awesome_bot found issues

Line | Status | Link
| --- | --- | --- |
18 | 301 | http://twitter.com/awesome_ios | -1 | https://www.rephrase.io | -1 | https://littlebitesofcocoa.com/

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dkhamsing** [comment]
@lfarah how does the above look?

**Comment by lfarah** [comment]
@dkhamsing it would be good to show how's the old link and how's the new link, as well as if it's a **Dupe** problem or a **Link** problem

**Comment by dkhamsing** [comment]
ok

**Comment by dkhamsing** [comment]
Hm at the moment, dupes is not reported in the test output

**Comment by lfarah** [comment]
👏 👏 👏 👏 👏 👏 👏

**Comment by dkhamsing** [comment]
@lfarah still wip 😅

**Comment by lfarah** [comment]
CI is a magical thing. Any wip you do still amazes me! hahahahahha

**Comment by dkhamsing** [comment]
ha just some scripts, you could do it

**Comment by vsouza** [comment]
WOW ❤ ❤ ❤ ❤ ❤ ❤ ❤

**Comment by dkhamsing** [comment]
Looks good enough, merging

**Comment by lfarah** [comment]
🎉🎉🎉🎉

**Pull request merged**
