### PR TITLE
Add DiffableDataSources

### PR DESCRIPTION
**Pull request by ra1028**
Add DiffableDataSources.

## Project URL

https://github.com/ra1028/DiffableDataSources

## Category

Collection View

## Description

Add DiffableDataSources that the library for backporting UITableView/UICollectionViewDiffableDataSource announced in WWDC 2019.

## Why it should be included to `awesome-ios` (mandatory)
It's awesome to be able to use the same functionality in iOS9+ as diffable datasource added in iOS13.

## Checklist

- [x] Has 50 GitHub stargazers or more
- [x] Only one project/change is in this pull request
- [x] Isn't an archived project
- [ ] Has more than one contributor
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 9 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
499 | [301](https://httpstatuses.com/301) | https://github.com/arikis/Overdrive redirects to<br>https://github.com/saidsikira/Overdrive
531 | [404](https://httpstatuses.com/404) | https://github.com/rob-nash/Records 
610 | [301](https://httpstatuses.com/301) | https://github.com/alexdrone/Dispatch redirects to<br>https://github.com/alexdrone/DispatchStore
943 | [301](https://httpstatuses.com/301) | https://github.com/kean/Yalta redirects to<br>https://github.com/kean/Align
1289 | [301](https://httpstatuses.com/301) | https://github.com/JustHTTP/Just redirects to<br>https://github.com/dduan/Just
2054 | [301](https://httpstatuses.com/301) | https://github.com/alaphao/LLSpinner redirects to<br>https://github.com/alephao/LLSpinner
2254 | [404](https://httpstatuses.com/404) | https://github.com/rob-nash/Sheet 
2569 | [404](https://httpstatuses.com/404) | https://github.com/rob-nash/Rotary 
3014 | [301](https://httpstatuses.com/301) | https://github.com/tumblr/SwiftCompilationPerformanceReporter redirects to<br>https://github.com/TumblrArchive/SwiftCompilationPerformanceReporter


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@ra1028 Can you remove emoji from the description?

**Comment by ra1028** [comment]
@vsouza 
Sure, but why do I need to delete it even though already use emojis in many descriptions?

**Comment by vsouza** [comment]
@ra1028 I'm removing in the old listed projects. So, We will no longer accept emojis in the new projects.

**Comment by ra1028** [comment]
That makes sense.

**Comment by vsouza** [comment]
@ra1028 Thanks for contributing!

**Pull request merged**
