### PR TITLE
Add BouncyLayout to "Table View / Collection View" section.

### PR DESCRIPTION
**Pull request by roberthein**
## Project URL
https://github.com/roberthein/BouncyLayout

## Description
BouncyLayout is a collection view layout that makes your cells bounce.
 
## Why it should be included to `awesome-ios` (optional)
This custom collection view layout makes any iOS app more awesome!

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 4 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1182 | [301](https://httpstatuses.com/301) | https://github.com/pvzig/SlackKit redirects to<br>https://github.com/SlackKit/SlackKit
1465 | [301](https://httpstatuses.com/301) | https://github.com/andrew8712/DCKit redirects to<br>https://github.com/agordeev/DCKit
2254 | [301](https://httpstatuses.com/301) | https://github.com/thoughtbot/liftoff redirects to<br>https://github.com/liftoffcli/liftoff
2526 | [522](https://httpstatuses.com/522) | http://rypress.com/tutorials/objective-c/index 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by roberthein** [comment]
@vsouza What do these errors mean? Should I change something?

**Comment by dkhamsing** [comment]
@roberthein dont worry about those (we'll take care of them), thank you

**Comment by roberthein** [comment]
🎉

**Pull request merged**
