### PR TITLE
Add ExpandableTableView

### PR DESCRIPTION
**Pull request by SubhiH**
Expandable TableView in swift.
## Project URL

https://github.com/SubhiH/ExpandableTableView
## Description

Expandable TableView in swift with tableViews in cells(similar to expandable ListView in Android)

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by dkhamsing** [comment]
Travis issue is unrelated ✅

**Comment by lfarah** [comment]
Hey @SubhiH, thanks for contributing to AwesomeiOS.
I really liked your lib but before we approve it on AwesomeiOS, we'd like you to [fix issue 1](https://github.com/SubhiH/ExpandableTableView/issues/1). When that is done we can approve you pool request!

Thanks 😄

**Comment by dkhamsing** [comment]
pool request now? 🏊 😁

**Comment by dkhamsing** [comment]
Let's close this
Feel free to reopen when ready

**Pull request closed without merging**
