### PR TITLE
ARKit - Placing Virtual Objects in Augmented Reality

### PR DESCRIPTION
**Pull request by ignacio-chiazzo**
Added ARKit project 

## Project URL

https://github.com/ignacio-chiazzo/ARKit

## Description

 Added ARKit project that places virtual objects on the space based off of WWDC Apple conference.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please update the Pull Request title to contain the library name</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 8 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
300 | [301](https://httpstatuses.com/301) | https://github.com/lorentey/GlueKit redirects to<br>https://github.com/attaswift/GlueKit
436 | [301](https://httpstatuses.com/301) | https://github.com/lorentey/BTree redirects to<br>https://github.com/attaswift/BTree
632 | [301](https://httpstatuses.com/301) | http://www.placekit.io/ redirects to<br>https://business.mapquest.com/products/points-of-interest-data/
726 | [301](https://httpstatuses.com/301) | https://github.com/lorentey/BigInt redirects to<br>https://github.com/attaswift/BigInt
880 | [301](https://httpstatuses.com/301) | https://github.com/immrss/SSVideoPlayer redirects to<br>https://github.com/immrss/Mango
1285 | [301](https://httpstatuses.com/301) | https://github.com/lorentey/SipHash redirects to<br>https://github.com/attaswift/SipHash
2458 | [301](https://httpstatuses.com/301) | https://github.com/lorentey/Attabench redirects to<br>https://github.com/attaswift/Attabench
2652 | [301](https://httpstatuses.com/301) | http://codewithchris.com/ redirects to<br>https://codewithchris.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ignacio-chiazzo** [comment]
@lfarah Is there any plan to update the `urls` or fix the tests?

**Comment by lfarah** [comment]
Hey @ignacio-chiazzo, don't worry about it. I'll fix it until Sunday

**Comment by lfarah** [comment]
So, what's are the differences between your project and Apple's ARKit example?

**Comment by ignacio-chiazzo** [comment]
> I'm currently traveling in NYC for the try!Swift conference

That's awesome!

Basically, the main differences are:
- Using multiple objects
- Take Screenshots
- Code Improvements
- Remove all deprecated classes
- Better usage of SceneKit

**Comment by dkhamsing** [comment]
thx @ignacio-chiazzo

**Pull request merged**
