### PR TITLE
StyleDecorator

### PR DESCRIPTION
**Pull request by dimpiax**
## Project URL
https://github.com/dimpiax/StyleDecorator

## Description
Design string simply by linking attributes to needed parts
 
## Why it should be included to `awesome-ios` (optional)
Great library

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by dimpiax** [comment]
@dkhamsing I can't resolve conflicts here because preloader shows forever.

**Comment by dkhamsing** [comment]
Not sure what you mean 
@lfarah, how does the library look

**Comment by lfarah** [comment]
@dkhamsing README is short but library definitely provides a lot of value!

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 4 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
416 | [301](https://httpstatuses.com/301) | http://developer.couchbase.com/mobile/ redirects to<br>https://developer.couchbase.com/mobile/
2425 | [503](https://httpstatuses.com/503) | https://www.amazon.com/Programming-Objective-C-6th-Developers-Library/dp/0321967607 
2428 | [503](https://httpstatuses.com/503) | https://www.amazon.com/Core-Data-iOS-Data-Driven-Applications/dp/0321670426 
2429 | [503](https://httpstatuses.com/503) | https://www.amazon.com/Cocoa-Design-Patterns-Erik-Buck/dp/0321535022 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dimpiax** [comment]
@lfarah so what is the issue?

**Comment by dimpiax** [comment]
@lfarah so what is the issue?

**Comment by dkhamsing** [comment]
No issue, thx

**Pull request merged**
