### PR TITLE
Added RainyRefreshControl

### PR DESCRIPTION
**Pull request by onix-dolzhenko**
## Project URL
https://github.com/Onix-Systems/RainyRefreshControl

## Description
Simple refresh control for iOS based on POP, SpriteKit and Core Graphics inspired by [concept](https://dribbble.com/shots/2242263--1-Pull-to-refresh-Freebie-Weather-Concept).
 
## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1041 | [301](https://httpstatuses.com/301) | https://moltin.com/ios-ecommerce-sdk/ redirects to<br>https://www.moltin.com/ios-ecommerce-sdk/
2378 | [301](https://httpstatuses.com/301) | https://framerjs.com/ redirects to<br>https://framer.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Hey @onix-dolzhenko, thanks for contributing to AwesomeiOS! 👍 

Before I can merge your PR, I need you to fix [this issue](https://github.com/Onix-Systems/RainyRefreshControl/issues/15)

**Comment by onix-dolzhenko** [comment]
@lfarah done

**Comment by dkhamsing** [comment]
Thank you for contributing to `awesome-ios` 😄

**Pull request merged**
