### PR TITLE
Adding SkyFloatingLabelTextField.

### PR DESCRIPTION
**Pull request by gergelyorosz**
## Project URL
https://github.com/Skyscanner/SkyFloatingLabelTextField

## Description
Added SkyFloatingLabelTextField

## Checklist

- [x] Only one project is in the request
- [ ] `Travis CI` pass
- [x] Supports iOS 7 and later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by dkhamsing** [comment]
@gergelyorosz this project is already added under `TextField`, will fix some formatting issue

**Comment by gergelyorosz** [comment]
@dkhamsing you're completely right - I did not realize someone else added it! Thanks very much :+1:

**Comment by lfarah** [comment]
@gergelyorosz did you work on this library? I took a look and it is amazingly easy to implement and the results are beautiful. I'll definitely use on my [new open source swift game](http://github.com/lfarah/mynz)

**Comment by gergelyorosz** [comment]
@lfarah thanks! I was one of the people working on it - most of the legwork was done by @intonarumori, and design by @mds. Glad it works well for you - and keeping an eye out for your new game, good luck!

**Pull request closed without merging**
