### PR TITLE
Added Xcode plugin for localization in Plugin section

### PR DESCRIPTION
**Pull request by aashishtamsya**
## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] `Travis CI` pass
- [x] Supports iOS 7 or later
- [ ] Has a commit from less than 2 years ago
- [ ] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @aashishtamsya, thanks for the contribution! 😄
The only problem is that you have to skip a line between Dash and our **Themes** section because this happened: 
screen shot 2016-07-20 at 10 36 54 am
Also for next time, please send just one library per pull request.

**Comment by aashishtamsya** [comment]
Sry for that mistake, I will make sure that doesn't happen next time 😄

Kind Regards,
Aashish Tamsya

**Comment by lfarah** [comment]
Hey @aashishtamsya, I still need you to rebase and add a line before **Theme**

**Comment by aashishtamsya** [comment]
Sure I will do that. 😊👍

**Comment by lfarah** [comment]
Sorry but there are still conflicts and you need to do a **rebase**

**Pull request closed without merging**
