### PR TITLE
Add Swift-VIPER-Module

### PR DESCRIPTION
**Pull request by Juanpe**
## Project URL
https://github.com/Juanpe/Swift-VIPER-Module

## Description
Xcode template for VIPER Architecture in Swift
 
## Why it should be included to `awesome-ios` (optional)
When you decide to use VIPER architecture in your project, it is very tired create new modules, because you need create at least 5 files for each. Imagine that you need to create 6 modules...I was suffering this problem, and this is the raison why I've created this template. It's very useful for me and I hope that for you too.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1312 | [404](https://httpstatuses.com/404) | https://github.com/rob-nash/Fetcher 
2166 | Error | http://alcatraz.io/ <br> getaddrinfo: Temporary failure in name resolution


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Juanpe** [comment]
Hi, this error is out of my control. How I can do to publish my library?

Thanks

**Comment by miguelarauj1o** [comment]
Please, rebase with master.

**Comment by lfarah** [comment]
Wow, this template is awesome. Definitely good for both people who are learning about VIPER and people who want to create new files faster 🚀🚀🚀

**Pull request merged**
