### PR TITLE
Add GraphLayout

### PR DESCRIPTION
**Pull request by bakhtiyork**
Adding GraphLayout to ~~"Table View / Collection View"~~ Graphics

## Project URL
https://github.com/bakhtiyork/GraphLayout

## Category
~~UI -> Table View / Collection View~~ Graphics

## Description
GraphLayout - UI controls for graph visualization.
 
## Why it should be included to `awesome-ios` (optional)
There is no open source alternative to it.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by vsouza** [comment]
I'm not sure about this project on 'Table View/ Collection View' category. What you think guys?

**Comment by victorgama** [comment]
I'd say `Charts` or `Graphics`. 🤔

**Comment by vsouza** [comment]
@victorgama I vote `Graphics`

**Comment by victorgama** [comment]
@vsouza LGTM

**Comment by vsouza** [comment]
@bakhtiyork  Please move the project to `Graphic` category.

**Comment by bakhtiyork** [comment]
@vsouza Done.

**Comment by lfarah** [comment]
Thanks for contributing 👍

**Pull request merged**
