### PR TITLE
add DDDKit

### PR DESCRIPTION
**Pull request by gsabran**
## Project URL
https://github.com/gsabran/DDDKit

## Description
DDDKit is an alternative to SceneKit that is buggy and not opened source. There is a number of issues with video rendering in SceneKit that make it a not viable option (memory leak etc). DDDKit supports the core functionalities of 3D rendering (Scenes, objects, shaders etc) and has a focus on supporting video media for application in 360 videos.
As a bonus, it's very easy to apply image filter on the video!
 
## Why it should be included to `awesome-ios` (optional)
- 360 video is a growing media and we need a pure Swift solution
- people doing 3D animation might enjoy an open source framework to create 3D scenes

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @gsabran, thanks for contributing! I just need you to fix the issue above and add a line below your lib.

**Comment by gsabran** [comment]
Thanks. All done

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2136 | [301](https://httpstatuses.com/301) | https://github.com/krzysztofzablocki/Insanity redirects to<br>https://github.com/krzysztofzablocki/Sourcery


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Thanks, @gsabran!

**Pull request merged**
