### PR TITLE
Add ReduxSwift

### PR DESCRIPTION
**Pull request by lsunsi**
## Project URL
https://github.com/lsunsi/ReduxSwift

## Description
Added a new package to the Reactive Programming session: ReduxSwift.
It is an Redux implementation that leverages Swift's type safety and coolness instead of trying to get around it. It is also really minimal and extensible.

Note: It seems like my editor removed a trailing whitespace unrelated to my addition.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 3 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
379 | [301](https://httpstatuses.com/301) | https://github.com/hyperoslo/Sync redirects to<br>https://github.com/SyncDB/Sync
387 | [301](https://httpstatuses.com/301) | https://github.com/3lvis/DATAStack redirects to<br>https://github.com/SyncDB/DATAStack
1629 | [301](https://httpstatuses.com/301) | https://github.com/Binur/SubscriptionPrompt redirects to<br>https://github.com/binchik/SubscriptionPrompt


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lsunsi** [comment]
These link issues seem to be unrelated to my changes.

**Comment by lfarah** [comment]
Hey @lsunsi, nice lib
Can you [fix this issue](https://github.com/lsunsi/ReduxSwift/issues/4) before I approve your commit?

Thanks! 😄

**Comment by lsunsi** [comment]
@lfarah All done man. README updated and issue closed. (:

**Comment by lfarah** [comment]
Really thanks for the contribution, @lsunsi! 🎉

**Pull request merged**
