### PR TITLE
Added SwifterSwift to Utility

### PR DESCRIPTION
**Pull request by omaralbeik**
Added SwifterSwift to Utility

## Project URL
https://github.com/omaralbeik/SwifterSwift

## Description
A handy collection of more than 290 native Swift 3 extensions to boost your productivity.
 
## Why it should be included to `awesome-ios` (optional)
Swifter Swift is a library of over 290 properties and methods, designed to extend Swift's functionality and productivity, staying faithful to the original design guidelines of swift 3.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
987 | [301](https://httpstatuses.com/301) | https://github.com/alvinvarghese/EasyIAPs redirects to<br>https://github.com/aaalveee/EasyIAPs
1027 | [503](https://httpstatuses.com/503) | https://boxcar.io 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dkhamsing** [comment]
Hey
You're missing the Swift marker :)

**Comment by dkhamsing** [comment]
🔶

**Comment by omaralbeik** [comment]
@dkhamsing sorry, I added it

**Comment by dkhamsing** [comment]
Thx!

**Pull request merged**
