### PR TITLE
Added the CloudRail SI library & a new library category

### PR DESCRIPTION
**Pull request by felixkm**
## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

Added the new iOS version of the CloudRail SI library which provides an abstraction layer across multiple provider APIs. Due to the fact that it doesn't fit well into any existing category, I created a new one (API Integrations).

### CODE REVIEW

**Comment by vsouza** [comment]
@felixkm We already have a category for SDK. Move it to please. thanks 😄

**Comment by felixkm** [comment]
@vsouza thanks for your answer. Does that really fit into this category? There are just SDKs to integrate the services natively but nothing with an abstraction. The whole point of the library is to bundle multiple APIs into one. As I said, not sure. If you tell me to better move it into the SDK section, I'll do it.

**Comment by dkhamsing** [comment]
sdk seems fine

**Comment by felixkm** [comment]
Moved it to the SDK section. Hope I did the changes in the right way. Thanks everyone for the comments.

**Comment by dkhamsing** [comment]
thx!

**Comment by lfarah** [comment]
Good job guys! 😃

**Pull request merged**
