### PR TITLE
Add Caffe2

### PR DESCRIPTION
**Pull request by bryant1410**
## Project URL
https://caffe2.ai

## Description
A New Lightweight, Modular, and Scalable Deep Learning Framework. Caffe2 is optimized for mobile integrations, flexibility, easy updates, and running models on lower powered devices.

It needs iOS 10+ as it uses Metal.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [ ] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

---

*edited*

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
8 | [522](https://httpstatuses.com/522) | https://img.shields.io/badge/PRs-welcome-brightgreen.svg 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @bryant1410, please rebase your PR

**Comment by bryant1410** [comment]
rebased

**Comment by lfarah** [comment]
Thanks for contributing 👍

**Pull request merged**
