### PR TITLE
Update SDK section

### PR DESCRIPTION
**Pull request by dkhamsing**
Splits `API` section into `Official` and `Unofficial`

### CODE REVIEW

**Comment by victorgama** [comment]
Looks good! :shipit:

**Comment by victorgama** [comment]
@dkhamsing Shall we merge this? (So we can iterate other PRs by asking them to rebase their forks)

**Comment by dkhamsing** [comment]
Cool, thanks for lookin

**Comment by victorgama** [comment]
:metal:

**Pull request merged**
