### PR TITLE
Added PerfectSlackAPIClient to Networking section

### PR DESCRIPTION
**Pull request by SvenTiigi**
## Project URL
https://github.com/SvenTiigi/PerfectSlackAPIClient

## Category
Networking

## Description
A Slack API Client for the Perfect Server-Side Swift Framework
 
## Why it should be included to `awesome-ios` (optional)
PerfectSlackAPIClient is an API Client to access the Slack API from your Perfect Server Side Swift application. It is build on top of PerfectAPIClient, a network abstraction layer to perform network requests from your Perfect Server Side Swift application

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
I think this should be under [SDK/Unofficial](https://github.com/vsouza/awesome-ios#unofficial) or [/Server](https://github.com/vsouza/awesome-ios#server).

What do you think?

**Comment by naeemshaikh90** [comment]
Tough decision, I think [SDK/Unofficial](https://github.com/vsouza/awesome-ios#unofficial) would be better for this.

**Comment by SvenTiigi** [comment]
@lfarah Moved `PerfectSlackAPIClient` entry to SDK/Unofficial https://github.com/vsouza/awesome-ios/pull/2213/commits/326e30bca13e147d21c98f4a3a180fbe8ac54f71 👌

**Comment by dkhamsing** [comment]
thank you

**Pull request merged**
