### PR TITLE
added TLLayoutTransitioning

### PR DESCRIPTION
**Pull request by nschucky**
## Project URL

https://github.com/wtmoose/TLLayoutTransitioning
## Description

added TLLayoutTransitioning to Animation section
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
481 | [301](https://httpstatuses.com/301) | https://github.com/l0gg3r/LGBluetooth redirects to<br>https://github.com/LGBluetooth/LGBluetooth


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Hey @nschucky, thanks for contributing again. You've been an amazing asset for AwesomeiOS.

The only problem with this lib is that it should be under ```/Table View & Collection View```

**Comment by lfarah** [comment]
Damn, you're fast! 🚀

**Comment by dkhamsing** [comment]
@nschucky thanks a lot for your work
in future please use the following format for commits and pull requests:


Add `project_name` by `@github_username` to `section`

**Comment by nschucky** [comment]
@dkhamsing got it, thanks

**Comment by wtmoose** [comment]
@nschucky you literally posted this pull request (for my library) while I was posting a pull request for my new library SwiftMessages. Weird.

**Pull request merged**
