### PR TITLE
Add SonogramView

### PR DESCRIPTION
**Pull request by Luccifer**
## Project URL
https://github.com/Luccifer/SonogramView

## Description
Audio visualisation of song
 
## Why it should be included to `awesome-ios` (optional)
No other libs to get audio-visualization

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2651 | [301](https://httpstatuses.com/301) | http://codewithchris.com/ redirects to<br>https://codewithchris.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @Luccifer, please fix the issue above before we can merge your PR

**Comment by Luccifer** [comment]
It was not actually my fault, but ok, no problem!

**Comment by miguelarauj1o** [comment]
Hey @Luccifer, the problem is we cann't allow more than one commit per PR.
As we can see, your PR has three commits.
Also, you made changes not related to **SonogramView**. Please, make them in another PR.

**Pull request closed without merging**
