### PR TITLE
Add SCrypto

### PR DESCRIPTION
**Pull request by sgl0v**
## Project URL
https://github.com/sgl0v/SCrypto

## Description
Elegant Swift interface to access the CommonCrypto routines.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
@dkhamsing does he need to rebase?

**Comment by dkhamsing** [comment]
Uh looks ok now

**Comment by sgl0v** [comment]
I used Atom to edit the `README.md` file. Looks like it changed couple of lines automatically (removed trailing whitespaces). Fixed.

**Comment by lfarah** [comment]
Thanks for contributing, @sgl0v!

**Pull request merged**
