### PR TITLE
Added UnsupportedOSVersionAlert to Utility

### PR DESCRIPTION
**Pull request by caloon**
## Project URL

https://github.com/caloon/UnsupportedOSVersionAlert

## Description

Alerts users with a popup if they use an app with an unsupported version of iOS (e.g. iOS betas). Closed old, incorrect pull request and opened new one. Hope it's correct this time.

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

Forked the wrong file beforehand. Closed the old pull request and opened this new one. Hope it fits.

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @caloon, I really liked your lib. Opened a few issues there too.
For me to approve it into AwesomeiOS, I'm gonna need you to finish [issue 4](https://github.com/caloon/UnsupportedOSVersionAlert/issues/4) so your project can have a clear ```README.md```.

Thanks for contributing 😄

**Comment by caloon** [comment]
Thanks for your feedback. I'll look into the issues later today and report back as soon as I'm done.

**Comment by caloon** [comment]
3 of the 4 issues are corrected (including issue #4).

**Comment by lfarah** [comment]
Awesome. Thanks @caloon 😄

**Pull request merged**
