### PR TITLE
Added: passlock/Vault, removed: deleted repo

### PR DESCRIPTION
**Pull request by projectvim**
## Project URL

https://github.com/passlock/Vault

## Category

Security

## Description

Safe place for your encryption keys.

## Why it should be included to `awesome-ios` (mandatory)
Managing encryption keys is always tricky. This lib makes it really easy to do so.
Since this code comes from [Passlock](https://passlock.io/), it is already tested in production.

## Checklist

- [x] Isn't an archived project
- [ ] Has 50 GitHub stargazers or more
- [ ] Only one project/change is in this pull request
- [ ] Has more than one contributor
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by vsouza** [comment]
@projectvim the deleted repository was yours?

**Comment by projectvim** [comment]
No. Repo was deleted and unvailable.

**Comment by lfarah** [comment]
Hey @projectvim, thanks for contributing! Please update the PR description with the correct info. I also opened an issue on `Vault` that needs to be fixed before we merge this PR.

Let me know if you need any help!

**Comment by projectvim** [comment]
Thanks @lfarah. Fixed.

**Comment by lfarah** [comment]
@projectvim awesome work 👍

**Comment by lfarah** [comment]
@projectvim I also updated your PR description with Passlock's info. Let me know if you have anything else to add

**Comment by projectvim** [comment]
@lfarah Thanks. Nice done.

**Comment by dkhamsing** [comment]
Thx everyone!

**Comment by dkhamsing** [comment]
hi @lfarah how are we using the `waiting manager` label?

**Pull request merged**
