### PR TITLE
Add NxEnabled

### PR DESCRIPTION
**Pull request by Otbivnoe**
## NxEnabled

https://github.com/Otbivnoe/NxEnabled

## Description
Library which allows you binding `enabled` property of button with textable elements (TextView, TextField)

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1038 | [301](https://httpstatuses.com/301) | https://tapglue.github.io/ redirects to<br>http://www.tapglue.com/
2207 | [301](https://httpstatuses.com/301) | https://github.com/s4cha/AssetChecker redirects to<br>https://github.com/freshOS/AssetChecker


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @Otbivnoe, nice lib 👍 
Also... do you have Twitter? I wanted to talk to you about adding ```NxEnabled``` to this week's AwesomeiOS.Weekly

**Comment by lfarah** [comment]
Also..... please move the lib to [/TextField & TextView](https://github.com/vsouza/awesome-ios#textfield--textview)

**Comment by Otbivnoe** [comment]
@lfarah No, I haven't. I'm not so good tweet-writer :) But I can create the account if needed

**Comment by lfarah** [comment]
@Otbivnoe no problem! Just sent you an email 😉

**Pull request merged**
