### PR TITLE
Add HTMLKit

### PR DESCRIPTION
**Pull request by iabudiab**
## Project URL
https://github.com/iabudiab/HTMLKit

## Description
An Objective-C framework for your everyday HTML needs.

HTMLKit is a [WHATWG specification](https://html.spec.whatwg.org/multipage/)-compliant framework for parsing and serializing HTML documents and document fragments for iOS and OSX. HTMLKit parses real-world HTML the same way modern web browsers would.

HTMLKit provides a rich DOM implementation for manipulating and navigating the document tree. It also understands [CSS3 selectors](http://www.w3.org/TR/css3-selectors/) making node-selection and querying the DOM a piece of cake.

## Checklist
- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 8 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Hey @iabudiab, great library!

Thanks for the contribution 😄

**Comment by iabudiab** [comment]
Hey @lfarah just letting you know, that I screwed it up a bit with this PR, it had two commits instead of just one. You see, after I made the PR I have pushed yet another commit to master with another project that I wanted to contribute. I guess you haven't noticed it either. Feel free to remove the other one (ObjectiveRocks) if you don't like it. 
Sorry for that...

**Comment by dkhamsing** [comment]
@iabudiab should be ok
thx

**Comment by lfarah** [comment]
I'm at WWDC so I was quickly looking through the PR before accepting... but no problem. Thanks for letting us know 😉

**Pull request merged**
