### PR TITLE
Added “twitter-kit-ios” library

### PR DESCRIPTION
**Pull request by Yogesh-MV**
## Project URL

https://github.com/twitter/twitter-kit-ios
## Category

Tools
## Description

 Twitter Kit is a native SDK to include Twitter content inside mobile apps.
## Checklist

- [X] Only one project/change is in this pull request
- [X] Addition in chronological order (bottom of category)
- [ ] Supports iOS 9 / tvOS 10 or later
- [ ] Supports Swift 4 or later
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
736 | [301](https://httpstatuses.com/301) | https://github.com/knly/Evergreen redirects to<br>https://github.com/nilsleiffischer/Evergreen
2879 | [404](https://httpstatuses.com/404) | https://www.manning.com/books/ios-development-with-swift 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by arasu01** [comment]
It must be under SDK -> Official. What do you think @dkhamsing, @lfarah and @vsouza ?

**Comment by lfarah** [comment]
Yup, you're correct @arasu01

**Comment by Yogesh-MV** [comment]
Updated the request as @arasu01 mentioned

**Comment by arasu01** [comment]
Thanks for the quick changes @Yogesh-MV.

**Comment by lfarah** [comment]
Good job guys! 👍

**Pull request merged**
