### PR TITLE
Add mixpanel-swift

### PR DESCRIPTION
**Pull request by serhii-londar**
Add mixpanel-swift

## Project URL
https://github.com/mixpanel/mixpanel-swift

## Category
[SDK/Official](https://github.com/vsouza/awesome-ios#official)

## Description
Mixpanel tracking library for iOS (Swift) 
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by arasu01** [comment]
We have mixpanel already listed under analytics section and it's of more than enough. So I vote to close this PR.

**Comment by vsouza** [comment]
@arasu01 actually we have only the link to MixPanel website in `Analytics` section. Maybe we can add this project on `SDK` category, and keep both projects, or remove the link on analytics category.

I vote for keep both projects. I don't see any problem with this. What u think?

**Comment by serhii-londar** [comment]
@vsouza I agree with you.

**Comment by lfarah** [comment]
I agree with @arasu01. I think we can leave it only under analytics

**Comment by vsouza** [comment]
I'll close this PR for now. I'm planning to organize some sections and I've added on my personal list a task to organize SDK section.

**Pull request closed without merging**
