### PR TITLE
Adds Reference category w/ cheat sheets

### PR DESCRIPTION
**Pull request by iwasrobbed**
## Project URL
https://github.com/iwasrobbed/Swift-CheatSheet
https://github.com/iwasrobbed/Objective-C-CheatSheet

## Description
Cheat sheets for Swift and Objective-C

## Checklist
- [x] Only one project / new category is in the request
- [x] Addition in chronological order (bottom of category)
- [x] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
@vsouza  @dkhamsing what do you guys think?

**Comment by dkhamsing** [comment]
Somewhere in good websites ?

**Comment by vsouza** [comment]
I think CheatSheet should be together with Style Guides. IMHO

**Comment by iwasrobbed** [comment]
They aren't really style guides since they showcase design patterns and operators moreso than code formatting. Either way, just wanted to get the conversation started and will let you all decide 👍

**Comment by vsouza** [comment]
@iwasrobbed my ideia was put CheatSheet as a subcategory of Style Guides. Not be together.

**Comment by dkhamsing** [comment]
How about a category named `Reference`

**Comment by vsouza** [comment]
@dkhamsing good idea

**Comment by vsouza** [comment]
what u think @lfarah  ?

**Comment by lfarah** [comment]
Sure!

**Comment by iwasrobbed** [comment]
@dkhamsing Renamed to `Reference` 👍

**Comment by dkhamsing** [comment]
Looks good!

**Comment by vsouza** [comment]
thanks guys ❤️

**Pull request merged**
