### PR TITLE
Update sponsorship listing

### PR DESCRIPTION
**Pull request by azamzamy**
Update Instabug sponsorship listing
• Modify content
• Modify picture
• Modify URL

### CODE REVIEW

**Comment by azamzamy** [comment]
@vsouza Hi Vinicius, Thanks for updating Instabug's listing. I was about to get in touch with you regarding that.

Thanks, 🙏

**Comment by vsouza** [comment]
@azamzamy Can we merge?

**Comment by azamzamy** [comment]
@vsouza Yes, please.

**Comment by vsouza** [comment]
Thanks @azamzamy

**Pull request merged**
