### PR TITLE
add NoticeObserveKit by @marty-suzuki

### PR DESCRIPTION
**Pull request by marty-suzuki**
## Project URL

https://github.com/marty-suzuki/NoticeObserveKit

## Description

NoticeObserveKit is type-safe NotificationCenter wrapper that associates notice type with info type.
 
## Why it should be included to `awesome-ios` (optional)
It provides a simpler syntax for working with NotificationCenter.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1039 | [301](https://httpstatuses.com/301) | https://tapglue.github.io/ redirects to<br>http://www.tapglue.com/
2207 | [301](https://httpstatuses.com/301) | https://github.com/s4cha/AssetChecker redirects to<br>https://github.com/freshOS/AssetChecker


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by hklcorp** [comment]
Cool lib and nice readme!

Thanks for contributing! 👍

**Comment by lfarah** [comment]
Cool lib and nice ```README```!

Thanks for contributing! 👍

**Comment by marty-suzuki** [comment]
Thank you!

**Pull request merged**
