### PR TITLE
Login section under ui

### PR DESCRIPTION
**Pull request by serhii-londar**
Create new Login subsection under UI section according to [Login section under UI #1047](https://github.com/vsouza/awesome-ios/issues/1047).

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 3 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
854 | [301](https://httpstatuses.com/301) | https://github.com/terflogag/FacebookImagePicker redirects to<br>https://github.com/floriangbh/FacebookImagePicker
1355 | [301](https://httpstatuses.com/301) | https://github.com/SwiftOnEdge/Edge redirects to<br>https://github.com/skylab-inc/Edge
2389 | [301](https://httpstatuses.com/301) | https://github.com/terflogag/OpenSourceController redirects to<br>https://github.com/floriangbh/OpenSourceController


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @serhii-londar, thank you so much for doing this! Please add it to the contents section, under [Label](https://github.com/vsouza/awesome-ios#label)

**Comment by serhii-londar** [comment]
@lfarah Just added.

**Comment by lfarah** [comment]
Thanks! 🎉

**Pull request merged**
