### PR TITLE
Added Playground for Dijkstra's Algorithm

### PR DESCRIPTION
**Pull request by theindiandev1065**
## Project URL

https://github.com/theindiandev1065/Djikastra-s-Algorithm
## Description

 I have added a playground which links to how to implement Dijkstra's Algorithm in Swift. This is an important algorithm for finding the shortest path!
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 3 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
521 | [301](https://httpstatuses.com/301) | https://github.com/bwide/BWCollectionView redirects to<br>https://github.com/bwide/CollectionNode
2764 | [301](https://httpstatuses.com/301) | http://www.coreint.org/ redirects to<br>http://coreint.org/
2778 | Error | https://www.mikeash.com/book.html <br> Cannot assign requested address - connect(2) for "www.mikeash.com" port 443


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
@dkhamsing @vsouza What do you guys think? I've read his blog posts [[1]](https://medium.com/swiftly-swift/dijkstras-algorithm-in-swift-15dce3ed0e22) [[2]](https://medium.com/swiftly-swift/the-right-way-to-write-dijkstras-algorithm-in-swift-abb14ce66b00) and it is pretty interesting, but it is still not a library

**Comment by theindiandev1065** [comment]
True but according to the description of awesome-ios, it’s a collection of tutorials, libraries, and more

**Comment by lfarah** [comment]
@theindiandev1065 when we talk about tutorials, we mostly talk about resources that have many tutorials(Check [Getting Started](https://github.com/vsouza/awesome-ios#getting-started) section for example), and not a single one. I understand the value of what you made and I think it's awesome, but if we accept single tutorials, this list would be too big

**Comment by theindiandev1065** [comment]
I see what you mean. I just thought I should add it since the category is lacking a lot so I thought I could add Dijkstra’s Algorithm. But it’s all up to you! 🤗

**Comment by dkhamsing** [comment]
Closing on recommendation from @lfarah 
Thanks

**Pull request closed without merging**
