### PR TITLE
Add Monaka

### PR DESCRIPTION
**Pull request by naru-jpn**
Add Monaka to Data Structures / Algorithms

## Project URL
https://github.com/naru-jpn/Monaka

## Description
Convert custom struct and fundamental values to NSData.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
639 | [301](https://httpstatuses.com/301) | https://github.com/comyarzaheri/TuningFork redirects to<br>https://github.com/comyar/TuningFork


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
@dkhamsing what do you think? I think it fits more under ```/Core Data```

**Comment by dkhamsing** [comment]
@lfarah submitted category is fine

**Comment by dkhamsing** [comment]
merging

**Comment by dkhamsing** [comment]
@naru-jpn 
Thank you for contributing to `awesome-ios` 😄

**Pull request merged**
