### PR TITLE
Added KVOController from @facebook

### PR DESCRIPTION
**Pull request by Mylittleswift**
## Project URL

https://github.com/facebook/KVOController
## Category

Code quality
## Description

 Simple, modern, thread-safe key-value observing for iOS and OS X.  KVOController builds on Cocoa's time-tested key-value observing implementation. It offers a simple, modern API, that is also thread safe. Benefits include:
- Notification using blocks, custom actions, or NSKeyValueObserving callback.
- No exceptions on observer removal.
- Implicit observer removal on controller dealloc.
- Thread-safety with special guards against observer resurrection.
## Why it should be included to `awesome-ios` (optional)
Better than native Objective-C KVO. >6000 stars at Github.
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
5 | Dupe | https://gitter.im/vsouza/awesome-ios 
2686 | [503](https://httpstatuses.com/503) | https://boombox.io/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
Hi @Mylittleswift thanks for PR. We already have a discussion about this project, We don't have a right category for this and we are in trouble to figure out which category this project belongs to.

If you want to help us, you'll be welcome. For now I'll mark this PR as a discussion before merge this, ok?

**Comment by Mylittleswift** [comment]
@vsouza understood and agreed.

**Comment by dkhamsing** [comment]
Let's continue the discussion in #997

Thank you @Mylittleswift

**Pull request closed without merging**
