### PR TITLE
Added Cluster

### PR DESCRIPTION
**Pull request by efremidze**
## Project URL

https://github.com/efremidze/Cluster

## Description

Added a map annotation clustering library. It helps add clustering to any MKMapView.
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 3 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1180 | [301](https://httpstatuses.com/301) | https://github.com/pvzig/SlackKit redirects to<br>https://github.com/SlackKit/SlackKit
1463 | [301](https://httpstatuses.com/301) | https://github.com/andrew8712/DCKit redirects to<br>https://github.com/agordeev/DCKit
2523 | [522](https://httpstatuses.com/522) | http://rypress.com/tutorials/objective-c/index 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by efremidze** [comment]
IDK what I'm supposed to do to fix this. Those are errors with other libraries.

**Comment by dkhamsing** [comment]
yeah dont worry about it
thx

**Comment by dkhamsing** [comment]
thx

**Pull request merged**
