### PR TITLE
Add StoryboardBuilder

### PR DESCRIPTION
**Pull request by hiro-nagami**
## Project URL
https://github.com/hiro-nagami/StoryboardBuilder

## Category
Injection

## Description
Simple dependency injection for generating views from storyboard.

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1380 | [404](https://httpstatuses.com/404) | https://github.com/aaalveee/EasyIAPs 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by vsouza** [comment]
@hiro-nagami before we can merge, I need you to fill in the `Description` section on your repository. Thank you.

**Comment by hiro-nagami** [comment]
@vsouza Thank you for comments. I added `Description` section on README.md.

**Comment by vsouza** [comment]
@hiro-nagami  I meant the description on top of your repository:

screen shot 2018-05-21 at 2 03 15 pm

I'll merge, then you can add the description later. No problem.

Thank you ❤️

**Comment by hiro-nagami** [comment]
Oh, I will add it soon. Thank you :)

**Pull request merged**
