### PR TITLE
Add Applozic iOS Chat SDK

### PR DESCRIPTION
**Pull request by devashishmamgain**
## Project URL

https://github.com/AppLozic/Applozic-iOS-SDK

## Category
Messaging

## Description

Open source iOS Chat and Messaging SDK that lets you add real time messaging in your mobile (android, iOS) applications and website.
 
## Why it should be included to `awesome-ios` (optional)
Applozic iOS Chat SDK is being used by 300+ companies.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2182 | [301](https://httpstatuses.com/301) | https://github.com/saeid/GDPersianCalendar redirects to<br>https://github.com/saeid/GDCalendar


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by devashishmamgain** [comment]
@vsouza went through the error details, it is pointing to some existing library listing:
  1. [L2182] 301 https://github.com/saeid/GDPersianCalendar  → https://github.com/saeid/GDCalendar 

Shall i change the existing entry mapping?

**Comment by devashishmamgain** [comment]
@vsouza changed https://github.com/saeid/GDPersianCalendar  to https://github.com/saeid/GDCalendar

**Comment by vsouza** [comment]
@devashishmamgain I was talking about the unit tests or integration tests in the project that you sent.  Our new contribution guidelines are avoiding projects without tests.

**Comment by devashishmamgain** [comment]
@vsouza got it

**Comment by devashishmamgain** [comment]
@vsouza pls check now

**Comment by vsouza** [comment]
@devashishmamgain The other project is a UI project, with a different category and still don't have tests.
I'll close this PR for now, because the two projects are ineligible, feel free to open a new a pull request when projects fit on our contribution guidelines. Thank you

**Comment by mukeshthawani** [comment]
@vsouza Tests are present in the demo folder: https://github.com/AppLozic/ApplozicSwift/tree/master/Demo/ApplozicSwiftDemoTests

And the category is messaging only. It's a messaging UI kit similar to [MessageKit](https://github.com/MessageKit/MessageKit) which is also present in the Messaging category.

Thank you

**Pull request closed without merging**
