### PR TITLE
MFCard

### PR DESCRIPTION
**Pull request by arpandesai**
Easily integrate Credit Card payments in iOS App

MFCard
https://github.com/MobileFirstInc/MFCard

Description
Easily integrate Credit Card payments in iOS App
 
## Why it should be included to `awesome-ios` (optional)
MFCard is an awesome looking Credit Card input & validation control. You can easily customize UI according to project design
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by arpandesai** [comment]
MFCard is an awesome looking Credit Card input & validation control

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
416 | [301](https://httpstatuses.com/301) | http://developer.couchbase.com/mobile/ redirects to<br>https://developer.couchbase.com/mobile/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by arpandesai** [comment]
Added :large_orange_diamond: for Swift identification.

**Comment by lfarah** [comment]
@arpandesai why did you close it? I really liked your lib 😢

**Comment by lfarah** [comment]
@arpandesai don't worry about the CI Error. We use travis to know when a link is broken or is redirecting, but that's for the managers to fix it and not the external contributors.

Thanks for the ❤️  and happy New Year 🎉

**Comment by arpandesai** [comment]
Happy new year Lucas ! I will submit it shortly. 

— Arpan Desai
MobileFirst | Principal consultant
Mobile: +91 (0) 99 9875 5114
Email: arpan@mobilefirst.in <mailto:arpan@mobilefirst.in>
MobileFirst Applications Private Limited

43, JMC House, Opp. Parimal Garden,
Ambawadi, Ahmedabad - 380006

http://mobilefirst.in <http://mobilefirst.in/>
http://facebook.com/mobilefirst <http://facebook.com/mobilefirst>
@ MobileFirst <http://twitter.com/mobilefirstinc>

**Pull request closed without merging**
