### PR TITLE
Added Feeds for iOS Developer

### PR DESCRIPTION
**Pull request by rgnlax**
## Project URL
https://github.com/rgnlax/Feeds-for-iOS-Developer

## Description
Added a "Feeds for iOS Developer" under "Good Websites" as you suggest before.

## Checklist
- [X] Only one project is in this pull request
- [X] Addition in chronological order (bottom of category)
- [ ] `Travis CI` pass
- [ ] Supports iOS 7 or later
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
hey @rgnlax, I think it's not necessary to add it in a new section since a lot of the feeds you present on your list, like the one from Natasha the Robot, are already inside [News, Blocks and More](https://github.com/vsouza/awesome-ios#news-blogs-and-more), so you could add your lib under there 😉

**Comment by rgnlax** [comment]
Updated

**Comment by rgnlax** [comment]
## Project URL
https://github.com/rgnlax/Feeds-for-iOS-Developer

## Description
Added a "Feeds for iOS Developer" under "Good Websites" as you suggest before.

## Checklist
- [X] Only one project is in this pull request
- [X] Addition in chronological order (bottom of category)
- [ ] `Travis CI` pass
- [ ] Supports iOS 7 or later
- [X] Has a commit from less than 2 years ago
- [X] Has a **clear** README in English

**Comment by lfarah** [comment]
Awesome! Thanks for contributing 😄

**Comment by lfarah** [comment]
Oh now there are conflicts. Please rebase

**Comment by rgnlax** [comment]
Rebased!😄

**Comment by dkhamsing** [comment]
thx

**Pull request merged**
