### PR TITLE
Add CHIPageControl to Activity Indicator

### PR DESCRIPTION
**Pull request by chili-ios**
## Project URL
https://github.com/ChiliLabs/CHIPageControl

## Description
Add CHIPageControl to Activity Indicator
 
## Why it should be included to `awesome-ios` (optional)
it's awesome :)

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2209 | Error | http://alcatraz.io/ <br> getaddrinfo: Name or service not known


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by victorgama** [comment]
Hi there!
Awesome indeed! I'm in love with this component and will probably use it on my next project. 

I just need you to move it to a more suiting category, which in the case of `CHIPageControl` would be [**UI**](https://github.com/vsouza/awesome-ios#ui). We'll get this merged ASAP after you move it. 

Thank you! 🙌

**Comment by naeemshaikh90** [comment]
@chili-ios Nice lib 👌

**Comment by naeemshaikh90** [comment]
@chili-ios thanks for contributing to `awesome-ios` 🎉

**Pull request merged**
