### PR TITLE
Adds Komponents lib

### PR DESCRIPTION
**Pull request by s4cha**
## Project URL
https://github.com/freshOS/Komponents

## Description
Komponents is a Swift framework for building component-oriented interfaces ala React.
 
## Why it should be included to `awesome-ios`
Because it's unfair to need javascript to enjoy Components ! 😎
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by s4cha** [comment]
Thinking about it I really believe we can have a separate Category for **react-like** Frameworks.
Indeed they have nothing to-do with reactive programming per-se (observables etc.)
It would gather : 
- Render
- Katana
- TemplateKit 
- Komponents
Also (Few.swift, not yet on awesome-ios)
That are somewhat lost in RXExtensions at the moment :)
What do you think?

**Comment by dkhamsing** [comment]
can u open an issue with your ideas about react-like frameworks
thx

**Comment by dkhamsing** [comment]
Thank you for contributing to `awesome-ios` 😄

**Pull request merged**
