### PR TITLE
Add CDAlertView to UI/Alert Category

### PR DESCRIPTION
**Pull request by candostdagdeviren**
## Project URL
https://github.com/candostdagdeviren/CDAlertView

## Description
Highly customizable alert/notification/success/error/alarm popup written in Swift 3

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 3 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1016 | [502](https://httpstatuses.com/502) | https://boxcar.io 
1586 | [301](https://httpstatuses.com/301) | https://github.com/recisio/IncrementableLabel redirects to<br>https://github.com/tbaranes/IncrementableLabel
2204 | [500](https://httpstatuses.com/500) | https://code.facebook.com/ios/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by candostdagdeviren** [comment]
Why these issues occured? Does anyone have an idea?

**Comment by lfarah** [comment]
@candostdagdeviren we have Travis checking all the URLs and if someone changes their name on Github, the url has a redirect so we have to update on AwesomeiOS.

Don't worry about it because I'll look into it

Thanks for contributing to AwesomeiOS and good job on the lib! 😄 👍

**Comment by candostdagdeviren** [comment]
@lfarah Thank you!

**Pull request merged**
