### PR TITLE
Add MetovaTestKit by @metova to Other Testing section

### PR DESCRIPTION
**Pull request by nschucky**
## Project URL

https://github.com/metova/MetovaTestKit
## Description

 Add MetovaTestKit by @metova to Other Testing section
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
This is not available for Swift 3...

**Comment by lfarah** [comment]
Waiting for [this](https://github.com/metova/MetovaTestKit/issues/9) to be fixed...

**Comment by nhgrif** [comment]
I'll fix it this weekend.

**Comment by lfarah** [comment]
Thank you, @nhgrif!

**Comment by nhgrif** [comment]
MTK has now been updated in the github repository and on CocoaPods, with version 1.0.0.

**Comment by dkhamsing** [comment]
thx

**Pull request merged**
