### PR TITLE
Add PSTModernizer

### PR DESCRIPTION
**Pull request by naeemshaikh90**
## Project URL
https://github.com/PSPDFKit-labs/PSTModernizer

## Description
Makes it easier to support older versions of iOS by fixing things and adding missing methods
 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [ ] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Thank you so much, @naeemshaikh90. You've been a great help for us!

**Comment by naeemshaikh90** [comment]
@lfarah glad to help you guys! These are my first contributions to open source community. :)

**Comment by lfarah** [comment]
@naeemshaikh90 AwesomeiOS was also my first contribution to open source years ago. If you wanna dig more into open source, let me know and I can help you!😉

**Comment by naeemshaikh90** [comment]
Ya sure I am looking forward to actively contribute on open source community.

**Pull request merged**
