### PR TITLE
update in Other Awesome Lists

### PR DESCRIPTION
**Pull request by jphong1111**
update awesome list for ios developer which is contain useful stuff

## Project URL

https://github.com/jphong1111/awesome-ios-developer

## Category

Other Awesome Lists

## Description

I listed some keywords and useful stuff that can give some help for ios developers.

## Why it should be included to `awesome-ios` (mandatory)

Me and other contributors are updating everyday for this repository, but still it needs more contributors to make it more helpful for ios developer. Listed inside awesome-ios will be a great chance for it! Also, other programmers/developers can get some useful stuffs too!

## Checklist

- [x] Has 50 GitHub stargazers or more
- [x] Only one project/change is in this pull request
- [x] Isn't an archived project
- [x] Has more than one contributor
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by vsouza** [comment]
@jphong1111 Please, move the link to the end of the category.

**Comment by jphong1111** [comment]
got it!

**Comment by jphong1111** [comment]
@vsouza Done!

**Comment by vsouza** [comment]
@jphong1111 Thank you.

**Pull request merged**
