### PR TITLE
PMSuperButton

### PR DESCRIPTION
**Pull request by Codeido**
Added PMSuperButton swift project to Button category

## Project URL
https://github.com/Codeido/PMSuperButton

## Description
Added PMSuperButton swift project to Button category

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
767 | [301](https://httpstatuses.com/301) | https://github.com/zalando-incubator/MapleBacon redirects to<br>https://github.com/JanGorman/MapleBacon
994 | [301](https://httpstatuses.com/301) | http://www.netmera.com redirects to<br>https://www.netmera.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Codeido** [comment]
Each new pull request presents this inconsistency. @danger-awesome-ios

**Comment by dkhamsing** [comment]
@Codeido don't worry about that warning message
we'll take care of it, thanks

**Comment by lfarah** [comment]
@Codeido awesome to have one more library from you. Used PMAlertController in many projects!

**Pull request merged**
