### PR TITLE
Added Slope by @mergesort

### PR DESCRIPTION
**Pull request by lfarah**
## Project URL

https://github.com/mergesort/Slope

## Category

Graphics

## Description

A simpler way to implement simple gradients on iOS

## Why it should be included to `awesome-ios` (optional)
Joe has many awesome libraries and Slope is his newest.

## Checklist

- [x] Only one project/change is in this pull request
- [ ] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
Spoiler alert: Slope should be added in next week's [AwesomeiOS.Weekly](http://weekly.awesomeios.com/)

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1533 | [302](https://httpstatuses.com/302) | https://www.dropbox.com/developers redirects to<br>https://www.dropbox.com/lp/developers
3066 | Error | https://littlebitesofcocoa.com/ <br> Net::ReadTimeout


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by lfarah** [comment]
Hey @mergesort, do you think it would be useful to add some tests to Slope?

**Comment by vsouza** [comment]
@lfarah and @mergesort We cannot merge your PR yet until you write some tests for your lib. Feel free to open another PR once it is ready. Thanks, guys ❤️

**Pull request closed without merging**
