### PR TITLE
Add WCDB.

### PR DESCRIPTION
**Pull request by cwwise**
wcdb

## Project URL
https://github.com/Tencent/wcdb

## Description
WCDB is an efficient, complete, easy-to-use mobile database framework for iOS, macOS.
 
## Why it should be included to `awesome-ios` (optional)
* Easy-to-use. Through WCDB, you can get objects from database in one line code.
* Efficient. Through the framework layer and sqlcipher source optimization, WCDB have more efficient performance.

## Checklist

- [x] Only one project/change is in this pull request
- [ ] Addition in chronological order (bottom of category)
- [x ] Supports iOS 9 / tvOS 10 or later
- [ ] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks: )</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
974 | Error | http://protobuf.io/#swift <br> Connection refused - connect(2) for "protobuf.io" port 80
2422 | Error | https://iconresizer.com/ <br> Connection refused - connect(2) for "iconresizer.com" port 443


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dkhamsing** [comment]
@cwwise can u put the entry at the bottom? thanks!

**Comment by dkhamsing** [comment]
Dupe of #1894

**Comment by cwwise** [comment]
Ok.But I don't know how to change it. So I create a new pull request.You can close it.

**Pull request closed without merging**
