### PR TITLE
Adding Tapglue to build social apps

### PR DESCRIPTION
**Pull request by onurakpolat**
Adding Tapglue to build social apps

### CODE REVIEW

**Comment by victorgama** [comment]
Hmm. Looks like this should be merged into the _Products_ category, instead of creating a new one. @dkhamsing, what do you think?

**Comment by onurakpolat** [comment]
Sure, I thought it might be worth creating a new one to make social products but I guess that works ;)

**Comment by dkhamsing** [comment]
Yeah sounds ok @victorgama

**Comment by victorgama** [comment]
Great! We can merge this after @onurakpolat updates his changes. (:

**Comment by iraycd** [comment]
I guess tapglue it's similar to http://getstream.io

**Comment by dkhamsing** [comment]
@onurakpolat thx

**Pull request merged**
