### PR TITLE
Add androidtool-mac.

### PR DESCRIPTION
**Pull request by datomnurdin**

### CODE REVIEW

**Comment by vsouza** [comment]
* AndroidTool is a Mac application for Android devices, right? it is beyond the scope of this project. We are a collection of iOS ecosystem projects.
* Project Haneke Swift is required to add 🔶 flag, because it is a project in Swift :smile: 
* LibPhoneNumber project is a good project. It may well be added.

You could fix the Hanekee and remove AndroidTool project?

**Comment by dkhamsing** [comment]
Looks like this can be closed #140

**Comment by victorgama** [comment]
Not sure. It can be useful if @datomnurdin removes `AndroidTool` and fixes the conflicts.
Any thoughts, @vsouza?

**Comment by vsouza** [comment]
in PR #140 @datomnurdin added HanekeSwift.

**Comment by mortenjust** [comment]
For what it's worth, Android Tool now supports screenshots and videos. Misleading name, I know :)

**Pull request closed without merging**
