### PR TITLE
Update redirects 

### PR DESCRIPTION
**Pull request by shubh10**

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 7 link issues, a project collaborator will take care of these, thanks: )</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
8 | [522](https://httpstatuses.com/522) | https://img.shields.io/badge/PRs-welcome-brightgreen.svg 
374 | [301](https://httpstatuses.com/301) | https://github.com/SyncDB/Sync redirects to<br>https://github.com/3lvis/Sync
382 | [301](https://httpstatuses.com/301) | https://github.com/SyncDB/DATAStack redirects to<br>https://github.com/3lvis/DATAStack
899 | [404](https://httpstatuses.com/404) | https://github.com/MessageKit/MessageKit-iOS 
1650 | [301](https://httpstatuses.com/301) | https://github.com/jackyzh/awesome-ios-animation redirects to<br>https://github.com/jackymelb/awesome-ios-animation
2328 | [301](https://httpstatuses.com/301) | https://github.com/mojilala/VideoSplashKit redirects to<br>https://github.com/svtek/VideoSplashKit
2434 | Error | https://iconresizer.com/ <br> Connection refused - connect(2) for "iconresizer.com" port 443


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dkhamsing** [comment]
Thx a lot
Can you update the redirects above ??

**Comment by shubh10** [comment]
there you go. Links at 899 and 2434 doesn't seem to be working.

**Comment by shubh10** [comment]
should I also remove the projects for iconsynthesizer and messageKit. The links do not work anymore.

**Comment by dkhamsing** [comment]
No thx

**Pull request merged**
