### PR TITLE
SMNumberWheel 

### PR DESCRIPTION
**Pull request by SinaMoetakef**
Please add SMNumberWheel under UI/PickerView

I have created a CocoaPod for the custom made UI (SMNumberWheel) and would like to have it in your list. 

## Project URL
https://github.com/SinaMoetakef/SMNumberWheel respecting your contribution guidelines.

## Description
I added the link and description under UI/PickerView. 
 
## Why it should be included to `awesome-ios` (optional)
The UI component is written is swift 3.0 and supports iOS 9.0 and later. It also supports sounds and the new haptic feedback feature (iOS 10 for iPhone 7 and 7+). It is very smooth, highly customizable, renders in InterfaceBuilder, very accurate and very fast. 
The sample project demonstrating the wheel is very well done.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
757 | [301](https://httpstatuses.com/301) | https://github.com/ideaismobile/IDMPhotoBrowser redirects to<br>https://github.com/thiagoperes/IDMPhotoBrowser
1586 | [301](https://httpstatuses.com/301) | https://github.com/k9101/FCAlertView redirects to<br>https://github.com/krispenney/FCAlertView


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
I think it's better under [/Switch](https://github.com/vsouza/awesome-ios#switch).

@dkhamsing what do you think?

**Comment by dkhamsing** [comment]
How about Stepper

**Comment by lfarah** [comment]
Stepper it is. @SinaMoetakef please change to the /Stepper section 👍

**Comment by SinaMoetakef** [comment]
@lfarah 
Okay, I'm going to create another pull request under stepper.

Thanks 👍👍

**Pull request closed without merging**
