### PR TITLE
Add DKCamera by @zhangao0086 to Camera Section

### PR DESCRIPTION
**Pull request by haydenholligan**
## Project URL
https://github.com/zhangao0086/DKCamera

## Description
Add DKCamera by [@zhangao0086](https://github.com/zhangao0086) to Camera Section
## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
901 | [301](https://httpstatuses.com/301) | https://github.com/czechboy0/Jay redirects to<br>https://github.com/DanToml/Jay
1728 | [301](https://httpstatuses.com/301) | https://github.com/czechboy0/SecretSocks redirects to<br>https://github.com/czechboy0-deprecated/SecretSocks


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by haydenholligan** [comment]
I'm a little confused as to the error produced by danger-awesome-ios. I noticed it on another PR. Is this a common issue right now?

**Comment by dkhamsing** [comment]
@haydenholligan it's unrelated to your changes, don't worry about it

**Comment by lfarah** [comment]
Thanks for contributing, @haydenholligan! 😃

**Pull request merged**
