### PR TITLE
Update library description

### PR DESCRIPTION
**Pull request by miguelarauj1o**
related to #949.

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dkhamsing** [comment]
Miguel, are you finished ?

**Comment by miguelarauj1o** [comment]
Yes

**Comment by naeemshaikh90** [comment]
@miguelarauj1o Great work man 🙌🏻

**Comment by vsouza** [comment]
@miguelarauj1o  👏 👏 👏 👏 👏 👏

**Comment by lfarah** [comment]
giphy 22

**Pull request merged**
