### PR TITLE
Add Sage

### PR DESCRIPTION
**Pull request by nvzqz**
## Project URL

https://github.com/nvzqz/Sage/

## Description

Sage is a cross-platform chess library for Swift. It has been added added to a newly created Games category.

## Checklist

- [x] Only one project is in this pull request
- [x] Addition in chronological order (bottom of category)
- [ ] `Travis CI` pass
- [x] Supports iOS 7 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
@vsouza @dkhamsing what do you guys think?

**Comment by dkhamsing** [comment]
Not sure

**Comment by nvzqz** [comment]
It builds for iOS 8.0+ and tests pass on iOS.

**Comment by lfarah** [comment]
@dkhamsing me and @vsouza discussed and we think other people will like and use a chess library

**Pull request merged**
