### PR TITLE
Added PhotoEditorSDK to the list of Image Editing

### PR DESCRIPTION
**Pull request by DanielHauschildt**
## Project URL
https://www.photoeditorsdk.com

## Description
Added PhotoEditorSDK to the list of Image/Photo-Editing SDKs

## Why it should be included to `awesome-ios` (optional)
I came across your awesome-ios list and wondered if you would be so kind to enlist PhotoEditorSDK in your list. 

## Checklist
- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by DanielHauschildt** [comment]
Here is also a link to our repo 
https://github.com/imgly/pesdk-ios-build

**Comment by lfarah** [comment]
Hey @DanielHauschildt, please rebase your PR

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2241 | [301](https://httpstatuses.com/301) | https://github.com/zwaldowski/BlocksKit redirects to<br>https://github.com/BlocksKit/BlocksKit
2630 | Error | http://swiftsandbox.io <br> getaddrinfo: Name or service not known


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by DanielHauschildt** [comment]
Hey @lfarah,

I rebased it but now your automated tests fail for some reason for some other links.

**Comment by lfarah** [comment]
Hey @DanielHauschildt, thanks for contributing! 🎉

**Pull request merged**
