### PR TITLE
Add Ebblink SDK

### PR DESCRIPTION
**Pull request by AO2666**
Request to add the _Ebblink SDK_ under _Messaging_

## Project URL

[https://github.com/ebbapp/ebblinkSDK](https://github.com/ebbapp/ebblinkSDK)
[http://http://www.fiveopenbooks.com/](http://www.fiveopenbooks.com/)

## Description

The ebblink SDK makes it possible to share photos that expire automatically (after a customizable period of time has elapsed). These photos can be removed anytime. Photos are encrypted and stored in our servers and can only be accessed by intended recipients (as long as the photos have not expired or have not been removed). A URL or deeplink to these shared images is provided back by the SDK. These links can be shared within a messaging app or posted on social networks. Developers can choose to have a password generated for each photo (so that the URL and the password have to be shared separately) or to embed the password in the URL. 

## Why it should be included to `awesome-ios` (optional)

Encrypted photos with expiration time enhance photo sharing privacy and can be useful in a number of applications, such as messaging, posting on social networks, etc. 

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 3 link issues</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
453 | [301](https://httpstatuses.com/301) | http://www.dollarswift.org redirects to<br>https://www.dollarswift.org/
1043 | [301](https://httpstatuses.com/301) | https://moltin.com/ios-ecommerce-sdk/ redirects to<br>https://www.moltin.com/ios-ecommerce-sdk/
2380 | [301](https://httpstatuses.com/301) | https://framerjs.com/ redirects to<br>https://framer.com/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
Hey @AO2666, thanks for contributing! 👍 

I think your lib is better under [/Image](https://github.com/vsouza/awesome-ios#image).
Also, could you please remove that extra line?

**Comment by AO2666** [comment]
I moved to Image, also removed the extra line

**Comment by AO2666** [comment]
I moved it to Image and removed the extra line.

Thanks!

**Comment by dkhamsing** [comment]
Thank you for contributing to `awesome-ios` 😄

**Pull request merged**
