### PR TITLE
Added StatusBarOverlay

### PR DESCRIPTION
**Pull request by fraserscottmorrison**
StatusBarOverlay will automatically show a "No Internet Connection" bar when your app loses connection, and hide it again. It supports apps which hide the status bar and The Notch

## Project URL
https://github.com/IdleHandsApps/StatusBarOverlay

## Description
Added StatusBarOverlay
 
## Why it should be included to `awesome-ios` (optional)
Cause its awesome ;)

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by aaronjsutton** [comment]
Perhaps this would be better suited for a UI category, opposed to Networking? What do you think @lfarah @lukecrum

**Comment by lukecrum** [comment]
I agree @aaronjsutton

**Comment by lfarah** [comment]
Agree we need another category for this one.
We have [/(Activity Indicator](https://github.com/vsouza/awesome-ios/#activity-indicator) and [/Alert & Action Sheet](https://github.com/vsouza/awesome-ios/#alert--action-sheet) under UI. What do you guys think? 🤔

**Comment by lukecrum** [comment]
I think activity indicator is a good fit

**Comment by dkhamsing** [comment]
Please create a new pull request and add to activity indicator 

Thx!

**Comment by fraserscottmorrison** [comment]
Cheers guys - new PR added

**Pull request closed without merging**
