### PR TITLE
Add FCAlertView to Alerts section

### PR DESCRIPTION
**Pull request by yoha**
Added FCAlertView to the Alerts section.

## Project URL

https://github.com/k9101/FCAlertView

## Description

FCAlertView is a Flat Customizable AlertView for iOS.

## Why it should be included to `awesome-ios` (optional)
It's awesome

## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 8 or later
- [x] Supports Swift 3
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
1351 | [301](https://httpstatuses.com/301) | https://github.com/jaydee3/JDFlipNumberView redirects to<br>https://github.com/calimarkus/JDFlipNumberView
1447 | [301](https://httpstatuses.com/301) | https://github.com/jaydee3/JDStatusBarNotification redirects to<br>https://github.com/calimarkus/JDStatusBarNotification


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by lfarah** [comment]
@yoha amazing README with the images!! 👏 👏 

Thanks for contributing! 😃

**Comment by yoha** [comment]
@lfarah Glad to contribute back! 👍

**Comment by yoha** [comment]
@lfarah I have a question; I want to include a project that's written in obj-c but the contribution guideline specifies that project not written in swift 3 is ineligible. So, shall I just ignore the swift 3 support checkbox when doing pr?

**Comment by lfarah** [comment]
@yoha That rule is only for Swift projects. Objective-C projects are more than welcome in AwesomeiOS, so please send a pull request! 😃 👍

**Pull request merged**
