### PR TITLE
Add voice-overlay-ios

### PR DESCRIPTION
**Pull request by spinach**
Adding the voice-overlay-ios library

## Project URL
https://github.com/algolia/voice-overlay-ios

## Category
Voice category (new) inside UI

## Description
Voice overlay helps you turn your user's voice into text, providing a polished UX while handling for you the necessary permissions.

## Checklist

- [x] Only one project/change is in this pull request
- [x] Has unit tests, integration tests or UI tests
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Too many changes (when adding, please keep it to one project per Pull Request)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by spinach** [comment]
The danger warning triggered because I am adding a new sub-category `Voice`

**Comment by lfarah** [comment]
hey @spinach, thanks for contributing! I saw your library a couple days ago somewhere and I was already gonna add it to next week's AwesomeiOS.Weekly 🎉

**Comment by spinach** [comment]
Thanks @lfarah 😄

**Pull request merged**
