### PR TITLE
Add OverlayComposite

### PR DESCRIPTION
**Pull request by aaronjsutton**
## Project URL
[OverlayComposite](https://github.com/aaronjsutton/OverlayComposite) - An asynchronous, multithreaded, image compositing framework written in Swift. 
## Description
Added the OverlayComposite framework to Graphics. Had to open new PR due to branch issues on my fork. 
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 4 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by lfarah** [comment]
I'm thinking that [/Image](https://github.com/vsouza/awesome-ios/#image) fits better. What do you think?

**Comment by aaronjsutton** [comment]
I agree, I'll move it.

**Comment by aaronjsutton** [comment]
Moved. @lfarah

**Comment by lfarah** [comment]
@aaronjsutton thanks 👍

**Pull request merged**
