### PR TITLE
Add SwiftyUI

### PR DESCRIPTION
**Pull request by haoking**
High performance and lightweight UIView, UIImage, UIImageView, UIlabel, UIButton, Promise and more.

SwiftyView GPU rendering Image and Color
 UIImage Extensions for Inflation / Scaling / Rounding
 Auto-Purging In-Memory Image Cache
 SwiftyImageView extension 10+ animations
 SwiftyImageView 150% High performance more than UIImageView, depending on UIView-package, Image-GPU and Image-Cache
 SwiftyLabel 300% High performance more than UIlabel, depending on UIView-package and TextKit
 SwiftyButton 300% High performance more than UIButton, depending on UIControl-package, TextKit and BackgroundImage-Advanced
 lightweight, almost one class for each UI
 UI loading thread-safe
 Block-Package to more easy to use
 Easy and simple to use, all APIs are same to system APIs

## Project URL

https://github.com/haoking/SwiftyUI
## Description

High performance and lightweight UIView, UIImage, UIImageView, UIlabel, UIButton, Promise and more.
## Why it should be included to `awesome-ios` (optional)
There are not so many Libs focusing on the performance of Base UIKit.
## Checklist

- [x] Only one project/change is in this pull request
- [x] Addition in chronological order (bottom of category)
- [x] Supports iOS 9 / tvOS 10 or later
- [x] Supports Swift 3 or later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English

### CODE REVIEW

**Comment by danger-awesome-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues, a project collaborator will take care of these, thanks :)</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
520 | [301](https://httpstatuses.com/301) | https://github.com/bwide/BWCollectionView redirects to<br>https://github.com/bwide/CollectionNode
2764 | [301](https://httpstatuses.com/301) | http://www.coreint.org/ redirects to<br>http://coreint.org/


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by haoking** [comment]
Sir, I do not very understand that warning. I have no idea what I should do to fix it?

**Comment by lfarah** [comment]
@haoking don't worry about that. We'll fix it

**Comment by dkhamsing** [comment]
Thx

**Pull request merged**
