### PR TITLE
add three frameworks in UI

### PR DESCRIPTION
**Pull request by w11p3333**
## Checklist

- [ ] Only one project is in the request
- [ ] Addition in chronological order (bottom of category)
- [ ] `Travis CI` pass
- [ ] Supports iOS 7 and later
- [ ] Has a commit from less than 2 years ago
- [ ] Has a **clear** README in English

### CODE REVIEW

**Comment by w11p3333** [comment]
add three frameworks in UI

**Comment by dkhamsing** [comment]
These are already on awesome-ios
- UITableView-FDTemplateLayoutCell
- LCFInfiniteScrollView

In the future, please check before. Also, one project per pull request

Thanks

**Comment by lfarah** [comment]
```CYLTabBarController``` also cannot be added because it's ```README.md``` isn't in English:
> Only have README in another language (Chinese, Japanese, Portuguese and etc)

**Comment by dkhamsing** [comment]
@lfarah thanks!

Closing this..

**Pull request closed without merging**
