### PR TITLE
Add UIImageColors

### PR DESCRIPTION
**Pull request by jathu**
## Project URL

https://github.com/jathu/UIImageColors
## Description

 iTunes style color fetcher for UIImage. :large_orange_diamond:[e]
## Checklist

- [x] Only one project is in the request
- [x] Supports iOS 7 and later
- [x] Has a commit from less than 2 years ago
- [x] Has a **clear** README in English
- [x] CI: ok (issue fixed separately)

### CODE REVIEW

**Comment by victorgama** [comment]
Please rebase your changes so we can get this merged, ok?

**Comment by dkhamsing** [comment]
@jathu please  update pull request

**Comment by jathu** [comment]
It should be good now

**Comment by dkhamsing** [comment]
Sorry this is not right, will close it 
Can you reopen? Thanks

**Pull request closed without merging**
