### PR TITLE
GH Icons and new categories

### PR DESCRIPTION
**Pull request by bre7**
* Replaced 🔶 with :large_orange_diamond: (as per the guidelines)
* Replaced ⌚ with :watch:
* Added new categories
 * Library and Frameworks - **Permissions**
 * Library and Frameworks - **Messaging**
 * Testing - **Other Testing** (needs a better name? Testing Tools maybe?)
 * **Platforms**
 * **Tools** (needs a better name?)

### CODE REVIEW

**Comment by vsouza** [comment]
Github don't renderize icons in large Markdown files. Can't merge this :cry: sorry.

**Comment by bre7** [comment]
Really ? :( What's the file size limit ?

**Comment by vsouza** [comment]
I sent an email to github team, and i received this response:
screen shot 2015-08-23 at 11 37 12 pm

**Comment by bre7** [comment]
March 6, might have been fixed by now since it's working

**Comment by vsouza** [comment]
nice! @dkhamsing, @victorgama and @lfarah can help me in new categories, before the merge?

@bre7 thanks for you patience.

**Comment by bre7** [comment]
np :wink:

**Comment by dkhamsing** [comment]
Wow thanks for all the work, looks good

**Comment by dkhamsing** [comment]
Messaging got duplicated but I will fix it

**Comment by vsouza** [comment]
:clap: :clap: :clap: :clap:  thanks @dkhamsing

**Pull request merged**
