### PR TITLE
Arranged in alphabetical order

### PR DESCRIPTION
**Pull request by pjebs**
- added Easy Social
- added Obfuscator-iOS

### CODE REVIEW

**Comment by pjebs** [comment]
Any problems?

**Comment by dkhamsing** [comment]
CI checks all the links in the readme to help find issues

**Comment by pjebs** [comment]
Where'd mine go wrong?

**Comment by victorgama** [comment]
The failed item has already been whitelisted by @dkhamsing. Besides that, I don't think it is necessary to add a new category to hold only one item. Do you mind moving _Easy Social_ to another one? Thanks!

**Comment by victorgama** [comment]
@dkhamsing @vsouza @lfarah Are you okay with the proposed alphabetical sorting?

**Comment by dkhamsing** [comment]
looks ok, thanks

**Comment by pjebs** [comment]
Reason for new category is I expect more libraries in the social networking category

**Comment by pjebs** [comment]
Is that okay or should I move it to another category?

**Comment by victorgama** [comment]
I recommend you to move it to another category. If the list of social-related libraries eventually gets bigger, one of the contributors can rearrange them.

**Comment by pjebs** [comment]
Done

**Comment by victorgama** [comment]
Thank you!

**Pull request merged**
